>Drosophila_melanogaster_gnl|BL_ORD_ID|861 gi|24639561|ref|NP_726885.1| Hsc/Hsp70-interacting protein related, isoform A [Drosophila melanogaster]
M-----------------------------------------------------------
------------------------------------------------------------
-------------AFTMQTGDLKKLKYFI-------------------------------
-DFALENPTFLNMPQLQFVKDFVEK-------FGGTVPPGQFNGGSAGGKCPFGGVAGAK
ANEPANAPEDSEDEKSLSDPESDVELDMEGVIEADSDPAQPMGNYSKKATE---------
--EEVEQASELRAQAASAYGQQ--------KFDEAIALYTKAIELSPGNALFHAKRGQAF
LKLKKPNACIRDCDVALELNSDLAAGYKFRGRARRLLGDFELAAHDLRQACKLDFDEETD
---------EWLKEVTP-NAKKIEQHRLKQERRQAERKIKERQRDQRRARKEQEKHNASS
GGSSGEFSGGNPGNG------------------------NMSDILGAMSDPEVSAAIQDI
LSNPGNITKYASNPKIYNLIKKI---VPGGDVGAAFGQAGEKAGKPSEPKPKKDSADFVD
DGLD
>Branchiostoma_floridae_gnl|BL_ORD_ID|1483 jgi|Brafl1|63921|fgenesh2_pg.scaffold_2000350
MENLHYVTDISS------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------KELFVLDPELVITKDVCTS-------PAMPDLVEQHPKGHSTSAGTPQGKAFVF
PVTPPGSPILQRTCQARSAWFNTFIIDAGTPMDGWAHDGLGDGATTARKRE---------
--TGRDNVQHLPHSNGPHYGSTPPARDDYTGVRGRVSALPVRPGLLT-------------
------------ADELSPTLREEVQRAYIYYGYRVNLTTW--------------------
---------ECIKGLFALSNETVN--IWSHLLPTVYFVVLLTKEGSQE------------
---------------------EGYARNVRLAQEICA------------IDPEVLAAFQDV
SQHPENLAKYQSNPKIANLIAKMSTKFGGPGGGPGGPPGGPPMGDPPADPPAGEPP--VD
DGLD
>Ciona_intestinalis_gnl|BL_ORD_ID|11836 jgi|Cioin2|295862|estExt_fgenesh3_pg.C_1620021
M---------TSRCSAYCCVTVSD------------------------------------
------------------------------------------------------------
------LYGNDTIVNVTPEMLIEKIKEMAVKQITA-DTEATGNVGQYRLILINNTPRSLC
DDKTAKQESLLEGDSTLLLKNRNNK-----QPMSSLVKDGVVSHEGPSLSSIARATEGLP
AMSGASTSSETSDMIGAATSSEQVEQTLRKVLLALLELSYKFMHFNDDQKS---------
--KREVEFEVSDVKHLTDMGFSEA------RAKRALVLNNMNTNLA--------------
------------MEWLLQHADDSSDDEQMETSGPPSVG----------------------
---------QRFRKFKP-NPTHLT--SLMD-----------MGFNKEESVQALKINNNNL
NSACEWLLGDRKVDDSHDVEDEMLNPESELYKALVA---NPTIHIG-LHDRKVLEALEDM
VENPWRRNSWAYESAVGNVILQILKLYNKYSTSAPQTNP---------------------
----
>Homo_sapiens_gnl|BL_ORD_ID|15261 gi|55770884|ref|NP_057256.2| ubiquitin-associated domain-containing protein 1 [Homo sapiens]
MFVQE----EKIFAGKVLRLHICA------------------------------------
------------------------------------------------------------
------SDGAEWLEEATEDTSVEKLKERCLKHCAHGSLEDPKSITHHKLI-HAASERVLS
DARTILEENIQDQDVLLLIKKRAPSPLPKMADVSAEEKKKQDQ-KAPDKEAILRATANLP
S--------YNMDRAAVQTNMRDFQTELRKILVSLIEVAQKLLALNPDAVELFKKANAML
DEDEDERVDEAALRQLTEMGFPEN------RATKALQLNHMSVPQA--------------
------------MEWLIEHAEDPTIDTPLPGQAPPEAEGATAAASEAAAGASATDEEARD
ELTEIFKKIRRKREFRA-DARAVI--SLME-----------MGFDEKEVIDALRVNNNQQ
NAACEWLLGDRK--PSPEELDKGIDPDSPLFQAILD---NPVVQLG-LTNPKTLLAFEDM
LENPLNSTQWMNDPETGPVMLQISRIFQTLNRT---------------------------
----
>Nematostella_vectensis_gnl|BL_ORD_ID|26546 jgi|Nemve1|246357|estExt_fgenesh1_pg.C_2130024
MRDFELQGLKSLRSVPLIRIKVTC------------------------------------
------------------------------------------------------------
------TSGKDQSLAVSLKDTVSLVKDRVL------GGEFCKESSFYKLV-VAKTRRNLS
DENTLEKEGISEDDELILLKRRHSS-----ACDHEKEKKRITC-KIPDISTIHKLTSTLP
A-------DEDTEVPTASSTQFNFNRELRRILVSLIDSSILLQSLDEDSQE----ASTAK
PEEPSLTVDPVSLKQLTDMGFDTA------RATKSLLANRMSPMLA--------------
------------MEWLLQHESDSDIDEPSTPSTSQGRTH---------------------
---------RKRREFTP-NPQSVR--NLKE-----------MGFEEEEIMVALKVSGNNP
EAACDWLLGDRK--EGAMSSDEGLDPESPMYKAIME---NPLVQLS-LYNPRVLGAFEDM
LDSPNTSNVYINDPETGPVLLQISCIVQGFAR----------------------------
----
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISASAQSQSPSSRPE
NTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPLFWIGVGVGLSA
LFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNS-GFPSGSPFP---FP---FPPQTSP
ASSPFQSQSQSSGATVDV---TATK------------------------------VETPP
STKPKPTPAKDIEVDKPSVVLEASKEKKEEKNYAFEDISPEETTKESPFSNYAEVSETNS
PKETRLFEDVLQNGAGPANGATAS------EVFQSLGGGKGGPGLS--------------
------------VEALEKMMEDPTVQKMVYPYLPEEMRNP--------------------
---------ETFKWMLK-NPQYRQ--QLQD----MLNNMSGSGEWDKRMTDTLKNFDLNS
P-------------EVKQQFNQIGLTPEEVISKIME---NPDVAMA-FQNPRVQAALMEC
SENPMNIMKYQNDKEVMDVFNKISQLFPGMTG----------------------------
----
>Nematostella_vectensis_gnl|BL_ORD_ID|11371 jgi|Nemve1|132153|e_gw.305.17.1
M-----------------------------------------------------------
---------------------------------------------------AAEGAEMSK
INVVVKTSKNKETIAVEPTATIKEFKEMI-------SEKFGAPVPQLCLI---FAGRILK
DHDTLASSAIKDGLTVHLVIKSENR------------------------------VRTAA
SCKP-CFPGNNHFTPSPPTALS---------------------------------PSVPL
PTGTPNPLDLAGLGGLGAMGQSGNLQEMTQQLQQQMMSNP--------------------
-------------DTMRQILDNPIVQSMMSNP----------------------------
---------ELMRNMIL-SNPQMQ--QLVERNPEISHILN--------------------
--------------------------NPDLMRQTMEMARNPSVMQEMMRNQDRALSNLES
L------------PGGFNALQRMYTDIQEPMMNAAQEQVFC-------------------
----
>Nematostella_vectensis_gnl|BL_ORD_ID|2973 jgi|Nemve1|45732|gw.355.81.1
MDNP--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------EVCRSLMDSS--------------------
-------------ELCRSIMDNPGVCRSLMNNP---------------------------
---------EVCRSLMD-SSEVCR--SLMD-NPEVCRSLMDSSEVCRSIMD---------
--------------------------NPEVCRSLMD---NPEVCMSIMDNPEVCRSLMDS
SE---VCRLLMDSPEVCRSLMD--------------------------------------
----
>Ciona_intestinalis_gnl|BL_ORD_ID|3654 jgi|Cioin2|231500|fgenesh3_pg.C_scaffold_585000003
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------KKTEVSDLNENIVNSNSGK------------------------------VEAIS
NTTPAVHSGLSIEIDDISLKVEKSSKKMPENSYAYTNNSEEQTLTNE-------------
--------EKLGVKHTLDNGVEDL------GVSEELSAESFNSNPSPNSNDELS------
------------LDSGIVSLDDQEADKMNPNEMNPSNNR---------------------
---------KRLRSSLV-SDQSAKRERRSLGKKVMFEKVKIFFFPRKQSFITVPSQGGST
LG--------------------------------MDLKHNGFKELT-LEQHKISIARRRR
L----AIKEHDRQQRIESKLRQYLLVEKPPEV----------------------------
----
