>Branchiostoma_floridae_gnl|BL_ORD_ID|30467 jgi|Brafl1|125587|estExt_fgenesh2_pg.C_1880092
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DAEKIAQLQAFVQLCKV
SPEV-LHDPKLQFFKSWM----ESM---------GATIPPA---ATSQS-----GTTQDS
PPP-MG-----SASK-----PPPPPE-PESEESE--------------------------
-----E------------------------------------------------------
--------------------------SEESDLDIDMEGVIEGDSDPPPDMG-DDSIEV--
------TEEMM----------------------DQSND-KRAEAQAAMNEGEKEKAIELW
TEAIRLNPQSAPLFAKRASCF-----------LRM----SKPNAAIHDCDRAIELNPDSA
A-------GYKWRGKAHKL-LGH-----------WEESAKDLATAQKI----------DY
DDD-TYLLLKEVQPKALKIKEHQRKKERKREEKELRARKKRVQKAKEAQEKAKREQEERE
RQ-----GPSGMPGFGGGGFPGMGGFPGMGSFPGGAGGAAGGMPGGMP-----GGFPGGM
PGGMP------GGMPGGMPGGMPGGMPGGMPDINKIMSDPEIMAAFQDPEVLAAFQDVSQ
HPENLAKYQSNPKIANLIAKMS---------------------TKFGGPGGGPGGPPGG-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-PPMGDPPADPPAGEPP--VDDGLD-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Homo_sapiens_gnl|BL_ORD_ID|30316 gi|19923193|ref|NP_003923.2| hsc70-interacting protein [Homo sapiens]
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DPRKVNELRAFVKMCKQ
DPSV-LHTEEMRFLREWV----ESM---------GGKVPPATQKAKSEE-----NTKEEK
PDS-KK------------------VEEDLKADEP--------------------------
-----S------------------------------------------------------
--------------------------SEESDLEIDKEGVIEPDTDAPQEMG-DENAEI--
------TEEMM----------------------DQAND-KKVAAIEALNDGELQKAIDLF
TDAIKLNPRLAILYAKRASVF-----------VKL----QKPNAAIRDCDRAIEINPDSA
Q-------PYKWRGKAHRL-LGH-----------WEEAAHDLALACKL----------DY
DED-ASAMLKEVQPRAQKIAEHRRKYERKREEREIKERIERVKKAREEHERAQREEEARR
Q--------------------------------------SGAQYGSFP-----GGFPGGM
PGNFP------GGMP-GMGGGMPG--MAGMPGLNEILSDPEVLAAMQDPEVMVAFQDVAQ
NPANMSKYQSNPKVMNLISKLS---------------------AKFGGQA----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Takifugu_rubripes_gnl|BL_ORD_ID|2722 jgi|Takru4|618641|e_gw2.209.28.1
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DPRKLSELKGFVQLCET
KPEM-LHLPEMSFFREWL----LGM---------GATIPPL---SKPKE-----SCQPEP
PVL-S-------------------------------------------------------
-----E------------------------------------------------------
--------------------------SDESDIEIDNDGVIEPDTDEPQEMGASENVEV--
------TEEMM----------------------DQANN-KKMEAIDAQGEGELQKALDLF
TEAIKLNPCLAVLYAKRASVF-----------IQL----QRPNAAIRDCDRAIQINPDSA
Q-------PYKWRGKAHRL-LGH-----------WEEAAKDLATACKL----------DY
DES-ASAMLKEVQPKANKIMEHRRKYERKREEKLIRERQERIKKAREEHARAQKDEEARQ
S--------------------------------------AGA---SFPVTVELGCFPGA-
-GGFS------GGLP------------GGMPNFEAFLNDPELLMAMKDPEVMAAFSDVSK
NPANIAKYQSNPKIMAIINKLS---------------------SKFGAPPQP--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Trichoplax_adhaerens_gnl|BL_ORD_ID|2773 jgi|Triad1|37729|estExt_Genewise1Plus.C_50584
MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------TSIQHLRLLEQFIDHCKN
NPAM-LRLPELKFFADFI----VSL---------GGKIPEA---AEPEEEKVEESINDES
ESQ-VG-----SANY-----IILCPEK---------------------------------
-----E------------------------------------------------------
--------------------------SEESDLDIEAEGVIEGDDDAPQPMG-DGSKEV--
------TEEML----------------------EEASE-KRQNANIALADGNIDEGIKLY
AEAIMLNPQSAPLFAKRAGGY-----------IKA----KKPNAAIRDCDKAIQLNPDSA
Q-------AYKWRGIAYRM-LGK-----------WDKSASDLRLSVKI----------DF
SED-AQEVLNYVQPRAQRIQEHQRKIERRKAEKEIKERRERVRLAQEAKEKARKEEEERA
RKEEESGTPGGFPGAGAGGFPGAGGFPGAGGFPGAAG--AGGFPGA-------GGFPGAG
AGGFPGAGAGAGGFPGA--GGMPGAGAGQMPDINAMLNDPEIIAAFQDPEIMAAFQDVSM
NPQNVSKYQNNSKVMNIINKLA---------------------SKYGKQN----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Drosophila_melanogaster_gnl|BL_ORD_ID|866 gi|45549303|ref|NP_570074.3| Hsc/Hsp70-interacting protein [Drosophila melanogaster]
MA----------------------------------------------------------
------------------------------------------------------------
----------------------------------------FTMQTGDLKKLKYFIDFALE
NPTF-LNMPQLQFVKDFV----EKF---------GGTVPPG----------QFNGGSAGG
KCP-FGGVAGAKANE-----PANAPEDSEDEKSL--------------------------
-----S------------------------------------------------------
--------------------------DPESDVELDMEGVIEADSDPAQPMG-NYSKKA--
------TEEEV----------------------EQASE-LRAQAASAYGQQKFDEAIALY
TKAIELSPGNALFHAKRGQAF-----------LKL----KKPNACIRDCDVALELNSDLA
A-------GYKFRGRARRL-LGD-----------FELAAHDLRQACKL----------DF
DEE-TDEWLKEVTPNAKKIEQHRLKQERRQAERKIKERQRDQRRARKEQEKHNASS----
-----------------------------------------------------GGSSGEF
SGGNPGNG-----------------------------NMSDILGAMSDPEVSAAIQDILS
NPGNITKYASNPKIYNLIKKIVPGGDVG---------------AAFGQAG----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-EKAGKPSEPKPKKDSADFVDDGLD-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Branchiostoma_floridae_gnl|BL_ORD_ID|1483 jgi|Brafl1|63921|fgenesh2_pg.scaffold_2000350
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------ENLHYVTDISSK
ELFV-LD-PELVITKDVC----TS--------------P-----AMPDLVEQHPKGHSTS
AGT-PQGKAFVFPVT-----PPGSPILQRTCQAR--------------------------
-----S------------------------------------------------------
--------------------------AWFNTFIIDAGTPMDGWAHDGLGDG-ATTARK--
------RETGR----------------------DNVQH-LPHSNGPHYGST---------
------PPARDDYTGVRGRVS-----------ALP----VRPGLLTAD-ELSPTLREEVQ
R-------AYIYYG--YRVNLTT-----------WECIKGLFALS---------------
-NE-TVNIWSHLLPTVYFVV--LLTKEGSQEEGYAR----NVRLAQE-------------
------------------------------------------------------------
------------------------------------------ICAI-DPEVLAAFQDVSQ
HPENLAKYQSNPKIANLIAKMS---------------------TKFGGPGGGPGGPPGG-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-PPMGDPPADPPAGEPP--VDDGLD-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Cladonia_grayi_gnl|BL_ORD_ID|8548 jgi|Clagr2|91224|fgenesh1_kg.11_#_130_#_isotig05539
MA---DALKAEGNKAFAEKNYDEAIEKFSQAIEL----EPDNHVLYSNRSGAWASKRDFD
KALEDANKTTELKPDWAKGWGRKGAALHGTGDLVGAHDAYEEALKHDPNNAQSKSGLAAV
KRAIDAEAQADGASPGAGLGNIFNDPQMIQKLANNPKTRGLLADPQFMQKLQRLRQNPND
IGTE-MQDPRFLQVMSVL----LGIDM-SFANPSGEGSG-----------APEVNGTKEA
EEDIPMPDARPASAQPSEPAKPHEPDSKPEPEPE--------------------------
-----P-EDEEAIAAKKAKEEADAEKKLGTENYKKRQFEAAIEHYDKAWSLHQDITYLTN
KSAAQFEKGDYTGAIESCETAIEKGREVLADFKIIAKAFGRIGSAYEKIGDLPNAITNYQ
KSLTEHRTPDMLNKLRAAEKAQIKAETEAYINPEEAEK-ARELGGQKFKEADWPGAVEAY
TEMIKRAPDDPRGYSNRAAAL-----------IKL----MTFPSAVADCDIAIKKDPNFI
R-------AYLRKAQAYFA-MKE-----------YSKCTDTCAEAMEH----------DV
----GGANRREIEQQQQKALQAQYA-GRAGETEEQT------------------------
------------------------------------------------------------
--------------------------------MERIQKDPEIMGILQDPIMQSILQQAKG
DPAALQDHMKNADIRNKITKLVAAGVIRTR------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Ustilago_maydis_gnl|BL_ORD_ID|2056 jgi|Ustma1|2057|UM02057
MS--VADLKAKGNAAFAAKDYQGAIQNYNDAIAAATSAEDNVHVLYSNRSACYAGLRDWN
KALEDAEACINANPSFAKGYGRKGAALHGARRLEEAVDAYDAGLKIAPEDAGLKKGLADV
RRAVENEA-ANGPGPEASLGQMFNDPQLFAKLSANPKTAGLLSDPAFMAKLKSIQANPKE
AGMA-FQDPRMIQVMGVL----MGIDLQAFERPEGSNELPGDLENRRQDIEEQTGASASK
PKP-AAAAAASTSSADDVEMKDAKPSSSTTAQSA--------------------------
-----PVEEEEEDEEKKAKAAADAEKKLGNERYLKRDFEAAIAHYQKAWELHKDITYLNN
LGACYFEQAKYDDCIKACEQAVEEGRSMRADFKLVAKAYGRIGSAYAKQDQLDLAITNFE
KSLTEHRTPDVLAKLRETEKLQKERTRQAYIDPAKAEA-ERARGNELYKNGDFPGAVAAF
TEAIKRDPSDARGYTNRASAY-----------TKL----AALPEALKDSEEAIKVDPNFV
K-------GYIRKANVLAS-MKE-----------FTKAMEACQQAENV----------DA
AQQGGAKNAREIQALMNKCMNELYS-QRSGETEQET------------------------
------------------------------------------------------------
--------------------------------LQRAMRDPEVAQIMQDPVMQSILQQAQG
NPAALQEHMKSPIIRDKVQKLIAAGIIRTR------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Saccharomyces_cerevisae_gnl|BL_ORD_ID|5053 gi|6324601|ref|NP_014670.1| Sti1p [Saccharomyces cerevisiae S288c]
MSLTADEYKQQGNAAFTAKDYDKAIELFTKAIEVS---ETPNHVLYSNRSACYTSLKKFS
DALNDANECVKINPSWSKGYNRLGAAHLGLGDLDEAESNYKKALELDASNKAAKEGLDQV
HRT----QQARQAQPDLGLTQLFADPNLIENLKKNPKTSEMMKDPQLVAKLIGYKQNPQA
IGQDLFTDPRLMTIMATL----MGVDL-NMDDINQSNSMPK---------EPETSKSTEQ
KKD-AEPQSDSTTSKEN---SSKAPQKEESKESE--------------------------
-----PMEVDEDD----SKIEADKEKAEGNKFYKARQFDEAIEHYNKAWELHKDITYLNN
RAAAEYEKGEYETAISTLNDAVEQGREMRADYKVISKSFARIGNAYHKLGDLKKTIEYYQ
KSLTEHRTADILTKLRNAEKELKKAEAEAYVNPEKAEE-ARLEGKEYFTKSDWPNAVKAY
TEMIKRAPEDARGYSNRAAAL-----------AKL----MSFPEAIADCNKAIEKDPNFV
R-------AYIRKATAQIA-VKE-----------YASALETLDAARTK----------DA
EVN-NGSSAREIDQLYYKASQQRFQPGTSNETPEET------------------------
------------------------------------------------------------
--------------------------------YQRAMKDPEVAAIMQDPVMQSILQQAQQ
NPAALQEHMKNPEVFKKIQTLIAAGIIRTGR-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Ustilago_maydis_gnl|BL_ORD_ID|5358 jgi|Ustma1|5359|UM05359
MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----QQTPLAYAVAQWL----------------------------------QQSSTSVP
ADQKAKLQQAAKSVSEAFGVDTSSAEQQAQYGSG--------------------------
-----P------------------------------------------------------
--------------------------GLQAIFDIFLKTQAKMGAAPAPAAA-SSSSTAPA
AAAATPSDEDL----------------------AKAEQ-LKAEGNKAMSAKDYGAAIEAY
GKAIELNPNSPVYFSNRAAAF-----------SQI----GQHDSAIDDAKQASKIDPKFG
K-------AYSRLGHALFS-SGR-----------YQEAVEAYQKGVEV----------DP
SNE---------------VLKKGLAASKEQLSSSSSSNANDATASRGAADAVSAPSA---
-----------------------------------------------------GADAGAG
AGGFPNFGGGAGGM-------------------------PDLAAMMNNPMIAQMAQNLMS
NPDSLASLMNNPMLRQAAERFGSGGGMPDMSSMMNDPALRDMARNFMGGAGRGAGGNGGN
NMVDVGGSEMSVWKRLWRRLAVFGRRSFLISPCIPTVSCVCLINTTSLSRIMSNGTPSVR
VLYFASARTTIGHSSETISLPTTPFPLASLITLIANKYSSRGAEAVLRTCRWSVDNTLIE
IDELIEWTLHGREEVAAIPPMPTSPSREVAVDATKVELVSKPLLASAALNKFSGYHFNPS
SSGVDSNLLILLHGLGDNDSGFFNLGQNLQKTLPQTAILTLQAPLKVPFLEGDHWMWYPA
FDQFAELLTKPNPTVTVASVVALLDHLVGKCGWSAGSIHIFGFGQGATLALEVLISWSKS
HSQPLGSIVSIHGSFISHPTISSSSTPVLHIYRSAREIPLDSTRWSSHRKSTSALTLHRL
RGNEEDESMLKGSEWDSVMSFWSKFFRNRIKWELEGKVVPIG------------------
-------------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
ME----------------------------------------------------------
-----------------------------NLTLVSCSASSPKLLIGCNFTSSLKNPTGFS
RRTPNIVLRCSKISASAQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVAS-
-PSVPVPPPSSSTIGSPLFWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQ
FNNSGFPSGSPFPFPFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPK------
-----P------------------------------------------------------
--------------------------TPAKDIEVDKPSVVLEASKEKKEEK-NYAFED--
------------------------------ISPEETTKESPFSNYAEVSETNSPKETRLF
EDVLQ-NGAGPANGATASEVF-----------QSLGGGKGGPGLSVEALEKMME-DPTVQ
KMVYPYLPEEMRNPETFKWMLKN-----PQYRQQLQDMLNNMSGSGEW------------
-DKRMTDTLKNFDLNSPEVKQQFNQIGLTPEEV---------------------------
------------------------------------------------------------
--------------------------------ISKIMENPDVAMAFQNPRVQAALMECSE
NPMNIMKYQNDKEVMDVFNKIS---------------------QLFPGMTG---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Branchiostoma_floridae_gnl|BL_ORD_ID|29564 jgi|Brafl1|124348|estExt_fgenesh2_pg.C_1450100
MA----------------------------------------------------------
------------------------------------------------------------
--------------------ESEDSGSELIKIVVKTPKSKETVEIEATSTITEFKEAISQ
KFGQPVEQLCLIFAGKIL----KDHETLEKIGIKDGLTVHLVIRQKVGSQQGPSASGSSA
PAA----SSTPSAPAAAAAGTAPAAAPQPAPAAA--------------------------
-----P------------------------------------------------------
--------------------------FGVGGMG-GLSGLQNLGMGSANFMEMQQRMQQEL
LRNPDMLTQMM----------------------ENPFV-QSMMSN-----------PDLL
RNLIVSNPQMQQLMERNPEIT-----------HML----NNPELMRQTMELA--RNPAML
Q-------EMMRSQDRALSNLESIPGGYNALRRMYTDIQEPMMNAAQE----------QF
GNN-PWASLVGGG-----------TSNPQQGQENREPLPNPWAPQGSSTT----------
------------------------------------------------------------
-----------AATTSTTTASTTASSPAGQGLPGGLPGGIPTSGMFNSPGMQSLMQQMVD
NPQLMQNMLQAPYMQSMMQSMGQNPDMASQIIGNNPLFQGNPQL---------------Q
EQMR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------QQLPTFMQQMQ
NPEVQAAVTNPRVLQAIMQIQQGMQQLQAEAPVLLPGVPPAGG-----------------
-------------------MPASPAAPASSAASSSTDSTTTTTPTPTTASASTTSPSTAA
PPTGPTEAQQ-----QLLQQMLQTLAGG-NAMQP----PEVRFRSQLEQLETMGFVNRAA
NIQALTATNGDVNAAIDRLLQAQ--
>Ciona_intestinalis_gnl|BL_ORD_ID|5808 jgi|Cioin2|261637|gw1.04q.675.1
------------------------------------------------------------
------------------------------------------------------------
-----------------------------IKITLKTPKEKQEFTVSPKISVKDLKAEVSK
KFNATTEQLVLIFSGKIL----KDAETIDHHMIKNGHTVHLVIKSASRAQ----------
--------PTPPPPTTTQASDAPTS--QSSNSSL--------------------------
-----P------------------------------------------------------
--------------------------FNLGSMG-GLSGLGAMGLDSPNFMEMQQQMQREM
LSNPEMLQRMM----------------------DNPLV-QNMMSN-----------PEII
RNMMSNNPQMQQLMERNPEIT-----------HML----NNPQLMRQTMELA--RNPAML
Q-------EMMRNQDRALSNLESIPGGYNALRRMYTDIQEPMLNAAQE----------QF
GQN-PFAALNETSNS--------GKLNNTQNTENTNPLPNPWGSSPQATT----------
------------------------------------------------------------
-----------TSTTSSTNRPTTTPSTNTAG-----------SGLFNNPAMQNLMQQITD
NPSLMQNMMTAPYMQGMMQNMAENPELAN-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------QQMQ
RPEMQNLFTNPRAMQAMMQMQAAMQTLQQEAPGLMTGLGPTGA-----------------
---------------------------------AVPPTTTTTTSTPSST-----------
TTTNNPASSQ-----ALLNQMMQTLATGPPAAAALS--PETRYRAQLEQLSAMGFVNRDA
NIQALTATNGNVNAAIEFLLG----
>Homo_sapiens_gnl|BL_ORD_ID|2181 gi|40538799|ref|NP_064516.2| ubiquilin-4 [Homo sapiens]
MA----------------------------------------------------------
-----------------------------------------------------------E
--------------------PSGAETRPPIRVTVKTPKDKEEIVICDRASVKEFKEEISR
RFKAQQDQLVLIFAGKIL----KDGDTLNQHGIKDGLTVHLVIKTPQKAQDPAAATASSP
STP---------DPASAPSTTPASPATPAQPSTSGSASSDAGSGSRRSSGGGPSPGAGEG
SPSATA------------------------------------------------------
--------------------------SILSGFG-GILGLGSLGLGSANFMELQQQMQRQL
MSNPEMLSQIM----------------------ENPLV-QDMMSN-----------PDLM
RHMIMANPQMQQLMERNPEIS-----------HML----NNPELMRQTMELA--RNPAMM
Q-------EMMRNQDRALSNLESIPGGYNALRRMYTDIQEPMFSAARE----------QF
GNN-PFSSLAGNSDS---------SSSQPLRTENREPLPNPWSPSPPTSQAPGSGGE---
------------------------------------------------------------
-----------GTGGSGT-SQVHPTVSNPFG----INAASLGSGMFNSPEMQALLQQISE
NPQLMQNVISAPYMRSMMQTLAQNPDFAAQMMVNVPLFAGNPQL---------------Q
EQLR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------LQLPVFLQQMQ
NPESLSILTNPRAMQALLQIQQGLQTLQTEAPGLVPSLGSFGI-----------------
--------------------SRTPAPSAGSNAGSTPEAPTSSPATPA-T----------S
SPTGASSAQQ-----QLMQQMIQLLAGS-GNSQVQT--PEVRFQQQLEQLNSMGFINREA
NLQALIATGGDINAAIERLLGSQLS
>Takifugu_rubripes_gnl|BL_ORD_ID|23716 jgi|Takru4|576577|e_gw2.45.104.1
MA----------------------------------------------------------
-----------------------------------------------------------D
QGAAN--------PGNNNNNKSEASEGTIIKVTVKTPKDKEEIAIAEDASVSQFKEEISR
RFKAKQDQLVLIFAGKIL----KDGDSLSQHGIKDGLTVHLVIKTAHKAADGGSTSASSA
ASP-QAGNTSTSSPGTTPPSTAASTGTPAQPTQA--------------------------
-----P------------------------------------------------------
--------------------------NILTGFG-DLAGLAGLGMGSTNFMELQQQMQRQL
MSNPEMLSQIM----------------------ENPLV-QNMMSN-----------PDLM
RQMIMANPQMQQLMERNPEIS-----------HML----NNPELMRQTMELA--RNPAMM
Q-------EMMRNQDRALSNLESIPGGYNALRRMYTDIQEPMFSAARE----------QF
GNN-PFSALGGNSE----------SGVQPSRTENREPLPNPWGP-PNSSNPPESGGS---
------------------------------------------------------------
-----------TAGSTSTPAGTNPSVSNPLG----VNAGSLGNGIFNSPGMQSLLQQISE
NPQLMQNMLSAPYMRSMMQSLAQNPELASQVLMNNPLFAGNPQL---------------Q
EQFR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------SQLPVFLQQMQ
NPEALSVMTNPRAMQALMQIQQGLQTLQTEAPGLMPSLMTAGV-----------------
--------------------PGIP-------TAGVPSMPTENPA--S-S----------P
SNAGTNAAQQ-----QLMQQMLQMFAGG-GGGSATT--PEVRFQSQLDQLNAMGFINREA
NLQALIATGGDINAAIERLLGSQPS
>Homo_sapiens_gnl|BL_ORD_ID|31107 gi|16753207|ref|NP_038472.2| ubiquilin-2 [Homo sapiens]
MA----------------------------------------------------------
-----------------------------------------------------------E
NGESSGPPRPSRGPAAAQGSAAAPAEPKIIKVTVKTPKEKEEFAVPENSSVQQFKEAISK
RFKSQTDQLVLIFAGKIL----KDQDTLIQHGIHDGLTVHLVIKSQNRPQ-GQSTQPSNA
AGT-----------NTTSASTPRSNSTPISTNSN--------------------------
-----P------------------------------------------------------
--------------------------FGLGSLG-GLAGLSSLGLSSTNFSELQSQMQQQL
MASPEMMIQIM----------------------ENPFV-QSMLSN-----------PDLM
RQLIMANPQMQQLIQRNPEIS-----------HLL----NNPDIMRQTLEIA--RNPAMM
Q-------EMMRNQDLALSNLESIPGGYNALRRMYTDIQEPMLNAAQE----------QF
GGN-PFASVGSSSSS--------GEGTQPSRTENRDPLPNPWAPPPATQSSAT-------
------------------------------------------------------------
-----------TSTTTSTGSGSGNSSSNATG--NTVAAANYVASIFSTPGMQSLLQQITE
NPQLIQNMLSAPYMRSMMQSLSQNPDLAAQMMLNSPLFTANPQL---------------Q
EQMR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------PQLPAFLQQMQ
NPDTLSAMSNPRAMQALMQIQQGLQTLATEAPGLIPSFTP-GVGVGVLGTAIGPVGPVTP
IGPIGPIVPFTPIGPIGPIGPTGPAAPPGSTGSGGPTGPTVSSAAPSET----------T
SPTSESGPNQ-----QFIQQMVQALAGA-NAPQLPN--PEVRFQQQLEQLNAMGFLNREA
NLQALIATGGDINAAIERLLGSQPS
>Trichoplax_adhaerens_gnl|BL_ORD_ID|508 jgi|Triad1|63757|estExt_fgeneshTA2_pg.C_30521
MS----------------------------------------------------------
------------------------------------------------------------
-----------------------SQGNKILDVIVKTPKEKQTISIHENATILEFKEAVSL
QFGAPVDQLCLIFAGRIL----KDSETLSQHSIKDGLAVHLVIKSGTKAQ---TATPSET
TGT---------TTQNTPPMQQQSEGTQQQF-----------------------------
-----P------------------------------------------------------
---------------------------------------VNFGIDPSTFQNMHQYMQQQL
TSNPDMLRQMM----------------------DNPMV-QSMLNN-----------PDLM
QQLIGSNPQMQQLMERNPELS-----------HML----NNPEMMRQALEMA--RNPSML
Q-------EMMRSQDRAMSNLESIPGGFNALRRMYSDIQEPMMNAAQEMNEQMRSSYTNP
GSN-PFSSLLGGAGTQTQPQSQQPSSSPSSTPAGTSPVPNPWENRSTA------------
------------------------------------------------------------
-------------------------------------PGSTSTGMFQSPGMQSMLQQLRE
NPQLMQDTLQSPFVQNMMTQMMNNPQLMQQMLANNPLFNNDPQL---------------S
EQIR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------ENMPNILRQMQ
NPQMQQIISNPQAVQAMLQIQQGFQQLSHAVP----------------------------
---------------------STGNTPGSTTSTTTGTNTTTSSGTGSTT----------T
TTTSSTSPQQQEQFNQLMSQMMQAMTAN-NQQQQSNLQPEVRFRTQLEQLNAMGFVDQAR
NLQVLSATGGDINAAIEQLLR----
>Nematostella_vectensis_gnl|BL_ORD_ID|11371 jgi|Nemve1|132153|e_gw.305.17.1
MA----------------------------------------------------------
------------------------------------------------------------
---------------------AEGAEMSKINVVVKTSKNKETIAVEPTATIKEFKEMISE
KFGAPVPQLCLIFAGRIL----KDHDTLASSAIKDGLTVHLVIKSENRVRTAASCKPCFP
GNN----HFTPSPPTALSPSVPLPTGTPN-------------------------------
-----P------------------------------------------------------
--------------------------LDLAGLG----GLGAMG-QSGNLQEMTQQLQQQM
MSNPDTMRQIL----------------------DNPIV-QSMMSN-----------PELM
RNMILSNPQMQQLVERNPEIS-----------HIL----NNPDLMRQTMEMA--RNPSVM
Q-------EMMRNQDRALSNLESLPGGFNALQRMYTDIQEPMMNAAQE----------QV
FC----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Nematostella_vectensis_gnl|BL_ORD_ID|2973 jgi|Nemve1|45732|gw.355.81.1
MD----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------NPEVCRSL
MDSSELCRSIM----------------------DNPGVCRSLMNN-----------PEVC
RSLMDSSEVCRSLMD-NPEVCRSLMDSSEVCRSIM----DNPEVCRSLMD-----NPEVC
M-------SIMDNPEVCRSLMDS-------------------SEVCRL------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------LMDSPEVCRSLMD---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
------------------------------------------------------------
----YDDIPEARRQA-------VPKTASSPSRGNPALWIGSGIGLLVI-AVGAAFAVGL-
-----------------FKPE-----------------------------------PSQS
KVE-------------TSPT---ASTPPTGGTE-APNTPDTTLGHFSYKVAPENE-----
--------------LQAI----TADNRIRL-RSSAARAYKQMSAA--AAADGIKLQALSG
FRTVEDQDYLFFRVKEER-----AQGAQQR-----------AKVSAPPGRSEHHTGYAMD
IGDATQPN--------THVNVTFEETRAFEWLQKNAPRYSFELSFPKGNSQGVSYEPW--
------------------------------------------------------------
---HWRYVGDKDSLETFYNARNLKS---------------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|4564 647568950 MC7420_3835 D-alanyl-D-alanine carboxypeptidase family [Microcoleus chthonoplastes PCC 7420]
M---KTPDFPGEPV----------------------------------------------
----------------------------------------------------N------L
SESTEEDIPVAVRDTP------DTRRRSRL---QPFLIILAVLGGGAI-VLGLILSSST-
---------SQSPQTITASPQ-----------------------------------PTTT
DTS-------------T------STTPEESESE-SENDVDNLLGHLPYEEAPLSE-----
--------------LEPI----TSDGRIQL-REAAAKKFKAMRAA--AQADGIVLVAISG
YRTQQQQQHLFFDIKAQR-----GQVATQR-----------AEVSAPPGYSEHHTGYAVD
IGDGRTPA--------TNLNTNFENTAAFKWLEENAAYYSFELSFPKGNPQGVSYEPW--
------------------------------------------------------------
---HWRFVGDPDSLETFYKAQNLDRPDLEPSPSSSEPEDESSTREQGTGNRE
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|931 637313549 tll0932 putative carboxypeptidase [Thermosynechococcus elongatus BP-1]
M-----------------------------------------------------------
------------------------------------------------------------
----DQDIPVAERLQP------IPQGKEKP---RQGGWAIASAIVLVG-FMGVGAAW---
-----------------FLSR-----------------------------------PATS
PTA-------------------------TGRAS-TVTPTENLLGHLPYEEAPLSE-----
--------------LEPV----SADGQIKL-RRAAAERFRAMVAA--AQQEGVVLIPLSG
FRSTQDQDYLFFEVKEHR-----AQRASER-----------ALVSAPPGYSEHHTGYAVD
IGDGAQPQ--------THLKETFEDTPAFRWLAKNAARFSFELSFPRNNPQGVSYEPW--
------------------------------------------------------------
---HWRFVGDRHSLQTFYRARQLRLRNAP-----------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|786 641534767 MAE_07870 putative carboxypeptidase [Microcystis aeruginosa NIES-843]
M-----------------------------------------------------------
------------------------------------------------------------
--KPIDDIPEALRDS-------QYRKTTNP---NGLIAIASGLLALVGTGIIALAVL---
-----------------NRPP-----------------------------------ATVK
KPV---------------------INPSPLIKA-TPSPIENILGHLPYEEAPETE-----
--------------LAPI----TGDGAMRL-RKPAAKAFIQMQSD--ARRSGVILMPISA
FRSKATQDKLFFEVKEQR-----NQETRKR-----------AEVSAPPGYSEHHTGYAID
IGDGRAPA--------TNLSSSFANTAAFRWLQNNAAQYSFELSFPENNLQGINYEPW--
------------------------------------------------------------
---HWRFVGDSHSLETFYKAQQLGKQK-------------------------
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|3369 650386693 NIES39_J01590 putative carboxypeptidase [Arthrospira platensis NIES-39]
M-----------------------------------------------------------
-----------------------------------------------------YKNLDNV
PPMTSEDIPEAIRDTPKSDNSNLGKSKRSP---KFWQWLALAIAAFGV-AIALNYQFGIF
VVDRTSINLSASETTDAMQPP-----------------------------------PTTN
PLP----------------------TPSVIPNQ-VSQLPVNLLGHLPYEEAPESE-----
--------------LKNI----TADGVIRL-RRAAAYAFLEMTDA--ARRSGIILVPISG
FRGLEDQEFLFFDIKAQR-----GQVPSQR-----------AQVSAPPGYSEHHTGYAID
VADANFPD--------TDLRETFDQTPAFKWLLDNAAFYSFELSFPKDNPLGVSYEPW--
------------------------------------------------------------
---HWRYVGDRHSLETFYKARSIDVASPSDLVNGDN----------------
>Arthrospira_sp_PCC_8005_gnl|BL_ORD_ID|2565 648387796 APCC8_010100013340 M15B family D-Ala-D-Ala carboxypeptidase VanY [Arthrospira sp. PCC 8005]
M-----------------------------------------------------------
------------------------------------------------------------
---TSEDIPEAIRDTPNSDHSTLGKSQRSP---KFWQWLALGIVAFVV-ALALNYQFGIL
VVDRTSVNLSASETTDAMQPP-----------------------------------PTTN
PLP----------------------TPSVIPNQ-VSQLPVNLLGHLPYEEAPESE-----
--------------LKNI----TADGVIRL-RRAAAYAFLDMTDA--ARRSGIILVPISG
FRGLEDQEFLFFDIKAQR-----GQVPSQR-----------AQVSAPPGYSEHHTGYAID
VGDANFPD--------TDLRETFDQTPAFKWLVDNAAFYSFELSFPKDNPLGVSYEPW--
------------------------------------------------------------
---HWRYVGDRHSLETFYKARSIDVASPSDLVNGDN----------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|3701 all3702 similar to D,D-carboxypeptidase
M---NKAGFSGEPR----------------------------------------------
----------------------------------------------------D------P
FDELSDDIPVALRDTP------GITPKQRL---QRLIFVTGGVGAFVILAIVSGFVFFI-
-----------------TTPK-----------------------------------KTTE
SQP-------------SPAIADATPMP---TAS-NPADLQAILGHLAYPEAPESE-----
--------------LVPI----SRDGRIRM-RRNAAQRFQEMAQA--ARTAGVILMPISG
FRSVKEQEQLFFAIGAQR-----NQTPAQR-----------AALSAPPGHSEHHTGYAVD
IGDGAAPT--------TNLQAIFENTRAFKWLEANAARFGFEMSFPMDNSQGVSYEPW--
------------------------------------------------------------
---HWRFVGDRDSLETFYKARNLKPVKTPQ----------------------
>Trichodesmium_erythraeum_IMS101_gnl|BL_ORD_ID|3901 gi|113477844|ref|YP_723905.1| unnamed protein product [Trichodesmium erythraeum IMS101]
MKILNKLGLLKKTP----------------------------------------------
----------------------------------------------------D------E
AKLPVDDIPEAVRDEEESAKHQSFKPQKIW---QIWQLLAMGAIALII-SISWHFQFNKT
LNTSPVVQ---------MKQK-----------------------------------ISTK
AVE-------------TSPTQLETPSPSPSFNS-SIKQRENILGHLPYKEASWQE-----
--------------LTPV----FGNQNIRL-RSIAAEKFDLMADV--AWSANIELVPLSG
FRTVGDQQYLFFEVKAER-----GQETSKR-----------AEVSAPPGYSEHHTGYAID
IGDARMPE--------THLEVSFENTKAFQWLQENAENYGFELSFPKDNPQGISYEPW--
------------------------------------------------------------
---HWRFVGDSHSLKTFEEARSLKE---------------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|2419 637618109 syc2418_c putative carboxypeptidase [Synechococcus elongatus PCC 6301]
M-----------------------------------------------------------
------------------------------------------------------------
GFQYDDDVPVAIRSE-------VPTAKARTN--RLLPWVVGGAVAAI--AIGAWAIV---
-----------------QRSS-----------------------------------PTPE
GVE----------------------TP---AES-TAATPNSLLGHRPYADAAPES-----
--------------LTPL----ASNAAIRL-RSPAAKAFDELQAA--AAREGVRLVPLSG
FRSKKDQEALFFDVKAER-----NQSVTER-----------ASVSAPPGYSEHHTGYAID
IGAADQPA--------THLETTFEQTAAFRWLQANAKRFSFELSFPRNNLQQVSYEPW--
------------------------------------------------------------
---HWRFVGDLESLRLFYGDRSGTPAQ-------------------------
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|2376 637459774 glr2377 similar to D,D-carboxypeptidase [Gloeobacter violaceus PCC 7421]
M-----------------------------------------------------------
------------------------------------------------------------
--TDFDDIPVIQRAAAT-----APIPVPTTKRPLPKPPVLAAVAGMVV-AVGLGLFL---
-----------------LLPK-----------------------------------PGEE
-----------------SPKAAQASAPASGAKS-ASAPAGTLLGHYRYKEAFRGD-----
--------------LVQIDFWRDTDRPILL-HKGAVESYRQLVQA--ARAEGVILVTLSG
FRSERYQQEVYAR-QLGK-----AGTTSTA-----------TLINAPPGYSEHHTGYAID
FGDGTVPG--------ANLRPRFEQTVAFRWLTANARKFGFEMSFPKDNPQRVSYEPW--
------------------------------------------------------------
---HWRYVGDKRSIETFYLGKGR-----------------------------
>Aquilegia_coerulea_gnl|BL_ORD_ID|26324 _003_00099.1|PACid:22049415
MENYALV------CSPNLTLFNVSGSSTTTTMKGPISIRTPL-----------FANHILF
RKSFNTTKSRFLV-KATAAL-----------PKPTLHIIDSSTSTTLRTNGHEAFARI-S
SSSGTETSSVGVRPEIS-----MPPP--SSTVGSPLFWIGVGV------GLSALFSWVAT
NLKKYAMQQAFKTMMGSMSSEKSPFSNPAFNNPAFS------PG--SPFPFPAP--PTST
TS--------------TSP--------SPVASK-PAVTVDVPAT--KVEATQATE-----
--------------VNSKTEI--------K-EEPKRYAFVDVSPE--EIVEKDPFKSSKE
LKETKATTNAQNTEEVSR-----NGAATKG----DAGAY--SEQSNSTR--RAGSVLSVE
ALEKMMEDPTVQNMVFPYLPEEMRDPTTFKWMLQN-PQYRQQLEDMLNNM-GGS-SEW-D
NKMMDSLKNFDLSSPEVKQQFDQIGLTPEEVISKIMANPEVAMAFQNPRVQAAIMDCSQN
PLSIAKYQNDKEVMDVFNKISELFPGVTGSP---------------------
>Prunus_persica_gnl|BL_ORD_ID|11413 _ppa013039m|PACid:17651878
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----MLEDPTVQKMVYPYLPEEMRNPSTFKWMLQN-PQYRQQLEDMLNNM-GGS-NEW-D
NRMMDSLKNFDLSSPEVKQQFDQIGLTPEEVISKIMANPEVAMAFQNPRVQAAIMDCSQN
PLSIAKYQNDKEVMDVFNKISELFPGVSGSP---------------------
>Vitis_vinifera_gnl|BL_ORD_ID|17248 _GSVIVT01025999001|PACid:17833873
MDSLTLV------SSPKLVL----GHSPSNPRH--ISCAHSS-----------FSLPLLF
RKP----RKFIAA-SQSGAS-----------PRTPRHVVETKLGT-------ECFASI-S
SSS-QGTSSVGVNPQFS-----PPPP--SSNIGSPLFWIGVGV------GLSALFSWVAS
NLKKYAMQQAFKTLMGQMDSQ-----NNQFNTTTFS------PG--SPFPFPMP--PPSG
PSTSHSGPTTSPSGPTTSP--------STVAAQ-SMVTVDVPAT--KVETPPATD-----
--------------VKDDIEK--------K-NEQNKYAFVDVSPE--ETLQESPFENFEE
STETSSSKDAQFSAGVSQ-----NGTPPRP----GMGV---SEDSQSTR--NANPFLSVD
ALEKMMEDPTVQKMVYPYLPEEMRNPTTFKWMLQN-PQYRQQLQDMLNNM-GGG-AEW-D
NRMMDNLKNFDLSSPEVKQQFDQIGLTPEEVISKIMANPDVALAFQNPRIQAAIMDCSQN
PLSIAKYQNDKEVMDVFNKISELFPGVSGPP---------------------
>Cucumis_sativus_gnl|BL_ORD_ID|15635 _173420.1|PACid:16966614
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------MRNPETFKWMMQN-PLYRQQLEEMLNNM-SGS-PQW-D
GRLMDSLKNFDLSSPEVKQQFDQIGLTPEEVISKIMANPEIAMAFQNPRVQAAIMDCSQN
PLSITKYQNDKEVMDVFNKISELFPGVSGAP---------------------
>Glycine_max_gnl|BL_ORD_ID|31596 _11g31810.1|PACid:16285086
MEKLNLALVSS--PKPLML-----GHVPAR-------------DVFRRKHFS-FGRVLIA
PH-----RCRFRV-SALSSS--HHNP----------KSVQEKLIV-------KHFASI-S
SSNTQETTSIGVKPQLS------PSP--SSTIGSPLFWIGVGV------GLSALFSVVAS
RLKKYAMQQAFKTMMGQMNSQ-----NNQFGNAAFS------PG--SPFPFPMP--TAAG
PTAPASSATTQSRAPSASS-----------ASQ-STITVDLPAA--KVEAAPTTN-----
--------------VKDEVEL--------K-NEPKKIAFVDVSPE--ETVRESPFESFKD
D-ESSSVKEAWVPDEVSQ-----NGAPSNL----GFGD---FPGSQSTK--KS--ALSVD
ALEKMMEDPTVQKMVYPYLPEEMRNPTTFKWMLQN-PQYRQQLEEMLNNM-GGS-TEW-D
NRMMDTLKNFDLNSPEVKQQFDQIGLSPEEVISKIMANPEVAMAFQNPRVQAAIMDCSQN
PMNITKYQNDKEVMDVFNKISELFPGV-GSP---------------------
>Glycine_max_gnl|BL_ORD_ID|48697 _18g05480.1|PACid:16308005
MEKLNLALVSS--PKPLML-----GHGLNCSSSLQIPCFCTL-----------FLPSHEY
PM-----LTFLRI-SVSMVK--------------HFFLKKEKLIV-------KHFASI-S
SSNTQEATSTGVNPQLS--------P--SSTIGSPLFWIGVGV------GLSALFSV---
---KYAMQQAFKTMMGQMNSQ-----NNQFGNAAFS------PG--SPFPFPMP--TAAG
PTAPASSATTQSRAPSASS-----------ASQ-STITVDIPAA--KVEVAPTTN-----
--------------VKDEVEL--------KMENIQGIIFINVSPE--ETVQESPFESFKD
D-ESSSVKEARVPDEVSQ-----NGAPSNQ----GFGD---FPGSQSTK--KS--VLSVD
ALEKMMEDPTVQKMVYPYLPEEMRNPTTFKWMLQN-PQYRQQLEEMLNNM-GGS-TEW-D
SRMMDTLKNFDLNSPEVKQQFDQIGLSPEEVISKIMANPEVAMAFQNPRVQAAIMDCSQN
PMNITKYQNDKEVMDVFNKISELFPGV-GSP---------------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|25224 _091029773m|PACid:23556101
MENLNLALVSS--SKPLML-----GHVPARDATDR--------DVLRRKPFS-LGRVLIA
PH-----RFRYRV-SALSSS------------HHSPKSVQDKLIV-------KHFASI-S
SSNTQETTSIGVNPQLS------PPP--SSTIGSPLFWIGVGV------GLSALFSMVAS
RLKKYAMQQAFKTMMGQMNSP-----NNDFGNAAFS------PG--SPFPFSMP--SAAG
PT-----ATAQYGAPSTSS-----------GSQ-STVTVDIPAT--KVEATRTTD-----
--------------IKDEVEV--------Q-NKPKKIAFVDVSPE--ETVQKSPFESVKD
NESSSVKEEARVPDEVSQ-----NGAPFNQ----GFGG---FPGSQSTK--KS--ALSVD
ALEKMMEDPTVQKMVYPHLPEEMRNPDTFKWMLQN-PQYRQQLEAMLSNM-GGS-TEW-D
NRMMDTLKNFDLNSPEVKQQFDQIGLSPEEVISKIMANPEVAMAFQNPRVQAAIMDCSQN
PMNITKYQNDKEVMNVFNKISELFPGM-GSP---------------------
>Mimulus_guttatus_gnl|BL_ORD_ID|5714 _mgv1a006810m|PACid:17675109
MENLGLV------SSPKIVL----GVSPNPRNSVI------SSKPLVGLPNL-LKKTGNY
GRHTTIHTSSLQV-LSLFRS-----------PKPTKTIVSEKAAK-------DRFATI--
SSSGQETSSVGVNPQLS------VPP--SSQVGSPLFWIGVGV------GLSALFSFVAG
RLKKYAMEQAFKTFTQQMNTQ-----NSPFGNAAFS------PG--SPFPFP----PATS
PA--------------LDP----FRTSTPLASQ-P-ITVDVPAS--KVEDPPSIS-----
--------------VKDEVEQ--------E-TGPKKYAFVDVSPE--ETLQKNAFENYKE
SIQTDSPKDPQSSQSVSQ-----NGTAWNQ----GAGG---SEGPTTSK---TAPLMSVE
ALEKMMEDPTVQQMVYPYLPEEMRNPTTFKWMLQN-PQYRQQLQDMLNNM-GGT-PEW-D
NRMMDSLKNFDISSPEVKQQFDQIGLTPEEVISKIMANPDVAMAFQNPRVQAAIMDCSQN
PMSIAKYQNDKEVMDVFNKISELFPGVAGS----------------------
>Carica_papaya_gnl|BL_ORD_ID|2452 _evm.model.supercontig_116.57|PACid:16406315
MENLNGVLVS---SSPKLLL----GYGCNHKIPKT------LNYSPLRLPFA-LRSSRVC
RR-----NSTISV-SALSHS---------RYSRPAVTSHTGKSGG-------DRFGSI-S
SSTDQQTSSVGVNPNLT-----VPPP--ASSVGSPLFWIGVGV------GLSAVFSWAAS
SLKKYAMQQAMKTMMSQMNTQ-----NNQFSNVPFP------PG--SPFPYPKP--PTTG
PT--------------TSP-----------ASQ-PTVTVDVAAT--KVEAAPTTD-----
--------------AKEESET--------E-TKQKKYAFVDVSPE--ETTQKSPFASFED
VPEISSSKNSQFPKEVSQ-----NGAASKQ----AVDS---SEGSQSFR-----PGLTVD
ALEKMMEDPTVQKMVYPYLPEEMRNPTTFKWMLQN-PQYRQQLQDMLNNM-SGS-GEW-N
NNMMETLKGFDLNSPEVKQQFDQIGLTPEEVISKIMANPEVAMAFQNPKIQAAIMDCSQN
PLSIAKYQNDKEVMDVFNKISELFPGVTGYP---------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|20359 _POPTR_0004s08560.1|PACid:18226590
MENPRLALLSS--SSPKLVM----GYPT-SLKNPT-TPKFSISTTRPSLPFS-LRISKTA
PH-----ASIFSI-SALANS-------------------HGKLGS-------EYFASI-S
SSSGKQTASVGVNPQPV------SPP--PSQIGSPLFWVGVGV------GLSAIFSWVAT
RVKNYAMQQAFKSLTEQMNTQ-----NNQF-NPAFS------AR--PPFPFSPP--PASH
PS--------------TSP--------SPAASQ-PAITVDIPAT--KVEAAPTTD-----
--------------VGKEKETDFLEERKIK-EETKKYAFVDISPE--ETSLNTPFSSVED
DNETSSSKDVEFAKKVFQ-----NGAAFKQ----GPGA---AEGSQSTR-----PFLSVE
ALEKMMEDPTMQKMVYPYLPEEMRNPTTFKWMLQN-PQYRQQLEDMLNNM-GGS-GKW-D
SQMMDSLKDFDLNSAEVKQQFDQIGLTPEEVISKIMANPDVAMAFQNPRVQQAIMECSQN
PINITKYQNDKEVMDVFNKISELFPGMTG-----------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|4786 _POPTR_0017s02900.1|PACid:18210818
MENPRLSLLSC--SSLKLVS----GYPT-SLKNPT-TPKFSISTTRPSLPFP-HRTSKTV
TH-----TSRISI-SALSQS--------------HGPRRTSKNGS-------EYFASI-S
SLSGQQTASVGVNPQSV------SPP--PSQIGSPLFWVGVGV------ALSAIFSWVAT
RLKNYAMQQAFKSLTEQMNAQ-----NNQF-NPAFS------AR--SPFPFSPP--PASQ
PA--------------TSP--------FQTASQ-PAVTVDIPAT--KVEAAPETD-----
--------------ARKEKETDTLEEREIK-EEPRKFAFVDVSPE--ETSLNTPFSSVED
VIDTSSSKDVQFAKEASQ-----NGATFKQ----GPSASEPSEGSQSSQ---KAGSLSVE
ALEKMMDDPTVQKMVYPYLPEEMRNPTTFKWMLQN-PQYRQQLEEMLNNM-SGS-SEW-D
SRMVDSLKNFDLSSPEVKQQFDQIGLTPEEVISKIMANPDVALAFQNPRVQQAIMECSQN
PLSIAKYQNDKEVMDVFNKISEILG---------------------------
>Linum_usitatissimum_gnl|BL_ORD_ID|32755 _10002287|PACid:23171935
MA--LISTPSS--CSPKLVI----GYPPTSLLNPT--------TPRRTLPYLHLRSCRIL
PP-----RSRFSA-SASYQG--DAAPPQAQPAARSATSRRGKSGA-------GNFASI-F
SSKGQNTSSVGVTPQPV-----ATPP--PSQVASYL-------------KVS-----VLD
IHGKYAMQQAMKTMMSQMNTQ-----NSQFGGNT--------PI--SPFQFPMPSVPETS
PSRPTSSPSWPASAPSYSKSAATEAATSPAPSQ-SRITVDVSAT----EEASSTN-----
--------------VNNEVDS--------K-EDKKKYAFVDVSPEDKETLVGTPFGSADD
GNETSSIKDAPFEVEASQ-----NGAAFKQDTSAGAAA---AEGSQSTG---SGPALSVE
ALEKMMEDPTVQQMVFPYLPEEMRNPTTFKWMLQN-PEYRQQLQDMLNNM-GGS-NGW-D
PSMLDSMKNFDLSSPEVKQQFDQIGLTPEEVISKIMANPDVAMAFQNPRVQQAIMECSQN
PMSITKYQNDKEVMDVFNKISELFPGVSGSPY--------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|5848 _488521|PACid:16039595
MENLTLVSCSA--SSPKLLI--GCNFTS-SLKNPT-GFS--------------RRTPRIV
LR-----CSKISA-SAQSQS--PSSRPD-----NTGEIVVVKQRS-------KAFASIFS
SSRDQQTTSV-ASPSVP-----VPPP-SSSTIGSPLFWIGVGV------GLSALFSLVTS
NLKKYAMQTAMKTMMNQMNTQ-----NSQFNNPGFP------SG--SPFPFPFP--PQTS
PA--------------SSP--------FQSQSQSSGATVDVTAT--KVDTPPSTKPKPT-
--PAKDIEVDKPSVVLEASKE--------K-KEEKNYAFEDISPE--ETTKESPFSNYAE
VSETSSPKETRLFEDVLQ-----NGAGPAN----GATA---SEVFQSLGGGKGGAGLSVE
ALEKMMEDPTVQKMVYPYLPEEMRNPETFKWMLKN-PQYRQQLQDMLNNM-SGS-GEW-D
KRMTDTLKNFDLNSPEVKQQFNQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSEN
PMNIMKYQNDKEVMDVFNKISQLFPGMTG-----------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MENLTLVSCSA--SSPKLLI--GCNFTS-SLKNPT-GFS--------------RRTPNIV
LR-----CSKISA-SAQSQS--PSSRPE-----NTGEIVVVKQRS-------KAFASIFS
SSRDQQTTSV-ASPSVP-----VPPP-SSSTIGSPLFWIGVGV------GLSALFSYVTS
NLKKYAMQTAMKTMMNQMNTQ-----NSQFNNSGFP------SG--SPFPFPFP--PQTS
PA--------------SSP--------FQSQSQSSGATVDVTAT--KVETPPSTKPKPT-
--PAKDIEVDKPSVVLEASKE--------K-KEEKNYAFEDISPE--ETTKESPFSNYAE
VSETNSPKETRLFEDVLQ-----NGAGPAN----GATA---SEVFQSLGGGKGGPGLSVE
ALEKMMEDPTVQKMVYPYLPEEMRNPETFKWMLKN-PQYRQQLQDMLNNM-SGS-GEW-D
KRMTDTLKNFDLNSPEVKQQFNQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSEN
PMNIMKYQNDKEVMDVFNKISQLFPGMTG-----------------------
>Thellungiella_halophila_gnl|BL_ORD_ID|25183 _Thhalv10013528m|PACid:20204858
MENLTLVSCSA--SSPKLLI--GCNFTS-SLKNPV-GFS--------------RRTPKVV
FR-----CSKISA-SAKSQS--HSSRPE-----NAGEIVVVKHRS-------RDFASIFS
SNRDQQTTSV-AYPNAA-----VPPP-SSSTIGSPLFWIGVGV------GLSALFSWVTS
SLKKYAMQTAMKTMMNQMNTQ-----NSQFNNPGFP------AGSASPFPFPFP--PQTS
PT--------------SSP--------FQSQSQSSGATVDVTAT--KVDTPPSAKPQPT-
--PAKKTEVDKPSVVLEENKA--------K-KEEKNYAFEDVSPE--ETTKESPFSNYAE
VSETSAPKEARLFEDVMQ-----NGAAPAN----GATA---SEVFQSLGAGKGGPGLSVE
ALEKMMEDPTVQKMVYPHLPEEMRNPETFKWMLKN-PHYRQQLQDMLNNM-SGS-GEW-D
KRMMDTLKNFDLNSPEVKQQFDQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSEN
PMNIMKYQNDKEVMDVFNKISQLFPGMTG-----------------------
>Capsella_rubella_gnl|BL_ORD_ID|22852 _v10000974m|PACid:20908651
MENLTLVSCSA--SSPKLLI--GCNFTS-SLKTPV-GLS--------------RRTPKIV
FR-----CSKISA-SAQSHSQPPSSLPE-------NEAVVVRHRS-------KAFASIFS
SSREKQTTSV-APPSVP-----VPPP-SSSTIGSPLFWIGVGV------GLSALFSL---
---KYAMQTAMKTMMNQMNTQ-----NSQFNNPGFP------SG--SPFPFPFP--PQPS
PA--------------SSP--------FQSQSPSSGATVDVMAS--KVDTPPSTKPQPK-
--PAKDIEVDKPSVVLEENKV--------K-KEENNYAFEDVSPE--ETTKESPFSNYAE
VSESSAPKETRLFEDVLQ-----NGAGPAN----GATA---SEVFQSLGGGKGGPGLSVE
ALEKMMEDPTVQKMVYPYLPEEMRNPETFKWMLKN-PQYRQQLQDMLNNM-SGS-GEW-D
KRMTDTLKNFDLNSPEVKQQFNQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSEN
PMNIMKYQNDKEVMDVFNKISQLFPGMTG-----------------------
>Brassica_rapa_gnl|BL_ORD_ID|10046 _008608|PACid:22693556
MENLTLVSCSASSSSPKLLI--GCNFTS-SLKPPV-GFS--------------RRSPKIL
LR-----RSKISASSAQSHS--PSD--------STGEIVVVKHKT-------KAFASIFS
SRSDKQTASV-ASPSVA-----VPPPSSSSTIGSPLFWIGVGV------GLSALFSWVTS
NAKKYAMQTAMKTMMNQMNTQ-----NSQFNNPGFPTGAGAGSG--SPFPFPFP--PQTS
PT--------------SSP--------FQSQSQSSGATVDVTAT--KVDRPPVSKPQTTP
TPPTKNIEVDKPSVVLEENKA--------K-KEEKNYAFEDVSPE--ETTKESPFSNYAE
VSEASAPKETRLFDDVLQ-----NGAAPAN----GATA---SEVFQSLGAGKGGAGLSVE
ALEKMMEDPTVQKMVYPHLPEEMRNPETFKWMLKN-PQYRQQLQDMLNNM-SGS-GEW-D
KRMTETLKNFDLNSPEVKQQFDQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSEN
PMNIMKYQNDKEVMDVFNKISQLFPGMTG-----------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|23259 _5g10800.1|PACid:21826029
MESLILASSCS--AYPRLPP--LPA-ARR-----PSQPLP--ATSLS------AGAGRRG
AR-----RPRLVV----SAA------------ARGSRNVLDGLNT-------TAFASI-S
SSTSSENTSTGTGTLPP-----MPPP--SSYIGSPVFWIGIGI------ALSAAFSMVSS
MVKKYAMEQAFKSMMTQTPPN------------TFG------TN--SPFPFSMP--PQAG
STAPSS-------YPYSGP--------RKNTSP-NGTTVDVSAT--DVAATETSE-----
--------------VADVIET--------S-KPSKKFAFVDVSPQ--ELQQKELQSSLET
VDVKGASTESEVKEDAEQNV-PTNGAAFKP----TEDS---STGPTESS--KSGPMLSID
TIEKMMEDPAVQKMVYPYLPEEMRNPDSFKWMLQN-PMYRQQLEDMLNNM-GASPDQW-D
NRMVDHLKNFDLSSPEVRQQFAQVGMTPEEVVSKIMANPEVAVAFQNPKIQTAIMDCSQN
PLNIVKYQNDKEVMDVFMKISQIFPQING-----------------------
>Oryza_sativa_gnl|BL_ORD_ID|12651 _LOC_Os04g35900.1|PACid:21895123
MESLVLASSCS--ASPRLPP--LSA-ARR--RRPSSQTLPATA----------AASGRRG
AG-----RSKLVVVAAAAAA------------ARGSGNGFEGLKT-------NGFASM-S
SSTNSENMSTGTGSLPP-----MPPP--SSYIGSPVFWIGVGV------ALSAAFSMVSS
MVKKYAMQQAFKSMMTQAPPN------------TFG------SN--SPFPFAMP--PQAA
PAAPSS-------YPYSQP--------RKDTSP-QSATVDVSAT--KVEATGTLE-----
--------------EADVAE-----------QPKKKFAFVDVSPE--ELQQKELQSSLET
VDVKSESKQSETMEDTEQKA-PTNGTAFKM----NEGS---ASGTTESS--NSGPMLSVD
TIEKMMEDPAVQKMVYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDMLNNM-GGSPDQW-D
NRMLDHLKNFDLSSPEVRQQFAQVGMTPEEVVSKIMANPEVAVAFQNPKIQTAIMDCSQN
PLNIVKYQNDKEVMDVFMKISQIFPQING-----------------------
>Panucum_virgatum_gnl|BL_ORD_ID|12878 _Pavirv00024278m|PACid:23768727
MESLVLASSCS--ASPRLPV--LSASAARLRGLPGAAPLP---ASSA------AGAARSG
AR-----RPRLLVAVAAAAA------------PRGSRNVFEGLRA-------KGFASV-S
SSTGNENVSTGTGTLPP-----MPPP--SSYFGSPVFWIGVGV------ALSVAFTTVSS
MVKRYAMQQAFKSMMTQSPSN------------SFG------SN--SPFPFAMP--PQAA
PTAPSS-------YPYSQP--------KRDTSP-QVATVDVLAT--EVEASGTPK-----
--------------EADVAET--------P-KPSKKFAFVDVSPE--ELQQKNLQSSLET
VDVKRDSTDSESKEDTEQKV-PTNGAVFKP----NEDA---ARGPTESS--NSGPMLSVE
TIEKMMEDPAVQKMVYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDMLNNMGGSSPDQW-D
NRMLDHLKNFDLSSPEVRQQFAQVGMTPEEVVSKIMANPEVAVAFQNPKIQTAIMDCSQN
PLNIVKYQNDKEVMDVFMKISQIFPQING-----------------------
>Setaria_italica_gnl|BL_ORD_ID|21201 _Si010149m|PACid:19694675
MESLVLASSCS--ASPRLPV--LSA-AARFRGLPGAAPPT---AAST------GGAARGG
AR-----RPRLLV---AAAA------------PRGSRNAFEGLRA-------KGFASV-S
SSTSNENTSTGTGTLPP-----MPPP--SSYIGSPVFWIGVGV------ALSVAFTTVSS
MVKKYAMQQAFKSMMSQSPSN------------SFG------SN--SPFPFAMP--PQAA
PTAPSSYP-----YPYSVP--------KKDTYP-QAATVDVSAT--EVEAAGTSK-----
--------------EADVAET--------P-KPSKKFAFVDVSPE--ELQQKNLQSSLET
VDVKSDSTDSESKEDTEREV-PTNGEAFKP----NEGA---ARGPTESS--NSGPMLSVE
TIEKMMEDPAVQKMVYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDMLNNM-GSSPDQW-D
NRMVDHLKNFDLSSPEVRQQFAQVGMTPEEVVSKIMANPEVAVAFQNPKIQTAIMDCSQN
PLNIVKYQNDKEVMDVFMKISQIFPQING-----------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|19148 _Sb06g017360.1|PACid:1972504
MESLVLASSCS--ASPRLPL--ISS-AARFRRLPGSVPPPTVAAAST------GGAARKG
PR-----RPRLFV--VAAAA------------PRGSGNVFEGLRA-------KGFASV-S
SSTGNENMSTGTGTLPP-----VPPP--SSYFGSPVFWIGVGV------ALSVAFTTVSS
MVKRYAMEQAFKSMMTQAPPN------------SFG------SN--SPFPFGMP--PQAS
PTAPSS-------FPYLEP--------KKDTSP-QVSTVDVSAT--EVEAAGTSK-----
--------------EVDVTET--------P-EPSKKFAFVDVSPE--ELQQKNLQSSLET
VDVKHDSTDSESKEDIEEKVLPTNGATFKP----NEDA---ARGPTEPS--NSGPMLSVE
TIEKMMEDPTVQKMVYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDMLNNM-GASPDQW-D
NRMVDHLKNFDLSSPEVRQQFAQVGMTPEEVVSKIMANPDVAVAFQNPKIQTAIMDCSQN
PLNIVKYQNDKEVMDVFMKISQIFPQING-----------------------
>Citrus_clementina_gnl|BL_ORD_ID|35771 _0.9_010946m|PACid:19286967
MENLNMALVSS--TSPKLVL----NYT--NFKHPTRGITGPRRSSSLALPFKLS------
-------TSRISA-SV-----------------RAGPYQNGQVGA-------GGFASL-T
SSSGQQTSSVGVNPNLP-----MPPP--SSNVGSPLFWVGVGV------GLSALFSFVAS
RLKQYAMQQALKGMMNQMNTQ-----NKPFGNAAFP------QG--SPFPFPNP--PASG
PTTP-----------------------YPAASQ-PRFTMDIPAT--KVEAASATD-----
--------VEGKKEVKGETEV--------K-EEPKKYAFVDVSPE--ETLQKSPFDNFED
VKETSSSKDAQPPKD-SQ-----NGAAFNY----NAGS---PLGGQSAK--KEGRFLTVD
TLEKLMEDPQVQKMVYPSLPEEMRNPASFKLMLQN-PEYRKQLQEMLDGM-CES-GEF-D
GRVLDSLKNFDLNSAEVKQQFEQIGLTPEEVITKMMANPEIALGFQSPRVQAAIMECSQN
PMNIIKYQNDKEVMSVITKIAELFPGVTGTS---------------------
>Citrus_sinensis_gnl|BL_ORD_ID|22996 _1.1g014282m|PACid:18115198
MENLNMALVSS--TSPKLVL----NYT--NFKHPTRGITGPRRSSSLALPFKLS------
-------TSRISA-SV-----------------RAGPHQNGQVGA-------GGFASL-T
SSGGQQTSSVGVNPNLP-----MPPP--SSNVGSPLFWVGVGV------GLSALFSFVAS
RLKQYAMQQALKGMMNQMNTQ-----NKPFGNAAFP------QG--SPFPFPNP--PASG
PTTP-----------------------YPAASQ-PRFTMDIPAT--KVEAATATD-----
--------VEGKKEVKGETEV--------K-EEPKKYAFVDVSPE--ETLQKSSFDNFED
VKETSSSKDAQPPKD-SQ-----NGAAFNY----NAGS---PFGGQSAK--KEGRFLTVD
TLEKLMEDPQVQKMVYPSLPEEMRNPASFKLMLQN-PEYRKQLQEMLDGM-CES-GEF-D
GRVLDSLKNFDLNSAEVKQQFEQIGLTPEEVITKMMANPEIALGFQSPRVQAAIMECSQN
PMNIIKYQNDKEVMSVITKIAELFPGVTGTS---------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|19216 _437721|PACid:15420494
MA-----------MAHSLGF--GALALHWRDGAPGAGTSSSVRFYGS------RRAPQRL
VLSPLSNRERLSVRCQ-------------------------------------------S
RSPAQDQAAGSAELQTV-----SVPPTQPAYIGSPLLWVGVGV------GLSVLFSWAAN
YVKKQAMQQALKSMMS--GPG-----QNQFGNMPI-----------PPFPFPVPPQPQQQ
PMPTFQ-------PPVSSP----------QATQ-PQASASATAVVESTEAASYSE-----
--------------TQTPTPV----------SENNKPAFTDVNVE--AEVSTVKIN--AE
ATEVKENANDVFFKDAEV---RDSGTGFTW----NTDGA--ASTSSSDG--KANSFFSVE
NLEKMLEDPTVQQMVYPYLPQEMRNPSTFKWMMQN-PQFRTQLQEMLNNM-TED-GAWKN
GQMGDVLKNFNPNNQELKQQFEQIGLSPEEVMAKMVANPEIAMAFQNPKIQAALIDCSQN
PTNITKYQNDKEVMDVFNKIAELFPIKGF-----------------------
>Cucumis_sativus_gnl|BL_ORD_ID|15634 _173410.1|PACid:16966613
M-----------------------------------------------------------
-------MLLIFIPSLFDSS--------------LFSSLTWKPVA-------ERFATVSS
STTSNDSSSVGV-PSVS-----IPPP--SSYVGSPLFWVGVGV------GLSALFTW---
---KYAMQQAFKTMMSQMNSQ-----NSPMSNPTLS------SG--SPFPTPPT--FATG
TT--------------ISP----------SVSE-PAVSIDVTAT--KVEEEPVTN-----
--------------VKSRTEN----------MEAKKFAFVDVSPE--ETDQKSPFK--ED
ATDADVSKSAQPTEELPQ-----NGAASKQ----AYNG---SDGSQFSR--KPGSVLSVE
AVEKMMEDPTVQKMIYX-------------------------------------------
------------------------------------------------------------
----------------------------------------------------
