>Drosophila_melanogaster_gnl|BL_ORD_ID|861 gi|24639561|ref|NP_726885.1| Hsc/Hsp70-interacting protein related, isoform A [Drosophila melanogaster]
M---------------------------AFTMQTGDLKKLKYFIDFALE-----------
-----------------------NPTFLNMPQLQFVKDFVEK------------------
------------------------------------------------------------
--------------FGGTVPPG--QFNGGSAGGKCPFGGVAGAKANEPANAPEDS-----
------------------------------------------------------------
---------------EDEKSLSDPESDVELDMEGVIEADSDP---AQPMGNYSKKATEEE
VEQASELRAQAASAYGQQKFDEAIALYTKAIELSPGNALFHAKRGQAFLKLKKPNACIRD
CDVALELNSDLAAGYKFRGRARRLLGDFELAAHDLRQACKLDFDEETDEWLKEVTPNAKK
IEQHRLKQERRQAERKIKERQRDQRRARKEQEKHN-------------------------
----------ASSGGSSGEFSGGNPG---------------------------------N
GNMSD--ILGAMS-DPEVSAAIQDILSNPGNITKYASN-----------PKIYNLIKKIV
-----PGGDVGAAFGQAGEKAGKPSEPKPKKDSADFVDDGLD
>Branchiostoma_floridae_gnl|BL_ORD_ID|1483 jgi|Brafl1|63921|fgenesh2_pg.scaffold_2000350
M------------------------------------ENLHYVTDISSK-----------
------------------------ELFVLDPELVITKDVCTS------------------
------------------------------------------------------------
----------------PAMPDLVEQHPKGHSTSAGTPQGKAFVFPVTPPGSPILQ-----
------------------------------------------------------------
---------------RTCQARSAWFNTFIIDAGTPMDGWAHDGLGD---GATTARKRETG
RDNVQHLPHSNGPHYGST---------------PPARDDYTGVRGRVSALPVRPGLLTAD
-ELSPTLREEVQRAYIYYGYRVNLTTWECIKG-------LFALSNETVNIWSHLLPTVYF
V--VLLTKEGSQEEGYAR------------------------------------------
-----------------------------------------------------------N
VRLAQEICAI----DPEVLAAFQDVSQHPENLAKYQSN-----------PKIANLIAKMS
TKFGGPGGGPGGPPG--GPPMGDPPADPPAGEPP--VDDGLD
>Ciona_intestinalis_gnl|BL_ORD_ID|11836 jgi|Cioin2|295862|estExt_fgenesh3_pg.C_1620021
M---------TSRCSAYCCVTVSDLYGNDTIVNVTPEMLIEKIKEMAVKQITADTEATGN
VGQYRLILINNTPRSLCDDKTAKQESLLEGDSTLLLKNRNNK------------------
------------------------------------------------------------
------------------QPMSSLVKDGVVSHEGPSLSSIARATEGLPAMSGASTSSETS
DMIGAATSSEQVEQTLRKVLLALLELSYKFMHFNDDQKS-----------KREVEFEVSD
VKHLTDMGFSEA---RAKRALVLNNMNTNLAMEWLLQHADDSSD-DEQMETSGPPSVGQ-
-----------------------------------RFRKFKPNPTHLTSLMD--------
---MGFNKEESVQALKINN-------------------------NNLNSACEWLLGDRKV
DDSHDVEDEMLNPESELY------------------------------------------
-----------------------------------------------------------K
ALVANPTIHIGLH-DRKVLEALEDMVENPWRRNSWAYE-----------SAVGNVILQIL
KLYNKYSTSAP-------------------------QTNP--
>Homo_sapiens_gnl|BL_ORD_ID|15261 gi|55770884|ref|NP_057256.2| ubiquitin-associated domain-containing protein 1 [Homo sapiens]
MFVQE----EKIFAGKVLRLHICASDGAEWLEEATEDTSVEKLKERCLKHCAHGSLEDPK
SITHHKLIHAASERVLSDARTILEENIQDQDVLLLIKKRAPS------------------
------------------------------------------------------------
-------------PLPKMADVSAEEKKKQ-DQKAPDKEAILRATANLPS--------YNM
DRAAVQTNMRDFQTELRKILVSLIEVAQKLLALNPDAVELFKKANAMLDEDEDERVDEAA
LRQLTEMGFPEN---RATKALQLNHMSVPQAMEWLIEHAEDPTI-DTPLPGQAPPEAEGA
TAAASEAAAGASATDEEARDELTEIFKKIR-----RKREFRADARAVISLME--------
---MGFDEKEVIDALRVNN-------------------------NQQNAACEWLLGDRK-
-PSPEELDKGIDPDSPLF------------------------------------------
-----------------------------------------------------------Q
AILDNPVVQLGLT-NPKTLLAFEDMLENPLNSTQWMND-----------PETGPVMLQIS
RIFQTLNRT---------------------------------
>Nematostella_vectensis_gnl|BL_ORD_ID|26546 jgi|Nemve1|246357|estExt_fgenesh1_pg.C_2130024
MRDFELQGLKSLRSVPLIRIKVTCTSGKDQSLAVSLKDTVSLVKDRVLG------GEFCK
ESSFYKLVVAKTRRNLSDENTLEKEGISEDDELILLKRRHSS------------------
------------------------------------------------------------
------------------ACDHEKEKKRI-TCKIPDISTIHKLTSTLPA-------DEDT
EVPTASSTQFNFNRELRRILVSLIDSSILLQSLDEDSQE----ASTAKPEEPSLTVDPVS
LKQLTDMGFDTA---RATKSLLANRMSPMLAMEWLLQHESDSDI-DEPSTPSTSQGRTHR
-----------------------------------KRREFTPNPQSVRNLKE--------
---MGFEEEEIMVALKVSG-------------------------NNPEAACDWLLGDRK-
-EGAMSSDEGLDPESPMY------------------------------------------
-----------------------------------------------------------K
AIMENPLVQLSLY-NPRVLGAFEDMLDSPNTSNVYIND-----------PETGPVLLQIS
CIVQGFAR----------------------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M--------------ENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRR-----------
---TPNIVLRCSKISASAQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVAS
PSVPVPPPSSSTIGSPLFWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQF
NNSGFPSGSPFPFPFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAKDI
EVDKPSVVLEASKEKKEEKNYAFEDISPEETTKESPFSNYAEVSETNSPKETRLFEDVLQ
NGAGPANGATAS---EVFQSLGGGKGGPGLSVEALEKMMEDPTV-QKMVYPYLPEEMRNP
E----------------------------------TFKWMLKNPQYRQQLQD----MLNN
MSGSGEWDKRMTDTLKNFDL------------------------NSPEVKQQF-------
------NQIGLTPEEVI-------------------------------------------
-----------------------------------------------------------S
KIMENPDVAMAFQ-NPRVQAALMECSENPMNIMKYQND-----------KEVMDVFNKIS
QLFPGMTG----------------------------------
>Nematostella_vectensis_gnl|BL_ORD_ID|11371 jgi|Nemve1|132153|e_gw.305.17.1
M--------AAEGAEMSKINVVVKTSKNKETIAVEPTATIKEFKEMISEKFGAP------
---VPQLCLIFAGRILKDHDTLASSAIKDGLTVHLVIKSENR------------------
------------------------------------------------------------
------------------VRTAASCKPCFPGNNHFTPSPPTALSPSVPLPTGTPNP----
-------------------------------------------------------LDLAG
LGGLGAMGQSGNLQ-EMTQQLQQQMMS---NPDTMRQILDNPIV-QSMMSNPE-------
-----------------------------------LMRNMILSNPQMQQLVE--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---RNPEISHILN-NPDLMRQTMEMARNPSVMQEMMRNQDRALSNLESLPGGFNALQRMY
TDIQEPMMNAA-------------------------QEQVFC
>Nematostella_vectensis_gnl|BL_ORD_ID|2973 jgi|Nemve1|45732|gw.355.81.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------DNP------------
------------------------------------------------------------
---------------EVCRSLMD-------SSELCRSIMDNPGVCRSLMNNPE-------
-----------------------------------VCRSLMDSSEVCRSLMDNPEVC---
------------------------------------------------------------
--------RSLMDSSEVC------------------------------------------
-----------------------------------------------------------R
SIMDNPEVCRSLMDNPEVCMSIMD---NPEVCRSLMDS-----------SEVCRLLMDSP
EVCRSLMD----------------------------------
>Ciona_intestinalis_gnl|BL_ORD_ID|3654 jgi|Cioin2|231500|fgenesh3_pg.C_scaffold_585000003
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KKTEVSDLNENIVNSNSGKVEAISNTTPAVHSGLSI
EIDDISLKVEKSSKKMPENSYAYTNNSEEQTLTN----------------EEKLGVKHTL
DNGVEDLGVSEELSAESFNSNPSPNSNDELSLDSGIVSLDDQEA-DK-MNPNEMNPSNNR
KRLRSSLVSDQSAKRERRSLGKKVMFEKVKIFFFPRKQSFITVPSQGGSTLG--------
------------MDLKHNGF------------------------KELTLEQHKISIARRR
RLAIKEHDRQQRIESKLRQ-----------------------------------------
-----------------------------------------------------------Y
LLVEKP---------PEV------------------------------------------
------------------------------------------
