>Branchiostoma_floridae_gnl|BL_ORD_ID|30467 jgi|Brafl1|125587|estExt_fgenesh2_pg.C_1880092
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DAEKIAQLQAFVQLCKV
SPEV-LHDPKLQFFKSWM----ESM---------GATIPPA---ATSQS-----GTTQDS
PPP-MG-----SASK-----PPPPPE-PESEESE--------------------------
-----E------------------------------------------------------
--------------------------SEESDLDIDMEGVIEGDSDPPPDMG-DDSIEV--
------TEEMM----------------------DQSND-KRAEAQAAMNEGEKEKAIELW
TEAIRLNPQSAPLFAKRASCF-----------LRM----SKPNAAIHDCDRAIELNPDSA
A-------GYKWRGKAHKL-LGH-----------WEESAKDLATAQKI----------DY
DDD-TYLLLKEVQPKALKIKEHQRKKERKREEKELRARKKRVQKAKEAQEKAKREQEERE
RQ-----GPSGMPGFGGGGFPGMGGFPGMGSFPGGAGGAAGGMPGGMP-----GGFPGGM
PGGMP------GGMPGGMPGGMPGGMPGGMPDINKIMSDPEIMAAFQDPEVLAAFQDVSQ
HPENLAKYQSNPKIANLIAKMS---------------------TKFGGPGGGPGGPPGG-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-PPMGDPPADPPAGEPP--VDDGLD-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Homo_sapiens_gnl|BL_ORD_ID|30316 gi|19923193|ref|NP_003923.2| hsc70-interacting protein [Homo sapiens]
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DPRKVNELRAFVKMCKQ
DPSV-LHTEEMRFLREWV----ESM---------GGKVPPATQKAKSEE-----NTKEEK
PDS-KK------------------VEEDLKADEP--------------------------
-----S------------------------------------------------------
--------------------------SEESDLEIDKEGVIEPDTDAPQEMG-DENAEI--
------TEEMM----------------------DQAND-KKVAAIEALNDGELQKAIDLF
TDAIKLNPRLAILYAKRASVF-----------VKL----QKPNAAIRDCDRAIEINPDSA
Q-------PYKWRGKAHRL-LGH-----------WEEAAHDLALACKL----------DY
DED-ASAMLKEVQPRAQKIAEHRRKYERKREEREIKERIERVKKAREEHERAQREEEARR
Q--------------------------------------SGAQYGSFP-----GGFPGGM
PGNFP------GGMP-GMGGGMPG--MAGMPGLNEILSDPEVLAAMQDPEVMVAFQDVAQ
NPANMSKYQSNPKVMNLISKLS---------------------AKFGGQA----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Takifugu_rubripes_gnl|BL_ORD_ID|2722 jgi|Takru4|618641|e_gw2.209.28.1
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DPRKLSELKGFVQLCET
KPEM-LHLPEMSFFREWL----LGM---------GATIPPL---SKPKE-----SCQPEP
PVL-S-------------------------------------------------------
-----E------------------------------------------------------
--------------------------SDESDIEIDNDGVIEPDTDEPQEMGASENVEV--
------TEEMM----------------------DQANN-KKMEAIDAQGEGELQKALDLF
TEAIKLNPCLAVLYAKRASVF-----------IQL----QRPNAAIRDCDRAIQINPDSA
Q-------PYKWRGKAHRL-LGH-----------WEEAAKDLATACKL----------DY
DES-ASAMLKEVQPKANKIMEHRRKYERKREEKLIRERQERIKKAREEHARAQKDEEARQ
S--------------------------------------AGA---SFPVTVELGCFPGA-
-GGFS------GGLP------------GGMPNFEAFLNDPELLMAMKDPEVMAAFSDVSK
NPANIAKYQSNPKIMAIINKLS---------------------SKFGAPPQP--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Trichoplax_adhaerens_gnl|BL_ORD_ID|2773 jgi|Triad1|37729|estExt_Genewise1Plus.C_50584
MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------TSIQHLRLLEQFIDHCKN
NPAM-LRLPELKFFADFI----VSL---------GGKIPEA---AEPEEEKVEESINDES
ESQ-VG-----SANY-----IILCPEK---------------------------------
-----E------------------------------------------------------
--------------------------SEESDLDIEAEGVIEGDDDAPQPMG-DGSKEV--
------TEEML----------------------EEASE-KRQNANIALADGNIDEGIKLY
AEAIMLNPQSAPLFAKRAGGY-----------IKA----KKPNAAIRDCDKAIQLNPDSA
Q-------AYKWRGIAYRM-LGK-----------WDKSASDLRLSVKI----------DF
SED-AQEVLNYVQPRAQRIQEHQRKIERRKAEKEIKERRERVRLAQEAKEKARKEEEERA
RKEEESGTPGGFPGAGAGGFPGAGGFPGAGGFPGAAG--AGGFPGA-------GGFPGAG
AGGFPGAGAGAGGFPGA--GGMPGAGAGQMPDINAMLNDPEIIAAFQDPEIMAAFQDVSM
NPQNVSKYQNNSKVMNIINKLA---------------------SKYGKQN----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Drosophila_melanogaster_gnl|BL_ORD_ID|866 gi|45549303|ref|NP_570074.3| Hsc/Hsp70-interacting protein [Drosophila melanogaster]
MA----------------------------------------------------------
------------------------------------------------------------
----------------------------------------FTMQTGDLKKLKYFIDFALE
NPTF-LNMPQLQFVKDFV----EKF---------GGTVPPG----------QFNGGSAGG
KCP-FGGVAGAKANE-----PANAPEDSEDEKSL--------------------------
-----S------------------------------------------------------
--------------------------DPESDVELDMEGVIEADSDPAQPMG-NYSKKA--
------TEEEV----------------------EQASE-LRAQAASAYGQQKFDEAIALY
TKAIELSPGNALFHAKRGQAF-----------LKL----KKPNACIRDCDVALELNSDLA
A-------GYKFRGRARRL-LGD-----------FELAAHDLRQACKL----------DF
DEE-TDEWLKEVTPNAKKIEQHRLKQERRQAERKIKERQRDQRRARKEQEKHNASS----
-----------------------------------------------------GGSSGEF
SGGNPGNG-----------------------------NMSDILGAMSDPEVSAAIQDILS
NPGNITKYASNPKIYNLIKKIVPGGDVG---------------AAFGQAG----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-EKAGKPSEPKPKKDSADFVDDGLD-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Branchiostoma_floridae_gnl|BL_ORD_ID|1483 jgi|Brafl1|63921|fgenesh2_pg.scaffold_2000350
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------ENLHYVTDISSK
ELFV-LD-PELVITKDVC----TS--------------P-----AMPDLVEQHPKGHSTS
AGT-PQGKAFVFPVT-----PPGSPILQRTCQAR--------------------------
-----S------------------------------------------------------
--------------------------AWFNTFIIDAGTPMDGWAHDGLGDG-ATTARK--
------RETGR----------------------DNVQH-LPHSNGPHYGST---------
------PPARDDYTGVRGRVS-----------ALP----VRPGLLTAD-ELSPTLREEVQ
R-------AYIYYG--YRVNLTT-----------WECIKGLFALS---------------
-NE-TVNIWSHLLPTVYFVV--LLTKEGSQEEGYAR----NVRLAQE-------------
------------------------------------------------------------
------------------------------------------ICAI-DPEVLAAFQDVSQ
HPENLAKYQSNPKIANLIAKMS---------------------TKFGGPGGGPGGPPGG-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-PPMGDPPADPPAGEPP--VDDGLD-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Cladonia_grayi_gnl|BL_ORD_ID|8548 jgi|Clagr2|91224|fgenesh1_kg.11_#_130_#_isotig05539
MA---DALKAEGNKAFAEKNYDEAIEKFSQAIEL----EPDNHVLYSNRSGAWASKRDFD
KALEDANKTTELKPDWAKGWGRKGAALHGTGDLVGAHDAYEEALKHDPNNAQSKSGLAAV
KRAIDAEAQADGASPGAGLGNIFNDPQMIQKLANNPKTRGLLADPQFMQKLQRLRQNPND
IGTE-MQDPRFLQVMSVL----LGIDM-SFANPSGEGSG-----------APEVNGTKEA
EEDIPMPDARPASAQPSEPAKPHEPDSKPEPEPE--------------------------
-----P-EDEEAIAAKKAKEEADAEKKLGTENYKKRQFEAAIEHYDKAWSLHQDITYLTN
KSAAQFEKGDYTGAIESCETAIEKGREVLADFKIIAKAFGRIGSAYEKIGDLPNAITNYQ
KSLTEHRTPDMLNKLRAAEKAQIKAETEAYINPEEAEK-ARELGGQKFKEADWPGAVEAY
TEMIKRAPDDPRGYSNRAAAL-----------IKL----MTFPSAVADCDIAIKKDPNFI
R-------AYLRKAQAYFA-MKE-----------YSKCTDTCAEAMEH----------DV
----GGANRREIEQQQQKALQAQYA-GRAGETEEQT------------------------
------------------------------------------------------------
--------------------------------MERIQKDPEIMGILQDPIMQSILQQAKG
DPAALQDHMKNADIRNKITKLVAAGVIRTR------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Ustilago_maydis_gnl|BL_ORD_ID|2056 jgi|Ustma1|2057|UM02057
MS--VADLKAKGNAAFAAKDYQGAIQNYNDAIAAATSAEDNVHVLYSNRSACYAGLRDWN
KALEDAEACINANPSFAKGYGRKGAALHGARRLEEAVDAYDAGLKIAPEDAGLKKGLADV
RRAVENEA-ANGPGPEASLGQMFNDPQLFAKLSANPKTAGLLSDPAFMAKLKSIQANPKE
AGMA-FQDPRMIQVMGVL----MGIDLQAFERPEGSNELPGDLENRRQDIEEQTGASASK
PKP-AAAAAASTSSADDVEMKDAKPSSSTTAQSA--------------------------
-----PVEEEEEDEEKKAKAAADAEKKLGNERYLKRDFEAAIAHYQKAWELHKDITYLNN
LGACYFEQAKYDDCIKACEQAVEEGRSMRADFKLVAKAYGRIGSAYAKQDQLDLAITNFE
KSLTEHRTPDVLAKLRETEKLQKERTRQAYIDPAKAEA-ERARGNELYKNGDFPGAVAAF
TEAIKRDPSDARGYTNRASAY-----------TKL----AALPEALKDSEEAIKVDPNFV
K-------GYIRKANVLAS-MKE-----------FTKAMEACQQAENV----------DA
AQQGGAKNAREIQALMNKCMNELYS-QRSGETEQET------------------------
------------------------------------------------------------
--------------------------------LQRAMRDPEVAQIMQDPVMQSILQQAQG
NPAALQEHMKSPIIRDKVQKLIAAGIIRTR------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Saccharomyces_cerevisae_gnl|BL_ORD_ID|5053 gi|6324601|ref|NP_014670.1| Sti1p [Saccharomyces cerevisiae S288c]
MSLTADEYKQQGNAAFTAKDYDKAIELFTKAIEVS---ETPNHVLYSNRSACYTSLKKFS
DALNDANECVKINPSWSKGYNRLGAAHLGLGDLDEAESNYKKALELDASNKAAKEGLDQV
HRT----QQARQAQPDLGLTQLFADPNLIENLKKNPKTSEMMKDPQLVAKLIGYKQNPQA
IGQDLFTDPRLMTIMATL----MGVDL-NMDDINQSNSMPK---------EPETSKSTEQ
KKD-AEPQSDSTTSKEN---SSKAPQKEESKESE--------------------------
-----PMEVDEDD----SKIEADKEKAEGNKFYKARQFDEAIEHYNKAWELHKDITYLNN
RAAAEYEKGEYETAISTLNDAVEQGREMRADYKVISKSFARIGNAYHKLGDLKKTIEYYQ
KSLTEHRTADILTKLRNAEKELKKAEAEAYVNPEKAEE-ARLEGKEYFTKSDWPNAVKAY
TEMIKRAPEDARGYSNRAAAL-----------AKL----MSFPEAIADCNKAIEKDPNFV
R-------AYIRKATAQIA-VKE-----------YASALETLDAARTK----------DA
EVN-NGSSAREIDQLYYKASQQRFQPGTSNETPEET------------------------
------------------------------------------------------------
--------------------------------YQRAMKDPEVAAIMQDPVMQSILQQAQQ
NPAALQEHMKNPEVFKKIQTLIAAGIIRTGR-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Ustilago_maydis_gnl|BL_ORD_ID|5358 jgi|Ustma1|5359|UM05359
MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----QQTPLAYAVAQWL----------------------------------QQSSTSVP
ADQKAKLQQAAKSVSEAFGVDTSSAEQQAQYGSG--------------------------
-----P------------------------------------------------------
--------------------------GLQAIFDIFLKTQAKMGAAPAPAAA-SSSSTAPA
AAAATPSDEDL----------------------AKAEQ-LKAEGNKAMSAKDYGAAIEAY
GKAIELNPNSPVYFSNRAAAF-----------SQI----GQHDSAIDDAKQASKIDPKFG
K-------AYSRLGHALFS-SGR-----------YQEAVEAYQKGVEV----------DP
SNE---------------VLKKGLAASKEQLSSSSSSNANDATASRGAADAVSAPSA---
-----------------------------------------------------GADAGAG
AGGFPNFGGGAGGM-------------------------PDLAAMMNNPMIAQMAQNLMS
NPDSLASLMNNPMLRQAAERFGSGGGMPDMSSMMNDPALRDMARNFMGGAGRGAGGNGGN
NMVDVGGSEMSVWKRLWRRLAVFGRRSFLISPCIPTVSCVCLINTTSLSRIMSNGTPSVR
VLYFASARTTIGHSSETISLPTTPFPLASLITLIANKYSSRGAEAVLRTCRWSVDNTLIE
IDELIEWTLHGREEVAAIPPMPTSPSREVAVDATKVELVSKPLLASAALNKFSGYHFNPS
SSGVDSNLLILLHGLGDNDSGFFNLGQNLQKTLPQTAILTLQAPLKVPFLEGDHWMWYPA
FDQFAELLTKPNPTVTVASVVALLDHLVGKCGWSAGSIHIFGFGQGATLALEVLISWSKS
HSQPLGSIVSIHGSFISHPTISSSSTPVLHIYRSAREIPLDSTRWSSHRKSTSALTLHRL
RGNEEDESMLKGSEWDSVMSFWSKFFRNRIKWELEGKVVPIG------------------
-------------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
ME----------------------------------------------------------
-----------------------------NLTLVSCSASSPKLLIGCNFTSSLKNPTGFS
RRTPNIVLRCSKISASAQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVAS-
-PSVPVPPPSSSTIGSPLFWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQ
FNNSGFPSGSPFPFPFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPK------
-----P------------------------------------------------------
--------------------------TPAKDIEVDKPSVVLEASKEKKEEK-NYAFED--
------------------------------ISPEETTKESPFSNYAEVSETNSPKETRLF
EDVLQ-NGAGPANGATASEVF-----------QSLGGGKGGPGLSVEALEKMME-DPTVQ
KMVYPYLPEEMRNPETFKWMLKN-----PQYRQQLQDMLNNMSGSGEW------------
-DKRMTDTLKNFDLNSPEVKQQFNQIGLTPEEV---------------------------
------------------------------------------------------------
--------------------------------ISKIMENPDVAMAFQNPRVQAALMECSE
NPMNIMKYQNDKEVMDVFNKIS---------------------QLFPGMTG---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Branchiostoma_floridae_gnl|BL_ORD_ID|29564 jgi|Brafl1|124348|estExt_fgenesh2_pg.C_1450100
MA----------------------------------------------------------
------------------------------------------------------------
--------------------ESEDSGSELIKIVVKTPKSKETVEIEATSTITEFKEAISQ
KFGQPVEQLCLIFAGKIL----KDHETLEKIGIKDGLTVHLVIRQKVGSQQGPSASGSSA
PAA----SSTPSAPAAAAAGTAPAAAPQPAPAAA--------------------------
-----P------------------------------------------------------
--------------------------FGVGGMG-GLSGLQNLGMGSANFMEMQQRMQQEL
LRNPDMLTQMM----------------------ENPFV-QSMMSN-----------PDLL
RNLIVSNPQMQQLMERNPEIT-----------HML----NNPELMRQTMELA--RNPAML
Q-------EMMRSQDRALSNLESIPGGYNALRRMYTDIQEPMMNAAQE----------QF
GNN-PWASLVGGG-----------TSNPQQGQENREPLPNPWAPQGSSTT----------
------------------------------------------------------------
-----------AATTSTTTASTTASSPAGQGLPGGLPGGIPTSGMFNSPGMQSLMQQMVD
NPQLMQNMLQAPYMQSMMQSMGQNPDMASQIIGNNPLFQGNPQL---------------Q
EQMR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------QQLPTFMQQMQ
NPEVQAAVTNPRVLQAIMQIQQGMQQLQAEAPVLLPGVPPAGG-----------------
-------------------MPASPAAPASSAASSSTDSTTTTTPTPTTASASTTSPSTAA
PPTGPTEAQQ-----QLLQQMLQTLAGG-NAMQP----PEVRFRSQLEQLETMGFVNRAA
NIQALTATNGDVNAAIDRLLQAQ--
>Ciona_intestinalis_gnl|BL_ORD_ID|5808 jgi|Cioin2|261637|gw1.04q.675.1
------------------------------------------------------------
------------------------------------------------------------
-----------------------------IKITLKTPKEKQEFTVSPKISVKDLKAEVSK
KFNATTEQLVLIFSGKIL----KDAETIDHHMIKNGHTVHLVIKSASRAQ----------
--------PTPPPPTTTQASDAPTS--QSSNSSL--------------------------
-----P------------------------------------------------------
--------------------------FNLGSMG-GLSGLGAMGLDSPNFMEMQQQMQREM
LSNPEMLQRMM----------------------DNPLV-QNMMSN-----------PEII
RNMMSNNPQMQQLMERNPEIT-----------HML----NNPQLMRQTMELA--RNPAML
Q-------EMMRNQDRALSNLESIPGGYNALRRMYTDIQEPMLNAAQE----------QF
GQN-PFAALNETSNS--------GKLNNTQNTENTNPLPNPWGSSPQATT----------
------------------------------------------------------------
-----------TSTTSSTNRPTTTPSTNTAG-----------SGLFNNPAMQNLMQQITD
NPSLMQNMMTAPYMQGMMQNMAENPELAN-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------QQMQ
RPEMQNLFTNPRAMQAMMQMQAAMQTLQQEAPGLMTGLGPTGA-----------------
---------------------------------AVPPTTTTTTSTPSST-----------
TTTNNPASSQ-----ALLNQMMQTLATGPPAAAALS--PETRYRAQLEQLSAMGFVNRDA
NIQALTATNGNVNAAIEFLLG----
>Homo_sapiens_gnl|BL_ORD_ID|2181 gi|40538799|ref|NP_064516.2| ubiquilin-4 [Homo sapiens]
MA----------------------------------------------------------
-----------------------------------------------------------E
--------------------PSGAETRPPIRVTVKTPKDKEEIVICDRASVKEFKEEISR
RFKAQQDQLVLIFAGKIL----KDGDTLNQHGIKDGLTVHLVIKTPQKAQDPAAATASSP
STP---------DPASAPSTTPASPATPAQPSTSGSASSDAGSGSRRSSGGGPSPGAGEG
SPSATA------------------------------------------------------
--------------------------SILSGFG-GILGLGSLGLGSANFMELQQQMQRQL
MSNPEMLSQIM----------------------ENPLV-QDMMSN-----------PDLM
RHMIMANPQMQQLMERNPEIS-----------HML----NNPELMRQTMELA--RNPAMM
Q-------EMMRNQDRALSNLESIPGGYNALRRMYTDIQEPMFSAARE----------QF
GNN-PFSSLAGNSDS---------SSSQPLRTENREPLPNPWSPSPPTSQAPGSGGE---
------------------------------------------------------------
-----------GTGGSGT-SQVHPTVSNPFG----INAASLGSGMFNSPEMQALLQQISE
NPQLMQNVISAPYMRSMMQTLAQNPDFAAQMMVNVPLFAGNPQL---------------Q
EQLR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------LQLPVFLQQMQ
NPESLSILTNPRAMQALLQIQQGLQTLQTEAPGLVPSLGSFGI-----------------
--------------------SRTPAPSAGSNAGSTPEAPTSSPATPA-T----------S
SPTGASSAQQ-----QLMQQMIQLLAGS-GNSQVQT--PEVRFQQQLEQLNSMGFINREA
NLQALIATGGDINAAIERLLGSQLS
>Takifugu_rubripes_gnl|BL_ORD_ID|23716 jgi|Takru4|576577|e_gw2.45.104.1
MA----------------------------------------------------------
-----------------------------------------------------------D
QGAAN--------PGNNNNNKSEASEGTIIKVTVKTPKDKEEIAIAEDASVSQFKEEISR
RFKAKQDQLVLIFAGKIL----KDGDSLSQHGIKDGLTVHLVIKTAHKAADGGSTSASSA
ASP-QAGNTSTSSPGTTPPSTAASTGTPAQPTQA--------------------------
-----P------------------------------------------------------
--------------------------NILTGFG-DLAGLAGLGMGSTNFMELQQQMQRQL
MSNPEMLSQIM----------------------ENPLV-QNMMSN-----------PDLM
RQMIMANPQMQQLMERNPEIS-----------HML----NNPELMRQTMELA--RNPAMM
Q-------EMMRNQDRALSNLESIPGGYNALRRMYTDIQEPMFSAARE----------QF
GNN-PFSALGGNSE----------SGVQPSRTENREPLPNPWGP-PNSSNPPESGGS---
------------------------------------------------------------
-----------TAGSTSTPAGTNPSVSNPLG----VNAGSLGNGIFNSPGMQSLLQQISE
NPQLMQNMLSAPYMRSMMQSLAQNPELASQVLMNNPLFAGNPQL---------------Q
EQFR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------SQLPVFLQQMQ
NPEALSVMTNPRAMQALMQIQQGLQTLQTEAPGLMPSLMTAGV-----------------
--------------------PGIP-------TAGVPSMPTENPA--S-S----------P
SNAGTNAAQQ-----QLMQQMLQMFAGG-GGGSATT--PEVRFQSQLDQLNAMGFINREA
NLQALIATGGDINAAIERLLGSQPS
>Homo_sapiens_gnl|BL_ORD_ID|31107 gi|16753207|ref|NP_038472.2| ubiquilin-2 [Homo sapiens]
MA----------------------------------------------------------
-----------------------------------------------------------E
NGESSGPPRPSRGPAAAQGSAAAPAEPKIIKVTVKTPKEKEEFAVPENSSVQQFKEAISK
RFKSQTDQLVLIFAGKIL----KDQDTLIQHGIHDGLTVHLVIKSQNRPQ-GQSTQPSNA
AGT-----------NTTSASTPRSNSTPISTNSN--------------------------
-----P------------------------------------------------------
--------------------------FGLGSLG-GLAGLSSLGLSSTNFSELQSQMQQQL
MASPEMMIQIM----------------------ENPFV-QSMLSN-----------PDLM
RQLIMANPQMQQLIQRNPEIS-----------HLL----NNPDIMRQTLEIA--RNPAMM
Q-------EMMRNQDLALSNLESIPGGYNALRRMYTDIQEPMLNAAQE----------QF
GGN-PFASVGSSSSS--------GEGTQPSRTENRDPLPNPWAPPPATQSSAT-------
------------------------------------------------------------
-----------TSTTTSTGSGSGNSSSNATG--NTVAAANYVASIFSTPGMQSLLQQITE
NPQLIQNMLSAPYMRSMMQSLSQNPDLAAQMMLNSPLFTANPQL---------------Q
EQMR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------PQLPAFLQQMQ
NPDTLSAMSNPRAMQALMQIQQGLQTLATEAPGLIPSFTP-GVGVGVLGTAIGPVGPVTP
IGPIGPIVPFTPIGPIGPIGPTGPAAPPGSTGSGGPTGPTVSSAAPSET----------T
SPTSESGPNQ-----QFIQQMVQALAGA-NAPQLPN--PEVRFQQQLEQLNAMGFLNREA
NLQALIATGGDINAAIERLLGSQPS
>Trichoplax_adhaerens_gnl|BL_ORD_ID|508 jgi|Triad1|63757|estExt_fgeneshTA2_pg.C_30521
MS----------------------------------------------------------
------------------------------------------------------------
-----------------------SQGNKILDVIVKTPKEKQTISIHENATILEFKEAVSL
QFGAPVDQLCLIFAGRIL----KDSETLSQHSIKDGLAVHLVIKSGTKAQ---TATPSET
TGT---------TTQNTPPMQQQSEGTQQQF-----------------------------
-----P------------------------------------------------------
---------------------------------------VNFGIDPSTFQNMHQYMQQQL
TSNPDMLRQMM----------------------DNPMV-QSMLNN-----------PDLM
QQLIGSNPQMQQLMERNPELS-----------HML----NNPEMMRQALEMA--RNPSML
Q-------EMMRSQDRAMSNLESIPGGFNALRRMYSDIQEPMMNAAQEMNEQMRSSYTNP
GSN-PFSSLLGGAGTQTQPQSQQPSSSPSSTPAGTSPVPNPWENRSTA------------
------------------------------------------------------------
-------------------------------------PGSTSTGMFQSPGMQSMLQQLRE
NPQLMQDTLQSPFVQNMMTQMMNNPQLMQQMLANNPLFNNDPQL---------------S
EQIR--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------ENMPNILRQMQ
NPQMQQIISNPQAVQAMLQIQQGFQQLSHAVP----------------------------
---------------------STGNTPGSTTSTTTGTNTTTSSGTGSTT----------T
TTTSSTSPQQQEQFNQLMSQMMQAMTAN-NQQQQSNLQPEVRFRTQLEQLNAMGFVDQAR
NLQVLSATGGDINAAIEQLLR----
>Nematostella_vectensis_gnl|BL_ORD_ID|11371 jgi|Nemve1|132153|e_gw.305.17.1
MA----------------------------------------------------------
------------------------------------------------------------
---------------------AEGAEMSKINVVVKTSKNKETIAVEPTATIKEFKEMISE
KFGAPVPQLCLIFAGRIL----KDHDTLASSAIKDGLTVHLVIKSENRVRTAASCKPCFP
GNN----HFTPSPPTALSPSVPLPTGTPN-------------------------------
-----P------------------------------------------------------
--------------------------LDLAGLG----GLGAMG-QSGNLQEMTQQLQQQM
MSNPDTMRQIL----------------------DNPIV-QSMMSN-----------PELM
RNMILSNPQMQQLVERNPEIS-----------HIL----NNPDLMRQTMEMA--RNPSVM
Q-------EMMRNQDRALSNLESLPGGFNALQRMYTDIQEPMMNAAQE----------QV
FC----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Nematostella_vectensis_gnl|BL_ORD_ID|2973 jgi|Nemve1|45732|gw.355.81.1
MD----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------NPEVCRSL
MDSSELCRSIM----------------------DNPGVCRSLMNN-----------PEVC
RSLMDSSEVCRSLMD-NPEVCRSLMDSSEVCRSIM----DNPEVCRSLMD-----NPEVC
M-------SIMDNPEVCRSLMDS-------------------SEVCRL------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------LMDSPEVCRSLMD---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
