>gnl|BL_ORD_ID|11646 @Cyanophora_paradoxa@_ConsensusfromContig54939-snap_masked-ConsensusfromContig54939-abinit-gene-0.3-mRNA-1:cds:11527/2598-2634:0:+
-------------------MKIDPRKVDELKAFVSLLKAQPVLLHDASLGFFRQY-----
----IESLGGRIPPTP-----AAAPGPAAPAS-----EDVAMEEPETSEPDPDV----IN
DED---------------PQPD-----------------------------APLSMGKEG
VE--------PSEADLEKC--------------------------DELKVKAAEQ-----
-IEQGDFQ----------------------------------------------------
--------G----------------------------------------AIASYTTAIEL
------------------D--PG---------------------------KDCDAGLAIN
KDSTK-------------------------------------------------------
------------------------------------------------------------
-----------------------------------CYRIRGRAFAL---------L-QWE
KAR---------------------------------------NDLG--------------
-----------------TAERIDGDP---ATYELLKKCSEKVK----------AIHEK--
--ELAAKKRR------EEA-AEAARR--------------------------ARAAAAAE
AAARE-----------AHEED-------------CC------------------------
----------------------------------------------------GGGPCGSG
PKAAGGMPGGM---PGA--------------------------GAGGNPFAGF-------
-------GGMPGGMP----GMGGMPG----------------------MGG---MAG---
MGGGMP------------------------------------------------------
----DIGSLLRD------------------PELL--------------------------
------------------AAMQN-PKVMQAMQAMMT------------------------
-----------------------NPASAAQY--------MSDPEVAAVLGKLASKMPGGM
GGMPGAGPGGNPFAGARGGGPAGGQGAPDLD
