>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------YDDIPEARRQAVPKTASSPS----------RGNPA
LWIGSGIGLLVI--------------------------------------AVGAAFAVGL
FKPEPSQSKVETSPTASTPPTGGTEAPNTPDTTLGHFSYKVAPENELQA----ITADNRI
RLRSSAARAYKQMSA---AAAADGIKLQALSGFRT-VEDQD-----YLFFRVKEERAQGA
---------QQRAKVSAPPGRSEHHTGYAMDIGDATQPNTHVNVTFEETRA----FEWLQ
KN----APRYSFELSFPKGNSQGVSYE-PWHWRYVGDKDSL-------------------
------------------------------------ETF---------------------
-------------YNARNLKS-------------------------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISAS
AQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPL
FWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPF----
--PFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAKDI----EVDKPSV
VLEASKEKKEEKNYAFEDISPEETTKESPFSNYAE-VSETNSPKETRLFEDVLQNGAGPA
NGATASEVFQSLGGGKGGPGLSVEALEKMME--DPTVQKMVYPYLPEEMRN-PETFKWML
KN-----PQYRQQLQDMLNNMSGSG---EWDKRMT---DTL-------------------
------------------------------------KNFDLNSPEVKQQFNQIGLTPEEV
ISKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDVFNKISQLFPGMTG
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISAS
AQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPL
FWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPF----
--PFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAKDI----EVDKPSV
VLEASKEKKEEKNYAFEDISPEETTKESPFSNYAE-VSETNSPKETRLFEDVLQNGAGPA
NGATASEVFQSLGGGKGGPGLSVEALEKMME--DPTVQKMVYPYLPEEMRN-PETFKWML
KN-----PQYRQQLQDMLNNMSGSG---EWDKRMT---DTL-------------------
------------------------------------KNFDLNSPEVKQQFNQIGLTPEEV
ISKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDVFNKISQLFPGMTG
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISAS
AQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPL
FWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPF----
--PFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAKDI----EVDKPSV
VLEASKEKKEEKNYAFEDISPEETTKESPFSNYAE-VSETNSPKETRLFEDVLQNGAGPA
NGATASEVFQSLGGGKGGPGLSVEALEKMME--DPTVQKMVYPYLPEEMRN-PETFKWML
KN-----PQYRQQLQDMLNNMSGSG---EWDKRMT---DTL-------------------
------------------------------------KNFDLNSPEVKQQFNQIGLTPEEV
ISKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDVFNKISQLFPGMTG
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISAS
AQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPL
FWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPF----
--PFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAKDI----EVDKPSV
VLEASKEKKEEKNYAFEDISPEETTKESPFSNYAE-VSETNSPKETRLFEDVLQNGAGPA
NGATASEVFQSLGGGKGGPGLSVEALEKMME--DPTVQKMVYPYLPEEMRN-PETFKWML
KN-----PQYRQQLQDMLNNMSGSG---EWDKRMT---DTL-------------------
------------------------------------KNFDLNSPEVKQQFNQIGLTPEEV
ISKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDVFNKISQLFPGMTG
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISAS
AQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPL
FWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPF----
--PFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAKDI----EVDKPSV
VLEASKEKKEEKNYAFEDISPEETTKESPFSNYAE-VSETNSPKETRLFEDVLQNGAGPA
NGATASEVFQSLGGGKGGPGLSVEALEKMME--DPTVQKMVYPYLPEEMRN-PETFKWML
KN-----PQYRQQLQDMLNNMSGSG---EWDKRMT---DTL-------------------
------------------------------------KNFDLNSPEVKQQFNQIGLTPEEV
ISKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDVFNKISQLFPGMTG
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISAS
AQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPL
FWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPF----
--PFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAKDI----EVDKPSV
VLEASKEKKEEKNYAFEDISPEETTKESPFSNYAE-VSETNSPKETRLFEDVLQNGAGPA
NGATASEVFQSLGGGKGGPGLSVEALEKMME--DPTVQKMVYPYLPEEMRN-PETFKWML
KN-----PQYRQQLQDMLNNMSGSG---EWDKRMT---DTL-------------------
------------------------------------KNFDLNSPEVKQQFNQIGLTPEEV
ISKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDVFNKISQLFPGMTG
>Trichodesmium_erythraeum_IMS101_gnl|BL_ORD_ID|2989 gi|113476932|ref|YP_722993.1| unnamed protein product [Trichodesmium erythraeum IMS101]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------SKPPIHAFFLGRAIAEGI------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------YEQLENGITNTLSGLG---KFDAEQR---ENL-------------------
------------------------------------RNFIDQVSEKADREAQVGNNTSN-
-----NSHPSDFDFQSKDLQAIIDDLRY---------------EVAQVREELKKYRNR
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|847 650384151 NIES39_A08510 hypothetical protein [Arthrospira platensis NIES-39]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MASIILQVDE-EIKVAFEQ
AN-----PEIQKQLSHIVELFLRGN---LYDKRLT---EVM-------------------
-------------------------------------------AEISDKAQQRGLTPE--
---------------------ILQDI--------------------------------
>Arthrospira_platensis_Paraca_gnl|BL_ORD_ID|4262 646132001 AplaP_010100021846 hypothetical protein [Arthrospira platensis Paraca]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------SISTPNPNLTMDKKTMASIILQVDE-EIKVAFEQ
AN-----PEIQKQLSHIVELFLRGN---LYDKRLT---EVM-------------------
-------------------------------------------AEISDKAQQRGLTPE--
---------------------ILQDI--------------------------------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|354 637312966 tlr0355 thiol:disulfide interchange protein [Thermosynechococcus elongatus BP-1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GAATAASGQRLRNFVIAVVAILISFALLAGLGSDN-------------------------
-----------------QPLTLAEQAKHATP--WEEAQVNGKPTLLEFYANWCSTCRSMA
KDLGELKAQYRDRVNFVMLNVDNSKWLPEIEQFNV---DGI-------------------
------------------------------------PHFVFLNRQLEPQAVAIGLQPKEV
MAKNLEALSNDLPLPYGQLTGEMSQLPS---------------PLARQRSDDPRSHGG
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|2021 641536007 MAE_20220 hypothetical protein [Microcystis aeruginosa NIES-843]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------LEFHNYPKLMRQK-IMDKNKPEEVQ--EAMISVGVGTA
IGASASAVVGGMGLAVGGTALGVGMAPVAAAGAVVGTAVYGTKKAIEEQDATAIGAAAIG
AG----------AGAGISALVGGMG-----------------------------------
--------------------------------------------------LAVGGTAVAV
TMAPVAAVGAVIGLAGYGISKLFTE---------------------------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|3612 all3613 unknown protein
MCFVWYFIFMSQKTIQCRLIASESTRQKLWKLMAESNTPLINELLQQLSKHPDFEKWRRN
GKLPSTVVSQLCQPLKTDPSFTGQPSRFYISAIHIVDYIYKSWLTIQKRLQQQLDGKLRW
IEMFNSDVELVEISGFSLEAIRTKASEILAITTPESDPKTLLTKRGKTKQSKKSSASNPD
RSLSRKLFDAYQETDDILSRSAISYLLKNGCKLNDKEENPEKFAKRRRKVEIQIQRLTDK
LTSRIPKGRDLTYSKWLETLFTATTTVPENNAEAKRWQDILLTRSSSIPFPVVFETNEDL
VWSTNEKGRLCVHFNGLSDLIFEVYCDSRQLYWFKRFLEDQQTKRKSKNQHSSGLFTLRN
GRLAWQQGEGKGEPWNIGHLALYCCVDNRLWTAEGTEQVRQE-----------KAEEITK
FITKMKDKSDLSETQLAFIKRKESTLTRINNSFDR-------------------------
---PSKPLYQGQSHILVGVSLGLEKPATIAVVDAIAGKVLTYRSLRQLLGDNYELLNRQR
RQQRSLSHERHKAQKSFSPNQFGASELGQYVDRLL-AKEIVAIAQTYKAGSIVLPKLGDI
REIVQSEIQAIAEAKCPSSSEIQQKYAKQYRVNVHQWSYGRLIQSIQSKAAQIGIVIEE-
--------------GKQPIRGSPQDKAK---------------ELALYAYSLRLARRS
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|3919 637234005 all3613 hypothetical protein [Nostoc sp. PCC 7120]
MCFVWYFIFMSQKTIQCRLIASESTRQKLWKLMAESNTPLINELLQQLSKHPDFEKWRRN
GKLPSTVVSQLCQPLKTDPSFTGQPSRFYISAIHIVDYIYKSWLTIQKRLQQQLDGKLRW
IEMFNSDVELVEISGFSLEAIRTKASEILAITTPESDPKTLLTKRGKTKQSKKSSASNPD
RSLSRKLFDAYQETDDILSRSAISYLLKNGCKLNDKEENPEKFAKRRRKVEIQIQRLTDK
LTSRIPKGRDLTYSKWLETLFTATTTVPENNAEAKRWQDILLTRSSSIPFPVVFETNEDL
VWSTNEKGRLCVHFNGLSDLIFEVYCDSRQLYWFKRFLEDQQTKRKSKNQHSSGLFTLRN
GRLAWQQGEGKGEPWNIGHLALYCCVDNRLWTAEGTEQVRQE-----------KAEEITK
FITKMKDKSDLSETQLAFIKRKESTLTRINNSFDR-------------------------
---PSKPLYQGQSHILVGVSLGLEKPATIAVVDAIAGKVLTYRSLRQLLGDNYELLNRQR
RQQRSLSHERHKAQKSFSPNQFGASELGQYVDRLL-AKEIVAIAQTYKAGSIVLPKLGDI
REIVQSEIQAIAEAKCPSSSEIQQKYAKQYRVNVHQWSYGRLIQSIQSKAAQIGIVIEE-
--------------GKQPIRGSPQDKAK---------------ELALYAYSLRLARRS
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|2334 637459732 gll2335 hypothetical protein [Gloeobacter violaceus PCC 7421]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------ATSLASTSKRWTWRGWQV
HYVEAG------------------------------------------------------
----------TDRPGVPLLLVHGFGASTDHWRKNIGPLSEHHPVWAVDLLGFGRTQKPNI
AYSGELWRDQLRDFTSEIIGRPPVVAGNSLGGYAALVLAADHPEWVKGLVLIN--GAGPF
SGAPQPNAFQKLTGEVAKGFFSQSWASWLL------------------------------
-------FQYFRQPSNIRRVLGQ-----VYHDQGAVTDELVADIYRPSCDPGAAVVFASV
FQTPQGRYVDELLGSLRRPLLLLWGESDPWMNVDRAKRFLEAYPSGQLQLIPAGHCPHDE
RPEL--------------VNAYLSEWAE---------------QIS------------
