>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145  641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]

M-----------------------------------------------------------
--------------YDDIPEARRQAVPKTASSPS----------RGNPALWIGSGI----
---GLLVI----------------------------AVGAAF------------------
------------------------------------------------------------
----------------------------------AVGLFKPEPSQ----SKVETSPTAST
PPTGGTEAPNT-------------------------------PDTTLGHFSYKVAPENEL
QAI----------------------------------------TADN--RIRLRSSAA--
------------------------------------------------------------
--------------------------------------------RAYKQMSAAAAAD---
---------------GIKLQALSGFRTVEDQDYLFF-----------------RVKEERA
QGAQQRAK----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----VSAPPGRSEH---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------HTGY
AMDIGDATQPNTHVNVTF------------------------------------------
------------------------------------------------------------
---------EETRAFEWLQKNAPRYSFELSFPKGNSQGVSYEPW----------------
---------------HWRYVGDKDS--LET------------------------------
------------FYNARNLKS---------------------------------------
------------------------------------------------------------
------------------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|3612  all3613 unknown protein

MCFVWYFIFMSQKTIQCRLIASESTRQKLWKLMAESNTPLINELLQQLSKHPDFEKWRRN
GKLPSTVVSQLCQPLKTDPSFTGQPSRFYISAIHIVDYIYKSWLTIQKRLQQQLDGKLRW
-------------IEMFNSD---------VELVEI-----SGFSLE--------AIRTKA
SEI----LAITTPESDPKTLLTKRGKTKQ-----SKKSSASNPDRSLSRKLFDAYQETDD
ILSRSAISYLLKNGCKLND-----------KEENPEKFAKRRRKV--EIQIQRLTDKLT-
-------SRIPK-----------GRDLTYSKW------LETLFTATTTVP-ENNAEAKRW
Q---------DILLTRSSSIPFPVVFETNEDLVWSTNEKGRLCVHFNGLSDL--------
-------IFEVYCDSRQLYWFKRFLEDQQTKRKSKNQ--HSSGLF--TLRNGRLA-W-QQ
GEGKGEPWNIGHLALYCCVDNRLWTAEGTEQVR--QE-------KAEEITKFITKMKDKS
DLSE---------------------------------------------------TQLAF
IKRKESTLTRINN-----------------------------------------------
------------------------------------------------------------
-----------------------------SFDRPSKPLYQGQSH----------------
------------------------------------------------------------
----------------------------ILVGVSLGLEKPATIAVVDAI--------AGK
VLTYRSLRQLLG---------------DN------YELLNRQRRQQRS----LSHERHKA
Q-KSFSPNQ-----------------------------------------FGASELGQ-Y
VDRLLAKEIVAIAQTYKAGSIVLPKLGDIREIV-QSEIQ-----------------AIAE
AKCPSSSEIQQKYAKQYRVNVHQWSYGRLIQSIQSKAAQ---------------------
------------------------------------------------------------
---------I--GIVIEEGKQPIRGSPQDKAKELALYAYS-LRLARRS------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M------------------ENLTLVSCSASSPKLLIGCNFTSS-----LKNPTGFSR---
---RTPNIVLRCSKISASAQSQSPSSRPENTGEIVV--------------------VKQR
SKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPLFWIGVGVGLSA-LFSYVTSNLK
KYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPFPFPPQTSPASSPFQSQSQSSGATVD
VTATKVETPPSTKPKPTPAKDIEVDKPSVVLEASKEKKEEKNYAFEDISPEETTKESPFS
NYAEVSETNSPKETRLFEDVLQNGAGPANGATASEVFQSLGGGKGGPGLSVEALEKMMED
PTVQKMVYPYLPEEMRNPETFKWMLKNPQYRQQLQDMLNNMSGSGEWDKRMTDTLKNFDL
NSPEVKQQFNQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSE-------------
--------NPMNIMKYQNDKEVMDVFNKISQLFPGMTG----------------------
------------------------------------------------------------
-----------------------------------
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|847  650384151 NIES39_A08510 hypothetical protein [Arthrospira platensis NIES-39]

MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SIILQVDEEIKV--AFEQA
NP----EIQKQLSH-------------------------IVELFLRGNLY----DKRLTE
V-------MAEISDKAQQRGLTPEILQDI-------------------------------
------------------------
>Arthrospira_platensis_Paraca_gnl|BL_ORD_ID|4262  646132001 AplaP_010100021846 hypothetical protein [Arthrospira platensis Paraca]

------------------------------------------------------------
-------------------------------------------SISTPNP----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------NLTMDK-----------KTMASIILQV
DEEIKVAFEQANP--EIQKQLSHIVELFLRGNLY----DKRLTEV-------MAEISDKA
QQRGLTPEILQDI-----------------------------------------------
--------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSR---------------RTPNIVLRCSK
ISASA---------------QSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQTTSV
ASPSVPVPPPSSSTIGSPLFWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNS
QFNNSGFPSGSPFPFPFPPQTSPASSPFQSQSQSSGATVDVTATKVETPPSTKPKPTPAK
DIEVDKPSVVLEASKEKKEEKNYAFEDISPEETTKESPFSNYAEVSETNSPKETRLFEDV
LQNGAGPANGATASEVFQSLG---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------GGKGGPGLSV
EALEKMMEDPTVQK-----------MVYPYLP----------------------------
-----------------EEMRNPETFKWML----KN---PQYRQQLQDM-LNNMSGSGEW
----DK------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------RMTDTLKNF-DLNSP--EVKQQ
FNQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDVFNKI
SQLFPGMT----------------------------------------------------
-----------------------------------------------G
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTP-NIVLRCSKISASAQSQSPSSRP
ENTGEIVVVK----------------------------------QRSKAFASIFSSSRDQ
QTTSVASPSVPVPPPSSSTIGSPLFWIGVGVGLSALFSYVTSN--LKKYAMQTAMKTMMN
QMNTQNSQFNNSGFPSGSPFPFPFPPQTSPASSPFQSQ--SQSSGATVDVTATKVETPPS
TKPKP--TPAKDIEVDKPSVVLEASKEKKEEKNYAFEDISPEETT--KESPFSNYAEVSE
TNSPKETRLFEDVLQNGAGPANGATASEVFQSL-----------------GGGKGGPGLS
VEALEKMMEDPTVQKMVYPYLPEEMR--NPETFKWMLKNPQYRQQLQDMLNNMSGSGEWD
KRMTDTLKNFDLN-----------SPEVKQQFNQI-------------------------
------------------------------------------------------------
------------------------------------------------------GLTPEE
VI--------------SKIMENPDVAMAFQNPRVQAALMECSENPMNIMKYQNDKEVMDV
FNKISQLFPGMTG
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|2334  637459732 gll2335 hypothetical protein [Gloeobacter violaceus PCC 7421]

M-------------------------------------------ATSLASTSKRWTWRGW
QVHYVEAGTDR------------------------------PGVPL--------------
------------------------------------------------------------
----LLVHGFGASTDHWRKN------------------------IGPLSEHHPVWAVDLL
GFGRTQK--------------------PNIAYSGELWRDQLRDFTSEIIGRPPVVAGNSL
GGYAAL-----VLAADHPE---------WVKGL--VLINGAGPFSGAPQPNAFQKLTGEV
AK-------GFFSQSWASWLLFQYFRQPSN-------IRRVLGQVYHDQGAVTDELVADI
YRPSCDPGAAVVFASVFQTPQGR-YVDELLGSLRRPLLLLWGESDP--------------
------------------------------------------------------------
---------------------WMNVDRAKRFLEAYPSGQLQLIPAGHCPHDERPELV---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------NAYLSEWAEQ-------------------------------------
------------------------------------------------------------
-----------------------------------------------------------I
S
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISASAQSQSPSSRPE
NTGEIVVVKQRSKAFASIFSSSRDQQTTSVASPSVPVPPPSSSTIGSPLFWIGVGVGLSA
LFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFPFPFPPQTSPASSPFQS
QSQSSGATVDVTATK--VETPPSTKPKPTPAKDIEVDKPSVVLEASKEKKEEKNYAFEDI
SPEETTKESPFSNYAEVSETNSPKETRLFEDVLQNGAGPANGATASEVFQSLGGGKGGPG
LSVEALEKMMEDPTVQKMVYPYLPEEMRNPETFKWMLKNPQYRQQLQDMLNNMSGSGEWD
KRMTDTLKNFDLNSPEVKQQFNQIGLTPEEVISKIMENPDVAMAFQNPRVQAALMECSEN
PMNIMKYQNDKEVMDVFNKISQLFPGMTG
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------ENLTLVSCSASSPKLLIGCNFTS-SLKNP----TGFSRRTPN
IVLRCSKISASAQSQSPSSRPENTGEIV------VVKQRSKAFASIFSSSRDQQTTS---
---------------------------------------VASPSVPVP------------
--PPSSSTIGSPLFWIGVGVGLSALFSYVT-----------SNL---KKYAMQT-AMKTM
MNQMNT-QNSQFNNSGFPS-------------------GSPFPFPF--PPQTSPASSPFQ
SQSQSSGATVD----------VTATKVETPPSTKPKPTPAKDIEVDKP-SV-------VL
EASKEKK----EEKNYAFEDIS-----PEETTKESPFSNYA--------EVSETNSPKET
RLFEDVLQNGAGPANGATASEVFQSLGGGKGGPGLSVEALEKMMEDPTVQKMVYPYLPEE
----------------------------------------------------------MR
NPETFKW---------MLKNPQYRQQLQDMLNNMSGS--------GEWDKRMTDTLK---
NFDLNSPE-----------------VKQQFNQIGLTPEEVISK-----------------
-IMENPDVAMAFQNPRVQAAL----------MECSENPMN---IMKYQNDKEVMDVF---
--------NKISQLFPGM------------------------------------------
------------------------------------------------------------
-------------------------------------------------TG
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|2021  641536007 MAE_20220 hypothetical protein [Microcystis aeruginosa NIES-843]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------LEFHNYPKLM-----------------------------------------
------------------------------------------------------------
-RQKIMDK------NKPEEVQE--------------------------------------
------------------------------------------------------AMISVG
VGTAIGASASAVVGGMGLAVGGTALGVGMAP--------------VAAAGAVVGTAVYGT
K---------------KAIEE---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------QDA--------------
------------TAIGAAAIGAGAGAGISALVGGMGLA----------------------
------------------------------------------------------------
------------VGGTAV----------------------------------------AV
TMAPVAAVGA--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------VIGLAGYGIS--------------------------------KL
FTE----------------------
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|3919  637234005 all3613 hypothetical protein [Nostoc sp. PCC 7120]

MCFVWYFIFMSQKTIQCRLIASESTRQKLWKLMAESNTPLINELLQQLSKHPDFEKWRRN
GKLPSTVVSQLCQPLKTDPSFTGQPSRFYISAIHIVDYIYKSWLTIQKRLQQQLDGKLRW
-------------IEMFNSD---------VELVEI-----SGFSLE--------AIRTKA
SEI----LAITTPESDPKTLLTKRGKTKQ-----SKKSSASNPDRSLSRKLFDAYQETDD
ILSRSAISYLLKNGCKLND-----------KEENPEKFAKRRRKV--EIQIQRLTDKLT-
-------SRIPK-----------GRDLTYSKW------LETLFTATTTVP-ENNAEAKRW
Q---------DILLTRSSSIPFPVVFETNEDLVWSTNEKGRLCVHFNGLSDL--------
-------IFEVYCDSRQLYWFKRFLEDQQTKRKSKNQ--HSSGLF--TLRNGRLA-W-QQ
GEGKGEPWNIGHLALYCCVDNRLWTAEGTEQVR--QE-------KAEEITKFITKMKDKS
DLSE---------------------------------------------------TQLAF
IKRKESTLTRINN-----------------------------------------------
------------------------------------------------------------
-----------------------------SFDRPSKPLYQGQSH----------------
------------------------------------------------------------
----------------------------ILVGVSLGLEKPATIAVVDAI--------AGK
VLTYRSLRQLLG---------------DN------YELLNRQRRQQRS----LSHERHKA
Q-KSFSPNQ-----------------------------------------FGASELGQ-Y
VDRLLAKEIVAIAQTYKAGSIVLPKLGDIREIV-QSEIQ-----------------AIAE
AKCPSSSEIQQKYAKQYRVNVHQWSYGRLIQSIQSKAAQ---------------------
------------------------------------------------------------
---------I--GIVIEEGKQPIRGSPQDKAKELALYAYS-LRLARRS------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MENLTLVSCSASSPKLLIGCNFTSSLKNPTGFSRRTPNIVLRCSKISASAQSQSPSSRPE
NTGEIVVVKQRSKAFAS----------------IFSSSRDQQTTSVASPSVPVPPPSSST
IGSPLFWIGVGVGLSALFSYVTSNLKKYAMQTAMKTMMNQMNTQNSQFNNSGFPSGSPFP
FPFP--PQTSPASSPFQSQSQSSGATVDVTATKVETPPSTK------------PKPTPAK
DIEVDKPSVVLEASKEKKEEKNYAFEDISPEETTKESPFSNYAEVSETNSPKETRLFEDV
LQNGAGPANG-----ATASEVFQSLGGGKGGPGLSVEALEKMMEDPTVQKMVYPYLPEEM
RNPETFKWMLKNPQYRQQLQDMLNNMSGSGEWDKRMTDTLKNFDLNSPEVKQQ-------
----------------------------------FNQIGLTPE--EVISKIMENPDVAMA
FQNPRVQAALMEC--------SENPMNIMKYQNDKEV----------------MDVFNKI
SQLF------------PGMT----------------------------------------
------------------------------------------------------------
-------------------------------------------G
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|354  637312966 tlr0355 thiol:disulfide interchange protein [Thermosynechococcus elongatus BP-1]

M---------------------------------GAATAASG------------------
------QRLRNFVIAVVAILIS--------------------------------------
------------------------------------------------------FALLAG
L-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------GSD
NQPLTLAEQAKHATP------WEEAQVNGKPTLLEFYANWCSTCRSMAKDLGELKAQYRD
RVNFVMLNVDNSKWLPEIEQFNVDGIPHFVFLNRQL-----------------EPQ----
-------------------AVAIGLQPKEVMAKNLE----AL---SNDLPLPYGQLTGEM
SQLPSP-------------LARQRSDDPRSH-----------------------------
GG
>Trichodesmium_erythraeum_IMS101_gnl|BL_ORD_ID|2989  gi|113476932|ref|YP_722993.1| unnamed protein product [Trichodesmium erythraeum IMS101]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---SKPPIHAFFLG----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------RAIAEGIYEQLEN
GIT-------------------------------------------NTLSGLGKFDAEQR
ENLRNFID----------------------------------------------------
------------QVSEKADREAQVGNNTSN------NSHPSD----------------FD
FQSKD-----------------------------------LQAIIDDL--RYEVAQVREE
-----------------------LKKYRNR-------------------
