>gnl|BL_ORD_ID|26324 @Aquilegia_coerulea@_003_00099.1|PACid:22049415
MENYALVCSPNLTLFNVSGSSTTTTMKGP--ISIRTPLFANHILFRKSFNTTKSRFLVKA
TAALPKPTLHIIDSSTSTTLRTNGHEAFARISSSSGTETSSVGVRPEISMPPP-SSTVGS
PLFWIGVGVGLSALFSWVATNLKKYAMQQAFKTMMGSMSSEKSPFSNPAFNNPAFSPGSP
FPFPAPPTSTTSTSPSP-------------------------------------------
------------------------------------------------------------
-------------------------------------------VASKPA-VTVDVPATKV
EATQA---------------------TEV----------------------------NSK
TEIKEEPKRYAFVDVSPEEIVEKDPF----------------------------------
---------------KSSKELKETKATTNAQNTEEVSRNGAATK----------------
------------------------------------------------------------
------------------------------------------------------------
--GDAGAYSEQSNSTRRAGSVLSVEALEK---MMED-------PTVQNMVFPYLPEEMRD
PTTFKWMLQNPQ------------------------------------------------
------------------------------------------YRQQLEDMLNNMG-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GSSEWDNKMMDSLKNFDLSSPEVKQQ----------
------------------------------------------------------------
-----------------------------------FDQIGLTPEEVISKIMANPEVAMAF
QNPRVQAAIMD-CSQNPLSIAKYQNDKEVMDVF----NKISELFPGVTGSP---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
