>gnl|BL_ORD_ID|529 @Cyanidioschyzon_merolae@_gnl|CMER|CME023C fusion protein of phosphoribosylaminoimidazole carboxylase and phosphoribosylaminoimidazole-succinocarboxamide synthase, chloroplast or mitochondrial precursor
MFGFVT------------------------------------------------------
------------------------------------------------------------
--STSSPLGLRF------------------------------------------------
-----------------------------------------------------SSFHSNT
ITCFHHVSSGKNQFGGTCRTANGAPARLGSRRLAPPRVLRT-------------------
------------------------LNCSTMDLTAPVTSSGNNSIGDHSAQGRLTPLVPIL
MGSKADKKHCDQIAAAC---HRFGLATEMHVLSAHKVPTRLLEVVG-----RLEADPR-P
KVYISVAGRS-------------NALSGLLDGSVAS----PVIACPPPSDAFGGADIF--
------------------------------------------------------------
--------SSLRMPGGIAPV----------------------------------------
-----------------------------------------------VSLDP--------
------------------------------------------------------------
--------------GNAALTAAKILGIHDPLV---------------RDRVRAFQKANRD
RLYVDDAEVATSAYLADIQAAA------RENNVLVSTDGVLSAL--VQQHAGTWRKKQGK
VRDQFYS---------DAAKHMILVTTDR-QSAFDRVLAAVPFKGAVLNLVSAWWFRRTE
HIVPNHLIAVPHPN---VTIAKRCDPFPIEFVVRGYATGSTS-------TSLWKNYERGV
REYCGIKL---PDNLHKNQKLWMN----------LVTPTTKEDIG-------DALISRQE
IIDRGLMSAVDFDACAAYALRLFEYGQQVASEHGLILVDTKYEFGRDADGQICLIDE---
------------------------------------IHTPDSSRYWLATSY--EERIASG
KEPENI-DKEILRLWYRDHCDPYKDEK---------------------------------
--------------LPEAPLELVT-ELSRRYIQ--------------LYEMITWDKFDLR
LS----------------------------------------------------------
---------TPS------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------ELQQALGPWFSGQGAKANF
TMSSP-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
