>gnl|BL_ORD_ID|3395 @Malus_domestica@_0000272048|PACid:22623366
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------MQQAFKTLMGQMNP
QDSQF-------------------------------------------------NNAGFS
PGSPFPFPSA-----------PGSGPFGSPF--------------------PPTSQH---
---------S--TVDVSATRVDA--APSAPAAPSSAPAAQATPTTP---TTPATPATDVK
SDSELNKKSNR------------FAFVDVT-------PEETEQKSPF--------ESSLK
DVSEASSSKGTQNDVEVSQNGAAFKQGAGSFTGSQS--TGKENPAISVEAL------EKM
LEDPTVQKM---------------------V----YPYLPEEM-----------------
----------------------------------RNPTTFKWMLQN--------------
----------------------PEYRKQL---EDMLNN---------MGGSS--EWDNRM
MDSLKN---------FDLSSPEV---KQQFDQI---------------------------
------------------------------------------------------------
---------------GLSPEEV--------------ISKIMANPEVAMAFQNPRVQAAIM
DIKDNRIIVLLAAGSLTLRKCSQNPLSIAKYQNDKEVMDVFNKISELFPGVSVTLLRRVL
AVDQVKSTIPKFQSRFGGMNVIDLEEESGSSILKSSSKRITELVSIEARTLEVVIHSLIA
HRSLLSVPIAAVGLVSNMQTQRLILRNVAPRTLTTFTKPTKYSLFHSHRPHSFAYCPPND
LELGLKSMQSQELCSSTSQEPFSSASLSDSLLVEKILLGLKQGTLTSLRSFRLNPFLIVE
VLSRCRENLQLGLKFVDLILLNSHNFKHSSESLSAMIHMLVRGRRVSDAQPLILRMVRKS
GISRVGVADSLVSTYSSCGSSSLIFDLFVRTYVQAKKLREGFEAFQVFRRKGFCVSINAC
NSLLGGLVKVGWFDLAWVVYGEVVSSGIQLNVYTLNIMVNALCKARKIESVKFFLSDMEE
KGVFSDIVTYNTLINAYCREGLLEEAFQLKNSMSSKGLKPELFTYNAIMNGLCKVGNYAR
AKELLDEMLQGGLNPDTTTYNTMLFESCRKGDILEAEEIFHEMSLRGVVPDIVSFSSLIG
VFSRNKNIDRALLYFRDMKRAGLVPDNVIYTILIDGYCRKGMMLEALKLRDEMLEQGCTI
DVVTFNTILNGLCREKMLSDADELFNEMLERGVIPDFYTFTTLIHGYCKHGNMTKSLNLF
DAMTNGNIKPDIVTYNTLFDGFCKLGEMDKAKELWGDMVSRRILPNHISYGILINGFCSL
GNVHEAFRLWDQMIEEGIKPTLVTCNTVIKGYCRSGDTTKADEFLGKMISKGVVPDSITY
NTLINGYVKEENLNKAFSSVQEMEKQGILSDQFTYNIILNGFCRQGRMHEAELVLRKMIE
RGVKPDRSTYTSLINGHVTQDNLKEAFRFHDEMLQRGFVPDDEF
>gnl|BL_ORD_ID|28768 @Malus_domestica@_0000173318|PACid:22648745
MEIEMEGVLENEIKRKGGRDAGLKEGDGREGKSGRGKRKPKSGIFVHVFREFDSKFQTEF
GKLKSEFREGGEEKEKLVFKRYFTKFRWPLRVSGSDGPSVWLRLHVQRGRVGWGLGRLLR
ALFLDFLVANHDVTISSSLASSLAAAPLFKPTKNXRSLIQSIPSLSMLRQSQKLQKSPEF
QSQXSRWSLHCHSPPSLNELGSEKSSKPCXEAXRKTVASTEISTCSGLEXADELCCTQTH
AYGEXXLVDFICVLKVVIIGLQLQELS------TFGDKDWAKLEVXRFASISSSSTQETS
SVGVNPQISVPPPPTN---------------------VATRLKNYAMQQAFKTLMGQMNP
QDSQF-------------------------------------------------NNAGFS
PGSPFPFPPA-----------SGSGPFGSPF--------------------PPTSQH---
---------S--TVDVSATRVDA--APSAPAAPASS-ATEATPTTPITSTAPSTPTTDVK
SDSELNKKSNRFVXFIDCCKNMSEAFVDVT-------PEETEQKSPF--------ESSFK
DVSE------------VSQNGAAFKQGADSFTSSQS--TGKAKPAMSVEAL------EKM
LEDPTVQKMESHLSVKNLTFIGRWSSFXXDL----TFYLPEEM-----------------
----------------------------------RNPTTFKWMLQN--------------
----------------------PQYRQQL---EDMLNN---------MGGSS--EWDNRM
MDSLKN---------FDLSSPEV---KQQFDQI---------------------------
------------------------------------------------------------
---------------GLSPEEV--------------ISKIMANPEVAMAFQNPRVQAAIM
DRWKTGWV-----GSWEWWECSQNPLSIAKYQNDKEVMDVFNKISELFPGVS--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GSP---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
