>gnl|BL_ORD_ID|5714 @Mimulus_guttatus@_mgv1a006810m|PACid:17675109
ME-----------------------------------------NLGLV----SSPKIVLG
VSPNPRNSVISSKPLVGLPNLLKK--------------------TGNYGRHTTIHTSSLQ
VLSLFRSPKPTKTIVSEKAAKDRFATI--SSSGQETSSVGVNPQLSVPP--SSQVGSPLF
WIGVGVGLSALFSFVAGRLKK-YAM----------EQAFKTFTQQMNTQNSPFGNAAFSP
GS--PFPFPPATSPALDPFRTSTPLASQPITV---------------DVP----------
-------------ASKVEDPPSIS------------------------------------
----------------VK----------------DEVEQ---------------------
----------------------ETGPKKYAFVDVSPE----------ETLQKNAFENYKE
SIQTDSPKDPQSSQSVSQNGTAWNQGAGGSE---GPTTSKTAPLMSVEAL----------
--EKMME-DPTVQQMVYPY-----------------------------------------
------------------------------------------------------------
---------------------------------------------LPEEMRNPTTFKWML
-----------------------QN----------------------------PQYRQQL
QDMLNNMG----------------------------------------------------
---GTPEWDNRM------MDSLKNFDISSPEVK------QQFDQI---------------
--------------GLTPEEV-ISKIMANPD-------VAMAF-----------------
------------------------------------------------------------
QNPRVQAAIMDCSQN--P------------------------------------------
-----------------MSIAKYQNDKEVMD-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------V
FNKISELFPGVAGS
