>gnl|BL_ORD_ID|13162 @Physcomitrella_patens@_Pp1s159_2V6.1|PACid:18049697
MAMESRLLQAG-DVSSPR---GCFIVSSARDGAGHRQGQHGFRVSAQR------------
------------------------------------------------FMRGVQVRQGGN
VCGRLEKKVSKSKSVVVAA------------RKSTQEQRETVVSKDDSNEYIES-SAEAQ
GSGYSYIGSPLLWIGVGV-------GLSALFSFGANA---------------VKRYAMQQ
MLKSMTGSAGGPGASPFGSPGANPFGAPGGNPFAGMPMPPPGAGFPFPMPP-TAASP---
--SPSPVSAAAA-------------APPVDVSPTNVTSSQPSVVSETPKTSTDAKKTAFT
DVNANEILEREQQAAAA----RFSDQAPSASEPTRP--YFADPELVDSKSGSNS------
-------------------------------GAGAGPSSNDPWNSAGKG----------K
QTVFTVD-------QLEKMMEDPTVQ--KMVYPY---LPEEMRNPTTFKWMMQNPQYRQQ
LQDMLNSMGGDGAWDNRMSDM-----------LNNFDLNSTEVKQQFEQIGLTPEE----
-----------------------------------VVAKIMANPE---------------
------------------------------------------------------------
-------------------------------------VAVAFQNPKVQAAIMDCSTN---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------PLNITKY-----
------------------------------------------------------------
------------------------------------------------------------
----------------QNDKEVMDVFNKISELFPGMNGSP--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------F
>gnl|BL_ORD_ID|11546 @Physcomitrella_patens@_Pp1s110_13V6.1|PACid:18048081
MAMESRVFHAGSSVASSR---ACFVVSSARAGSGHRQGQQGFQVAAQR------------
------------------------------------------------FMRGAKLRDVGI
ECGRCGKKGSRSEGIVAAA------------RKSTPEQEEYVVTKNDSNEYIES-IAESQ
GSGSSYIGSPLLWIGVGV-------GLSALFSFGANS---------------VKRYAMQQ
MLKSMSGGAGGPGAS--------PFGAPGGNPFAGMPMPPPGAGFPFPMPP-TGS-----
--VSSPVSAAAA-------------AAPVDVSP-NVTSSQPSVVSETPKSSTEPKIAAFT
DVNATEILEREQQAAAAAAASRFSDQSPSAQEPTRP--FFADSEVVDSKGGSYS------
-------------------------------GAGAGP-SNDPWDSAGKA----------K
QTVFSVE-------QLEKMMEDPTVQ--KMVYPY---LPEEMRNPTTFKWMMQNPQYRQQ
LQDMLNSMGGDGAWDNRMSDM-----------LKNFDLNSTEVKQQFEQIGLTPEE----
-----------------------------------VVAKIMANPE---------------
------------------------------------------------------------
-------------------------------------VAVAFQNPKVQAAIMDCSTN---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------PLNITKY-----
------------------------------------------------------------
------------------------------------------------------------
----------------QNDKEVMDVFNKISELFPGMAGSP--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------F
