>gnl|BL_ORD_ID|3984 @Ricinus_communis@_29005.m000255|PACid:16802149
MENLNMGLLSSFYASPKLVMGCCYPNSLKNPTVTTNKQFSRTSTSTRALPFSLRNYKIVT
RSSRFSISALAHSHSS-PRISGS---SRL-G-----AEHFASI---SSRQQTSSV-----
-----------------GVNPQPLPPPSS-SSQFGSP-----------------------
-----LFWIGVGVGLSAIFSLVATRVKNYAMQ---------------QAFKSMMNQMNTQ
NDQFN--------NPAFSPGSAFPFPTPPASVPASS-----PPFPTSSTSRPATSPSYPT
SSAST--------------SPSVASQPAVTVDVSATKVEAASVTDAKDEAEITKEPKKYA
F---VDVSPEETFPKSPFKSNEDILETSTSKD----------------------------
------------------------------------------------------------
------------------------TQFNPEVLQNG----------AASNQG--AADFTGS
QSTRKAGSGLSV--------EALEKMMEDPTVQKMVYPYLPEEM----------------
--RNPSTFKWM---------LQNPQY--------------------------RQQLEEML
NNMSGTGEWDNR-------------MMDSLKNFDLS------------------------
---------SPEVKQQFDQI-------------GLTP--EEV---ISKIMANPEIAMAFQ
NPRV----------------QQAIMDCSQNPLSIAKYQN--DKEVMDVFNKISEL-----
----FPGVRP
