>gnl|BL_ORD_ID|52243 @Zea_mays@_GRMZM2G353213_T02|PACid:20872059
MES------------LILASSCSASPRL--------PLLSSAARFRGLPVSVPPPSSASI
SGAARKGPMRPRLFVAAA-AAPRGSGN-----VFE-GLRAKGFASMSSSTGNENMSTGTG
TLPPMPPT-SSYIGSPVFWIGVGVALSVAFTTVS--------------------------
---SMLKRYAMQQ-AFKSMMTQSAP-------NSFGSNSPFPFSMPPQASPTAPSTYPYL
EPKKDTSPHVSTVDVSANEVEATGTSK---------EVD-------VTETPKPSKKFAFV
DVSPEELQQKNLQSSPETVDVKHDSTYSESKEDTEEQVPTISTNTESKEDTEEKVPTNGA
SFKLNEGAAHGPTESNNSASM--------LSVETIEKMMED---PAVQKMVYPYLPEEMR
NPNSFKWMLQNPMYRQQLQDMLNNMGATPDQWDNRMLDHLKNFDLSSPEVRQQFAQ----
------------------------------------VGMTPEEV-VSKIMANPDVAVA--
--FQNPKIQTAIMDCSQNPLNI----------------VKYQNDKEVM--------DVFM
KISQIFPQING-------------------------------------------------
--------------------------------------
