>gnl|BL_ORD_ID|12254 Arabidopsis_thaliana AT1G13900.1|PACid:19650201
M---------------------------------IVNFSFFL------------LLFVSV
FVSSADSKATISISPNALNRSGDSVVIQ----------------------WSGVDSPS--
---------------------------------DL-------------------------
------------------------------------------------------------
-----------------------------DWLG---------------------------
------------------------LYS---------------------------------
-----------------PPE-----SPNDHFIGYKFLNESSTWKDGFGSISLP-------
-LTNLRSNYTFRIFRWSESEIDPKHKDHDQNPLPGTKHLLAESEQLTFGSGVGMPEQIHL
SFTNMVNTMRVMFVAGDGEERF--------------------VRYGESKDLLGNSAAARG
MR-----YEREHMCDSPANSTIGWRDPGWIFDTVMKNLNDGVRYYYQVGSDSKGWSEIHS
YIARDVTAEETVAFMFGDMGCATPYTTFIRTQDESISTVKWILRDIEALGDKPAMISHIG
D-------ISYARGYSWVWDEFFAQ-------------VEPIASTVPYHVCIGNHEYDFS
------------------------TQPWKPDWAASIYGNDGGGECGVPYS----------
-----------------------LKFNMPGNSSESTGMKAPPTRNLYYSYDMGTVHFVYI
STETNFLKGGSQYEFIKRDLESVDRKKTPFVVVQGHRPMYTTSNEVRDTMIRQKMVEHLE
PLFVKNNVTLALWGHVHRYERFCPISNNTCGTQWQGNP--VHLVIGMAGQDWQPIWQPRP
NHPDLPIFPQPEQSMYRTGEFGYTRLVANKEKLTVSFVGNHDGEVHDTVEMLASGVVISG
SKESTKIPNLKTVP---ASATLMGKSESNALWYAKGAGLMVVGVLLGFIIGFFTRGKKSS
SGNRWIPVKNEE------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------T
>gnl|BL_ORD_ID|6440 Arabidopsis_thaliana AT4G15880.1|PACid:19644387
MGA----------------VAINRKRSDE---------SFNFINQQSTNP----LRNSPY
FQASKKRRFSFAMSEDSGKPASSNPTISR--ISRYPDAKAPLRREI--------HAPSRG
ILRYGKAKSNDYCEKDANFFVRKYDDAKRSALEAL-------------------------
------------------------------------------------------------
-----------------------------RFVNKGKD-----------------------
------------------------FVDLGDEVEKEEVVSDDSSV---QAIEVIDCD----
-----------------DDEEKKNLQPSF----------SSG------------------
-VTDVKKGENFRVEDTSMM---LDSLSLDRD-VDNDASSLEAYRKLMQSAEKRNSKLEAL
GFEIVLNEKKLS----LLRQSRPKTVEKRVEVPREPFIPLTEDEEAEVYRAFSGRNRRKV
L----------------ATHENSNIDITGEV-----------------------------
---------------------LQCLTPSAWLNDEVINVYLELLKERETREPKKYLKCHYF
NTFFYKKLVSDSGYNFKAVRRWTTQRKLGYALIDCDMIFVPIHRGVHWTLAVINNRESKL
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LYLDSLNGVDPMILNAL-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AKYMGDE------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ANEKSGKKIDANSWDMEFVEDL
PQQKNGYDCGMFMLKYI-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------DFFSRGLGLCFSQEHMPYFRL--RTAKEILRLRAD
>gnl|BL_ORD_ID|30503 Arabidopsis_thaliana AT5G23210.3|PACid:19668450
M----------------------GSHSVEFSVLVLFLVSFLLGSTSAEKL----CSDNDG
DNGCFRSRVLAAQRADRVKELPGQPPVKFRQYAGYVTVNETHGRALFYWFFEATQNPS--
--------KKP----------------------VL-------------------------
------------------------------------------------------------
-----------------------------LWLNGGPG-----------------------
------------------------CSSI-----------GFGAA---EELGPFFPQN---
-----------------SSQPKLKLNPYSWNKAANLLFLESPVGVGFSYTNTSRDIKQLG
DTVTARDSYNFLVNWFKRF---PQYKSHDFY-IAGESYAGHYVPQLSEL---IYKENKIA
SKKDFINLKGLMIGNALLDDET---------------------------DQKGMIE----
-------YAWDHAVISDALYEKVNKNCDFKQKLVTKECNDALDEYFDVYKILDMYSLYAP
KCVPTSTNSSTSHSVAG---------------NRPLPAFRSILR--------PRLISH--
---------------NEGWRRMAAG-------------YDPCAS-----------EYTEK
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------YMNRKDVQEAL----------
------------------------------------------------------------
------------------------------------------------------------
-----------------HANVTNISYPWTHCSDTVSFWSDAPASMLPTLRTLVSAGLRVW
VFSGDTDGR---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------IPVTATRYSLKKLGLKIVQDW
TPWYTKLQV---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------NLVPSYKL
>gnl|BL_ORD_ID|30502 Arabidopsis_thaliana AT5G23210.1|PACid:19668449
M----------------------GSHSVEFSVLVLFLVSFLLGSTSAEKL----CSDNDG
DNGCFRSRVLAAQRADRVKELPGQPPVKFRQYAGYVTVNETHGRALFYWFFEATQNPS--
--------KKP----------------------VL-------------------------
------------------------------------------------------------
-----------------------------LWLNGGPG-----------------------
------------------------CSSI-----------GFGAA---EELGPFFPQN---
-----------------SSQPKLKLNPYSWNKAANLLFLESPVGVGFSYTNTSRDIKQLG
DTVTARDSYNFLVNWFKRF---PQYKSHDFY-IAGESYAGHYVPQLSEL---IYKENKIA
SKKDFINLKGLMIGNALLDDET---------------------------DQKGMIE----
-------YAWDHAVISDALYEKVNKNCDFKQKLVTKECNDALDEYFDVYKILDMYSLYAP
KCVPTSTNSSTSHSVAG---------------NRPLPAFRSILR--------PRLISH--
---------------NEGWRRMAAG-------------YDPCAS-----------EYTEK
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------YMNRKDVQEAL----------
------------------------------------------------------------
------------------------------------------------------------
-----------------HANVTNISYPWTHCSDTVSFWSDAPASMLPTLRTLVSAGLRVW
VFSGDTDGR---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------IPVTATRYSLKKLGLKIVQDW
TPWYTKLQVGGWTVEYD-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---GLMFVTVRGAGHQVPTFKPREALQLIHHFLGNKKLPTFPF
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
----------------------------------YDDIPEARRQAV----PKTASSPS--
--------RGN----------------------PA-------------------------
------------------------------------------------------------
-----------------------------LWIGSGIG-----------------------
------------------------LLVI-----------AVGAA---FAVGLFKPE----
-----------------PSQSKVETSPTA----------STPPTGGTEAPNTP-------
DTTLGHFSYKVAP---ENE---LQAITADNR-IRLRSSAARAYKQMSA-----------A
AAADGIKLQALSGFRTVEDQDY-----LFFRVKEERAQGA---------QQRAKVSAPPG
RSEHHTGYAMD---IGDATQPNTHVNVTFEE-----------------------------
-----------------------------------TRAFEWLQKNA---------PRYSF
E-------LSFPKGNSQG-----VS-------------YEP---------------WHWR
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------YVGDKDSLETF----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----YNARNLK------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------S---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MEN----------------LTLVSCSASSPKLLIGCNFTSSLKNPTGFSR----RTPNIV
LRCSKISASAQSQSPSSRPENTGEIVVVKQRSKAFASIFSSSRDQQ----TTSVASPSVP
VPPPSSSTIGS----------------------PL-------------------------
------------------------------------------------------------
-----------------------------FWIGVGVG-----------------------
------------------------LSALFSYVTSNLKKYAMQTA---MKTMMNQMNTQNS
QFNNSGFPSGSPFPFPFPPQTSPASSPFQ----------SQSQSSGATVDVTATKVETPP
STKPK------------------PTPAKDIE-VDKPSVVLEASKEKKEE---KNYAFEDI
SPEETTKESPFSNYAEVSETNSPKETRLFEDVLQNGAGPANGATASEVFQSLGGGKGGPG
LSVEALEKMME-----DPTVQKMVYPYLPEE-----------------------------
--------------------------------MRNPETFKWMLKN----------PQYRQ
Q-------LQDMLNNMSGSGEWDKR-------------MTDTLKNFDLNSPEVKQQFNQI
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GLTPEEVISKIMENPDVA---
-------------------MAFQNPRVQAALMECSENPMNI-------------------
------------------------------------------------------------
------------------------------------------------------------
-----MKYQNDK------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------E---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------VMDVFNKISQLFPGMTG
>gnl|BL_ORD_ID|25150 Arabidopsis_thaliana AT3G12980.1|PACid:19663097
MAQGQNRTVLQSGQMHNSVVASASSVSSQPNMVNGISQDTLLLRQEMLNRTYAWLQQRQP
SKTDDASKAKLSEVAKRLESAMWRTATSKEDYLDFRSFDVRVESTLKQLLSQRRANPSSS
VSTMVQTPGVSHGWGQSYTATPMVDTSKFNSSNNLSDATTETGRLLPTNRMYRGTINNGR
QELSAVGQMIPTPGFDNSANADVYQSHRNEEYSGDGGKLLATGSDFGNPSQLQKQRPTGS
NDLMGYNLDHQLGGGFRSNIHQNTSGMTSIPLNAGVGMSGNNVHLANVPRSSEGVLSSTH
FSTFSQPSQQPVEQLQVSHVNRYSMSNSGTFVSGNLYGVQTSSGSIETAVDMNSMSLNSM
RRVDTSFGSQS------GLQNNPLLKPHLRHQFENGNFQSSSNSKENLAQVSHRPL----
----------------------------ERQ-FNQQAHYGQYHQQELLM---NNDAYRQS
QPASNL-VSQVKNEPRVEYYNEAFQMQAINKV--EPSKPQNQYKQNTVKDEYVGAQSAPV
----------------SSSQLKMSPSFPPQT-----------------------------
--------------------------------HQTQQVSQW--KDSSS------------
--------LSAGVQPVSGLGQWHSSSQN----------LTPISKNSNEEREHFGVRFHKQ
HEGTNNSSSVRESTNCLTVAPSGTLDVPHLPVGINVLSKQLNGDCGLSYKNQRRWLLFLL
HVRKCNAAEDNCESKYCFTAKTLLKHINCCKAPACAYQYCHQTRQLIHHYKHCGDEACPV
CVFVKNFKEKQKEKFTFLQRAEPSSAS-----------LNHGPKESFESMRTSSERDSEA
PFVVDDLQPSPKRQKVEKPSQFAYPDTQGNPATISAGVSQAHFSMGLQEKDRLPSDVCKP
VRSNVPMNADSSDSS--------RRLVPVSRELEKPVCKDTHMGRHGVKSALDGESLRLS
KQEKPKRMNEISAPKEENAEQSLGVVSASNCGKSKIKGVSLIELFTPEQVEEHIRGLRQW
VGQSKTKAEKNKAMGLSMSENSCQLCAVERLAFEPTPIYCTPCGARVKRNAMHYTVVAGE
SRHYVCIPCYNEARANTVSVDGTPVPKSRFEKKKNDEEVEESWVQCDKCQAWQHQICALF
NGRRNHGQAEYTCPNCYIQEVEQGERKPVSQNVILGAKSLPASTLSNHLEQRLFKKLKQE
RQERARLQGKSYEEVPGADSLVIRVVASVDKILEVKPRFLDIFREDNYSSEFPYKSKAIL
LFQKIEGVEVCLFGMYVQEFGTDSASPNQRRVYLSYLDSVKYFRPDVRTVSGEALRTFVY
HEILIGYLDYCKKRGFSSCYIWACPPLKGEDYILYCHPEIQKTPKTDKLREWYLAMLKKA
SKEKVVVECTNFYDHFFVQSGECRAKVTAARLPYFDGDYWPGAAEDLIDQMSQEEDGKKS
NRKLMPKKVISKRALKAVGQLDLSVNASKDLLLMHKLGEIILPMKEDFIMVHLQHCCKHC
CTLMVSGNRWVCNQCKNFQICDKCHEVEENRVEKEKHPVNQKEKHVLYPVAIDNIPTEIK
DNDDILESEFFDTRQAFLSLCQGNHYQYDTLRRAKHSSMMILYHLHNPTVPAFAMACAIC
QQELETAQGWRCEVCPDYDVCNACYSKGINHPHSIISRPSATDSVVQNTQTNQIQNAQLR
EVLLHVMTCCTAQCQYPRCRVIKGLIRHGLVCKTRGCIACKKMWSLFRLHSRNCRDPQCK
VPKCRELRAHFSRKQQQADSRRRAAVMEMVRQRAADTTASTPE
