>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
MY----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------DDIPEARRQA-------VPKTASSPSRGNP-ALWIGSGI----GL
LVI-AVGAAFAVGLFKPEP-----------------------------------------
-----------SQSKVETSPTA--------STPPTGGTEAPNTPDTTLGHFSYKVAPENE
LQAI----TADNR-IRLRSS------------------------AARAYKQMSAAA----
-----------------------------------------------------AADGIKL
QALSGFRT--VEDQDY------------LFFRVKEERAQGAQQR----------------
------------------------------------------------------------
----------------------------AKVSAPP-----GRSEHHTGYAMDIGDATQ--
---------------------------PNTHVNVTFEETRAFEWLQKNAPRYSFELSFPK
GNSQGVSYEPWHW-----------------------------------------------
----------------------------------------------RYVGDKD-SLETFY
N--------------------------------------------ARNLKS---------
------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|4564 647568950 MC7420_3835 D-alanyl-D-alanine carboxypeptidase family [Microcoleus chthonoplastes PCC 7420]
MK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
PDFPGEPVNLSESTEEDIPVAVRDTP------DTRRRSRL---QP-FLIILAVL----GG
G---AIVLGLILSSSTSQSPQTITA-----------------------------------
-----------SP--QPTTTDTSTS-----TTPEESESESENDVDNLLGHLPYEEAPLSE
LEPI----TSDGR-IQLREA------------------------AAKKFKAMRAAA----
-----------------------------------------------------QADGIVL
VAISGYRT--QQQQQH------------LFFDIKAQRGQVATQR----------------
------------------------------------------------------------
----------------------------AEVSAPP-----GYSEHHTGYAVDIGDGRT--
---------------------------PATNLNTNFENTAAFKWLEENAAYYSFELSFPK
GNPQGVSYEPWHW-----------------------------------------------
----------------------------------------------RFVGDPD-SLETFY
K--------------------------------------------AQNLDRPDLEPSPSS
SEPEDESSTREQGTGNRE
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|931 637313549 tll0932 putative carboxypeptidase [Thermosynechococcus elongatus BP-1]
MD----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------QDIPVAERLQP------IPQGKEKP---RQGGWAIASAI----VL
VGFMGVGAAWFLS-----------------------------------------------
-----------RPATSPTATGR---------------ASTVTPTENLLGHLPYEEAPLSE
LEPV----SADGQ-IKLRRA------------------------AAERFRAMVAAA----
-----------------------------------------------------QQEGVVL
IPLSGFRS--TQDQDY------------LFFEVKEHRAQRASER----------------
------------------------------------------------------------
----------------------------ALVSAPP-----GYSEHHTGYAVDIGDGAQ--
---------------------------PQTHLKETFEDTPAFRWLAKNAARFSFELSFPR
NNPQGVSYEPWHW-----------------------------------------------
----------------------------------------------RFVGDRH-SLQTFY
R--------------------------------------------ARQLRLRNAP-----
------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|786 641534767 MAE_07870 putative carboxypeptidase [Microcystis aeruginosa NIES-843]
MK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------PIDDIPEALRDS-------QYRKTTNP---NG-LIAIASGL----LA
LVGTGIIALAVLN-----------------------------------------------
-----------RPPATVKKPV---------INPSPLIKATPSPIENILGHLPYEEAPETE
LAPI----TGDGA-MRLRKP------------------------AAKAFIQMQSDA----
-----------------------------------------------------RRSGVIL
MPISAFRS--KATQDK------------LFFEVKEQRNQETRKR----------------
------------------------------------------------------------
----------------------------AEVSAPP-----GYSEHHTGYAIDIGDGRA--
---------------------------PATNLSSSFANTAAFRWLQNNAAQYSFELSFPE
NNLQGINYEPWHW-----------------------------------------------
----------------------------------------------RFVGDSH-SLETFY
K--------------------------------------------AQQLGKQK-------
------------------
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|3369 650386693 NIES39_J01590 putative carboxypeptidase [Arthrospira platensis NIES-39]
MY----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----KNLDNVPPMTSEDIPEAIRDTPKSDNSNLGKSKRSP---KF-WQWLALAI----AA
FGV-AIALNYQFGIFVVDRTSINLSASE--------------------------------
-----------TTDAMQPPPTTNPL-----PTPSVIPNQVSQLPVNLLGHLPYEEAPESE
LKNI----TADGV-IRLRRA------------------------AAYAFLEMTDAA----
-----------------------------------------------------RRSGIIL
VPISGFRG--LEDQEF------------LFFDIKAQRGQVPSQR----------------
------------------------------------------------------------
----------------------------AQVSAPP-----GYSEHHTGYAIDVADANF--
---------------------------PDTDLRETFDQTPAFKWLLDNAAFYSFELSFPK
DNPLGVSYEPWHW-----------------------------------------------
----------------------------------------------RYVGDRH-SLETFY
K--------------------------------------------ARSIDVASPSDLVNG
DN----------------
>Arthrospira_sp_PCC_8005_gnl|BL_ORD_ID|2565 648387796 APCC8_010100013340 M15B family D-Ala-D-Ala carboxypeptidase VanY [Arthrospira sp. PCC 8005]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------TSEDIPEAIRDTPNSDHSTLGKSQRSP---KF-WQWLALGI----VA
FVV-ALALNYQFGILVVDRTSVNLSASE--------------------------------
-----------TTDAMQPPPTTNPL-----PTPSVIPNQVSQLPVNLLGHLPYEEAPESE
LKNI----TADGV-IRLRRA------------------------AAYAFLDMTDAA----
-----------------------------------------------------RRSGIIL
VPISGFRG--LEDQEF------------LFFDIKAQRGQVPSQR----------------
------------------------------------------------------------
----------------------------AQVSAPP-----GYSEHHTGYAIDVGDANF--
---------------------------PDTDLRETFDQTPAFKWLVDNAAFYSFELSFPK
DNPLGVSYEPWHW-----------------------------------------------
----------------------------------------------RYVGDRH-SLETFY
K--------------------------------------------ARSIDVASPSDLVNG
DN----------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|3701 all3702 similar to D,D-carboxypeptidase
MN----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------K
AGFSGEPRDPFDELSDDIPVALRDTP------GITPKQRL---QR-LIFVTGGV----GA
FVILAIVSGFVFFITTPKK-----------------------------------------
-----------TTESQPSPAIADAT-----PMPT---ASNPADLQAILGHLAYPEAPESE
LVPI----SRDGR-IRMRRN------------------------AAQRFQEMAQAA----
-----------------------------------------------------RTAGVIL
MPISGFRS--VKEQEQ------------LFFAIGAQRNQTPAQR----------------
------------------------------------------------------------
----------------------------AALSAPP-----GHSEHHTGYAVDIGDGAA--
---------------------------PTTNLQAIFENTRAFKWLEANAARFGFEMSFPM
DNSQGVSYEPWHW-----------------------------------------------
----------------------------------------------RFVGDRD-SLETFY
K--------------------------------------------ARNLKPVKTPQ----
------------------
>Trichodesmium_erythraeum_IMS101_gnl|BL_ORD_ID|3901 gi|113477844|ref|YP_723905.1| unnamed protein product [Trichodesmium erythraeum IMS101]
MK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------ILNK
LGLLKKTPDEAKLPVDDIPEAVRDEEESAKHQSFKPQKIW---QI-WQLLAMGA----IA
LII-SISWHFQFNKTLNTSPVVQMKQKI--------------------------------
-----------STKAVETSPTQLET-----PSPSPSFNSSIKQRENILGHLPYKEASWQE
LTPV----FGNQN-IRLRSI------------------------AAEKFDLMADVA----
-----------------------------------------------------WSANIEL
VPLSGFRT--VGDQQY------------LFFEVKAERGQETSKR----------------
------------------------------------------------------------
----------------------------AEVSAPP-----GYSEHHTGYAIDIGDARM--
---------------------------PETHLEVSFENTKAFQWLQENAENYGFELSFPK
DNPQGISYEPWHW-----------------------------------------------
----------------------------------------------RFVGDSH-SLKTFE
E--------------------------------------------ARSLKE---------
------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|2419 637618109 syc2418_c putative carboxypeptidase [Synechococcus elongatus PCC 6301]
MG----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------FQYDDDVPVAIRSE-------VPTAKART---NRLLPWVVGGA----VA
AIAIGAWAIVQRS-----------------------------------------------
------------------SPTPEGV-----ETPA---ESTAATPNSLLGHRPYADAAPES
LTPL----ASNAA-IRLRSP------------------------AAKAFDELQAAA----
-----------------------------------------------------AREGVRL
VPLSGFRS--KKDQEA------------LFFDVKAERNQSVTER----------------
------------------------------------------------------------
----------------------------ASVSAPP-----GYSEHHTGYAIDIGAADQ--
---------------------------PATHLETTFEQTAAFRWLQANAKRFSFELSFPR
NNLQQVSYEPWHW-----------------------------------------------
----------------------------------------------RFVGDLE-SLRLFY
G--------------------------------------------DRSGTPAQ-------
------------------
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|2376 637459774 glr2377 similar to D,D-carboxypeptidase [Gloeobacter violaceus PCC 7421]
MT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------DFDDIPVIQRAAATAPIPVPTTKRPLP---KPPVLAAVAGM----VV
AVGLGLFLL---------------------------------------------------
-----------LPKPGEESPKAAQA-----SAPASGAKSASAPAGTLLGHYRYKEAFRGD
LVQIDFWRDTDRP-ILLHKG------------------------AVESYRQLVQAA----
-----------------------------------------------------RAEGVIL
VTLSGFRS--ERYQQE------------VYAR-QLGKAGTTSTA----------------
------------------------------------------------------------
----------------------------TLINAPP-----GYSEHHTGYAIDFGDGTV--
---------------------------PGANLRPRFEQTVAFRWLTANARKFGFEMSFPK
DNPQRVSYEPWHW-----------------------------------------------
----------------------------------------------RYVGDKR-SIETFY
L--------------------------------------------GKGR-----------
------------------
>Aquilegia_coerulea_gnl|BL_ORD_ID|26324 _003_00099.1|PACid:22049415
MEN---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------YALVCSPN--------
--LTL-----FNVSGSSTTTTMKGPISIRTP---------------LFANHILFRKSFNT
TKSRFLV-KATAALP---------------------------KPTLHIIDSSTSTTLRTN
GHEAFARISSS-SGTETSSVGVRPE-ISMPPP------SSTVGSP-LFWIGVGV----GL
SALFSWVATNLK------KYAMQQAFKTMMGSMSSE------------KSPFSNPAFNNP
AFS----PG--SPFPFPAPPT---------STT---------------------STSPS-
------PVASKPA-VTVDVP------------------------ATKV-----EAT----
-----------------------Q-------ATE-------------------VNSKTE-
-------IK-EEPKRY------------AFVDVSPE--EIVEKD----------------
---PFKSSK----ELKETKA-----------------TT-----------NAQNT-----
EEV-----SRNGAATKG----DAGA--YSEQSNS-------TRRAGSVLSVEALEKMMED
PTVQNM---------------------VFPYLPEEMRDPTTFKWMLQN-PQYRQQLEDML
NNM-GGS-SEWDN-KMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPEVAMAFQNPRVQAAIMD--------------CSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVT---GSP
------------------
>Prunus_persica_gnl|BL_ORD_ID|11413 _ppa013039m|PACid:17651878
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------MLED
PTVQKM---------------------VYPYLPEEMRNPSTFKWMLQN-PQYRQQLEDML
NNM-GGS-NEWDN-RMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPEVAMAFQNPRVQAAIMD--------------CSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVS---GSP
------------------
>Vitis_vinifera_gnl|BL_ORD_ID|17248 _GSVIVT01025999001|PACid:17833873
MDS---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------LTLVSSPK--------
--LVL---------GHSPSNP----RHISCAHS-------------SFSLPLLFRK----
-PRKFIAASQSGASP---------------------------RTP-------RHVVETKL
GTECFASISSS--SQGTSSVGVNPQ-FSPPPP------SSNIGSP-LFWIGVGV----GL
SALFSWVASNLK------KYAMQQAFKTLMGQMDSQ-----------------NNQFNTT
TFS----PG--SPFPFPMPPP---------SGP-------STSHSGPTTSPSGPTTSPS-
------TVAAQSM-VTVDVP------------------------ATKV-----ETP----
-----------------------P-------ATD-------------------VKDDIE-
-------KK-NEQNKY------------AFVDVSPE--ETLQES----------------
---PFENFE----ESTETSS-----------------SK-----------DAQFS-----
AGV-----SQNGTPPRP----GMGV---SEDSQS-------TRNANPFLSVDALEKMMED
PTVQKM---------------------VYPYLPEEMRNPTTFKWMLQN-PQYRQQLQDML
NNM-GGG-AEWDN-RMMDNLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPDVALAFQNPRIQAAIMD--------------CSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVS---GPP
------------------
>Cucumis_sativus_gnl|BL_ORD_ID|15635 _173420.1|PACid:16966614
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MRNPETFKWMMQN-PLYRQQLEEML
NNM-SGS-PQWDG-RLMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPEIAMAFQNPRVQAAIMD--------------CSQNPLSITKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVS---GAP
------------------
>Eucalyptus_grandis_gnl|BL_ORD_ID|2229 _A02100.1|PACid:23563950
MPH---------------------------------------------------------
------------------------------------------------------------
--------------HFRSADQRRREEKAKASTRFGSKNHVTNHKTSALGSPDGSISSSSS
ARRQL------PDRDMSPFAA-------------------------MAANLQVSPH----
-LYALPSSSHSSRAGSGGGGGRGSVPPPRNKQLLSRTLLCQRRPDEAARLRRYRTAPQAA
ESECFASISSSRSSKETTSVGVPPQ-PPVPPP------PSSFGSP-LFWIGVGV----GV
SALFSWVANYLK------KYAMQQAFKAMMGQMNSQ-----------------NNQFAGS
PFS----SA--SPSPFPMGSA---------PRP---------------------TPSP--
------MATSQPS--TVDIS------------------------ATKVEAVKAETA----
-----------------------P-------VAD-------------------VKDEIK-
-------KE-EELKRY------------AFVDISPE--ETKEKS----------------
---PFESFK----DVTETTS-----------------SE-----------ATQFV-----
GNA-----PQNGSASKS----VDSS---SEASES-------TGKGNPVLSVDALEKMMED
PTVQKM---------------------VFPHLPEEMRNPETFKWMLQN-PQYRQQLEEML
NNM-GGS-SEWDG-RMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPEVAMAFQNPRVQQAIMD--------------CSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVT---G-P
------------------
>Glycine_max_gnl|BL_ORD_ID|31596 _11g31810.1|PACid:16285086
MEK---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NLALVSSPKP-------
--LML---------GHVPAR-----DVFRRKHF-------------SFGRVLIAPH----
-RCRFRV-SALSSSH---------------------------HNP--------KSVQEKL
IVKHFASISSS-NTQETTSIGVKPQ--LSPSP------SSTIGSP-LFWIGVGV----GL
SALFSVVASRLK------KYAMQQAFKTMMGQMNSQ-----------------NNQFGNA
AFS----PG--SPFPFPMPTA---------AGP-------TAPASSATTQSRAPSASS--
--------ASQST-ITVDLP------------------------AAKV-----EAA----
-----------------------P-------TTN-------------------VKDEVE-
-------LK-NEPKKI------------AFVDVSPE--ETVRES----------------
---PFESFK----D-DESSS-----------------VK-----------EAWVP-----
DEV-----SQNGAPSNL----GFGD---FPGSQS-------TKKS--ALSVDALEKMMED
PTVQKM---------------------VYPYLPEEMRNPTTFKWMLQN-PQYRQQLEEML
NNM-GGS-TEWDN-RMMDTLKNFDLNSPEVKQQF------DQIGLSPEEVIS---KI---
--MANPEVAMAFQNPRVQAAIMD--------------CSQNPMNITKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGV----GSP
------------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|25224 _091029773m|PACid:23556101
MEN---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NLALVSSSKP-------
--LML---------GHVPARDATDRDVLRRKPF-------------SLGRVLIAPH----
-RFRYRV-SALSSSH---------------------------HSP--------KSVQDKL
IVKHFASISSS-NTQETTSIGVNPQ--LSPPP------SSTIGSP-LFWIGVGV----GL
SALFSMVASRLK------KYAMQQAFKTMMGQMNSP-----------------NNDFGNA
AFS----PG--SPFPFSMPSA---------AGP------------TATAQYGAPSTSS--
--------GSQST-VTVDIP------------------------ATKV-----EAT----
-----------------------R-------TTD-------------------IKDEVE-
-------VQ-NKPKKI------------AFVDVSPE--ETVQKS----------------
---PFESVK----DNESSSV-----------------KE-----------EARVP-----
DEV-----SQNGAPFNQ----GFGG---FPGSQS-------TKKS--ALSVDALEKMMED
PTVQKM---------------------VYPHLPEEMRNPDTFKWMLQN-PQYRQQLEAML
SNM-GGS-TEWDN-RMMDTLKNFDLNSPEVKQQF------DQIGLSPEEVIS---KI---
--MANPEVAMAFQNPRVQAAIMD--------------CSQNPMNITKYQNDKE-VMNVFN
K--------------------------------------------ISELFPGM----GSP
------------------
>Glycine_max_gnl|BL_ORD_ID|48697 _18g05480.1|PACid:16308005
MEK---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NLALVSSPKP-------
--LML---------GHGLNCS----SSLQIPCFCTLFLPSHEYPMLT-------------
-FLRISV-SMVKHFF---------------------------------------LKKEKL
IVKHFASISSS-NTQEATSTGVNPQ----LSP------SSTIGSP-LFWIGVGV----GL
SALFSV------------KYAMQQAFKTMMGQMNSQ-----------------NNQFGNA
AFS----PG--SPFPFPMPTA---------AGP-------TAPASSATTQSRAPSASS--
--------ASQST-ITVDIP------------------------AAKV-----EVA----
-----------------------P-------TTN-------------------VKDEVE-
-------LKMENIQGI------------IFINVSPE--ETVQES----------------
---PFESFK----D-DESSS-----------------VK-----------EARVP-----
DEV-----SQNGAPSNQ----GFGD---FPGSQS-------TKKS--VLSVDALEKMMED
PTVQKM---------------------VYPYLPEEMRNPTTFKWMLQN-PQYRQQLEEML
NNM-GGS-TEWDS-RMMDTLKNFDLNSPEVKQQF------DQIGLSPEEVIS---KI---
--MANPEVAMAFQNPRVQAAIMD--------------CSQNPMNITKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGV----GSP
------------------
>Manihot_esculenta_gnl|BL_ORD_ID|27495 _4.1_006941m|PACid:17987472
MEN---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NMALLSSPSSSSSSYSS
PKLVL---------GYSTYLK----NPTATRQFSR----TRALPF-TLRNYRTVPH----
-SSRISI-SAIAHSR---------------------------SST----GPRRVSHDRRL
GADYLLSISSS-AGQQTSSVGVNPQPLPSPSP------SSQFGSP-LFWIGVGV----GL
SALFSWVATNLK------KYAMQQALKTMMNQMTTQ-----------------NNQFTNP
AVS----PG--SPFPFPIPPA---------SGPASSPAYQTPSTSGAAISPSSPTSSGSF
DSNSSPRVTSQSA-ITVDVP------------------------ATKV-----EAT----
-----------------------P-------VSD-------------------AKDESE-
-------IK-KEPKKY------------AFVDVSPE--ETFTKS----------------
---PFKGDE----D---ISG-----------------AG-----------SSQFA-----
KEV-----SQNGAASNQ----GSTT---STASDG-------SKSTRPRLSVEALEKMMED
PTVQKM---------------------VYPYLPEEMRNPSTFKWMLQN-PQYRQQLEDML
NNM-SGS-GEWDN-RMMESLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPDVALAFQNPRVQQAIMD--------------CSQNPLSISKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVS---GS-
------------------
>Ricinus_communis_gnl|BL_ORD_ID|3984 _29005.m000255|PACid:16802149
MEN---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NMGLLSS------FYAS
PKLVM---------GCCYPNSLKNPTVTTNKQFSRTSTSTRALPF-SLRNYKIVTR----
-SSRFSI-SALAHSH---------------------------SSP-------RISGSSRL
GAEHFASISSR---QQTSSVGVNPQ--PLPPP----SSSSQFGSP-LFWIGVGV----GL
SAIFSLVATRVK------NYAMQQAFKSMMNQMNTQ-----------------NDQFNNP
AFS----PG--SAFPFPTPPA---------SVPASSPPFPTSSTSRPATSPSYPTSSAS-
---TSPSVASQPA-VTVDVS------------------------ATKV-----EAA----
-----------------------S-------VTD-------------------AKDEAE-
-------IT-KEPKKY------------AFVDVSPE--ETFPKS----------------
---PFKSNE----DILETST-----------------SK-----------DTQFN-----
PEV-----LQNGAASNQ----GAAD---FTGSQS-------TRKAGSGLSVEALEKMMED
PTVQKM---------------------VYPYLPEEMRNPSTFKWMLQN-PQYRQQLEEML
NNM-SGT-GEWDN-RMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPEIAMAFQNPRVQQAIMD--------------CSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVR-----P
------------------
>Carica_papaya_gnl|BL_ORD_ID|2452 _evm.model.supercontig_116.57|PACid:16406315
MEN---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NGVLVSS---------S
PKLLL---------GY-GCNH----KIPKTLNYS-----PLRLPF-ALRSSRVCRR----
-NSTISV-SALSHSR---------------------------YSR-----PAVTSHTGKS
GGDRFGSISSS-TDQQTSSVGVNPN-LTVPPP------ASSVGSP-LFWIGVGV----GL
SAVFSWAASSLK------KYAMQQAMKTMMSQMNTQ-----------------NNQFSNV
PFP----PG--SPFPYPKPPT---------TGP---------------------TTSP--
--------ASQPT-VTVDVA------------------------ATKV-----EAA----
-----------------------P-------TTD-------------------AKEESE-
-------TE-TKQKKY------------AFVDVSPE--ETTQKS----------------
---PFASFE----DVPEISS-----------------SK-----------NSQFP-----
KEV-----SQNGAASKQ----AVDS---SEGSQS-------FR---PGLTVDALEKMMED
PTVQKM---------------------VYPYLPEEMRNPTTFKWMLQN-PQYRQQLQDML
NNM-SGS-GEWNN-NMMETLKGFDLNSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPEVAMAFQNPKIQAAIMD--------------CSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVT---GYP
------------------
>Mimulus_guttatus_gnl|BL_ORD_ID|5714 _mgv1a006810m|PACid:17675109
MEN---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------LGLVSS----------
PKIVL---------GVSPNPR----------NSVISSKPLVGLPN-LLKKTGNYGRHTTI
HTSSLQV-LSLFRSP----------------------------------KPTKTIVSEKA
AKDRFATISSS--GQETSSVGVNPQ--LSVPP------SSQVGSP-LFWIGVGV----GL
SALFSFVAGRLK------KYAMEQAFKTFTQQMNTQ-----------------NSPFGNA
AFS----PG--SPFPF--PPA---------TSP---------------------ALDPF-
--RTSTPLASQP--ITVDVP------------------------ASKV-----EDP----
-----------------------P-------SIS-------------------VKDEVE-
-------QE-TGPKKY------------AFVDVSPE--ETLQKN----------------
---AFENYK----ESIQTDS-----------------PK-----------DPQSS-----
QSV-----SQNGTAWNQ----GAGG---SEGPTT--------SKTAPLMSVEALEKMMED
PTVQQM---------------------VYPYLPEEMRNPTTFKWMLQN-PQYRQQLQDML
NNM-GGT-PEWDN-RMMDSLKNFDISSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPDVAMAFQNPRVQAAIMD--------------CSQNPMSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVA---GS-
------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|20359 _POPTR_0004s08560.1|PACid:18226590
MEN---------------------------------------------------------
-----------------------------------------P------------------
-------------------------------------------RLALLSS--------SS
PKLVM---------GY-PTSL----KNPTTPKFSI-STTRPSLPF-SLRISKTAPH----
-ASIFSI-SALANSH------------------------------------------GKL
GSEYFASISSS-SGKQTASVGVNPQ--PVSPP------PSQIGSP-LFWVGVGV----GL
SAIFSWVATRVK------NYAMQQAFKSLTEQMNTQ-----------------NNQF-NP
AFS----AR--PPFPFSPPPA---------SHP---------------------STSPS-
------PAASQPA-ITVDIP------------------------ATKV-----EAA----
-----------------------P-------TTD-------------------VGKEKET
DFLEERKIK-EETKKY------------AFVDISPE--ETSLNT----------------
---PFSSVE----DDNETSS-----------------SK-----------DVEFA-----
KKV-----FQNGAAFKQ----GPGA---AEGSQS-------TR---PFLSVEALEKMMED
PTMQKM---------------------VYPYLPEEMRNPTTFKWMLQN-PQYRQQLEDML
NNM-GGS-GKWDS-QMMDSLKDFDLNSAEVKQQF------DQIGLTPEEVIS---KI---
--MANPDVAMAFQNPRVQQAIME--------------CSQNPINITKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGMT---G--
------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|4786 _POPTR_0017s02900.1|PACid:18210818
MEN---------------------------------------------------------
-----------------------------------------P------------------
-------------------------------------------RLSLLSC--------SS
LKLVS---------GY-PTSL----KNPTTPKFSI-STTRPSLPF-PHRTSKTVTH----
-TSRISI-SALSQSH---------------------------GPR----------RTSKN
GSEYFASISSL-SGQQTASVGVNPQ--SVSPP------PSQIGSP-LFWVGVGV----AL
SAIFSWVATRLK------NYAMQQAFKSLTEQMNAQ-----------------NNQF-NP
AFS----AR--SPFPFSPPPA---------SQP---------------------ATSPF-
------QTASQPA-VTVDIP------------------------ATKV-----EAA----
-----------------------P-------ETD-------------------ARKEKET
DTLEEREIK-EEPRKF------------AFVDVSPE--ETSLNT----------------
---PFSSVE----DVIDTSS-----------------SK-----------DVQFA-----
KEA-----SQNGATFKQ----GPSASEPSEGSQS-------SQKA-GSLSVEALEKMMDD
PTVQKM---------------------VYPYLPEEMRNPTTFKWMLQN-PQYRQQLEEML
NNM-SGS-SEWDS-RMVDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPDVALAFQNPRVQQAIME--------------CSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISEIL-------G--
------------------
>Malus_domestica_gnl|BL_ORD_ID|28768 _0000173318|PACid:22648745
MEIEMEGVLENEIKRKGGRDAGLKEGDGREGKSGRGKRKPKSGIFVHVFREFDSKFQTEF
GKLKSEFREGGEEKEKLVFKRYFTKFRWPLRVSGSDGPSVWLRLHVQRGRVGWGLGRLLR
ALFLDFLVANHDVTISSSLASSLAAAPLFKPTKNXRSLIQSIPSLSMLRQSQK---LQKS
PEFQS---------QXSRWSL----HCHSPPSLNELGSEKSSKPC-XEAXRKTVAS----
-TEISTC-SGLEXADELCCTQTHAYGEXXLVDFICVLKVVIIGLQLQELSTFGDKDWAKL
EVXRFASISSS-STQETSSVGVNPQ-ISVPPP------PTN-------------------
------VATRLK------NYAMQQAFKTLMGQMNPQ-----------------DSQFNNA
GFS----PG--SPFPFPPASG---------SGP---------------------FGSPF-
------PPTSQHS--TVDVS------------------------ATRV-----DAAPSAP
AAPASSATEATPTTPITSTAPSTP-------TTD-------------------VKSDSE-
-------LN-KKSNRFVXFIDCCKNMSEAFVDVTPE--ETEQKS----------------
---PFES------------S-----------------FK-----------DV--------
SEV-----SQNGAAFKQ----GADS---FTSSQS-------TGKAKPAMSVEALEKMLED
PTVQKMESHLSVKNLTFIGRWSSFXXDLTFYLPEEMRNPTTFKWMLQN-PQYRQQLEDML
NNM-GGS-SEWDN-RMMDSLKNFDLSSPEVKQQF------DQIGLSPEEVIS---KI---
--MANPEVAMAFQNPRVQAAIMDRWKTGWVGSWEWWECSQNPLSIAKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVS---GSP
------------------
>Linum_usitatissimum_gnl|BL_ORD_ID|32755 _10002287|PACid:23171935
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------ALISTPSS-----CS
PKLVI---------GYPPTSL----LNPTTP--------RRTLPYLHLRSCRILPP----
-RSRFSA-SASYQGD-------------------------AAPPQAQPAARSATSRRGKS
GAGNFASIFSS-KGQNTSSVGVTPQ-PVATPP------PSQVASY---------------
--LKVSVLDIHG------KYAMQQAMKTMMSQMNTQ-----------------NSQFGGN
T------PI--SPFQFPMP-----------SVPETSPSRPTSSPSWPASAPSYSKSAAT-
-EAATSPAPSQSR-ITVDVS------------------------AT-------EEA----
-----------------------S-------STN-------------------VNNEVD-
-------SK-EDKKKY------------AFVDVSPEDKETLVGT----------------
---PFGSAD----DGNETSS-----------------IK-----------DAPFE-----
VEA-----SQNGAAFKQDTSAGAAA---AEGSQS--------TGSGPALSVEALEKMMED
PTVQQM---------------------VFPYLPEEMRNPTTFKWMLQN-PEYRQQLQDML
NNM-GGS-NGWDP-SMLDSMKNFDLSSPEVKQQF------DQIGLTPEEVIS---KI---
--MANPDVAMAFQNPRVQQAIME--------------CSQNPMSITKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGVS---GSP
Y-----------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|5848 _488521|PACid:16039595
MEN---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------TLVSCSA------SS
PKLLI---------GCNFTSS----L-------------KNPTGF-SRRTPRIVLR----
-CSKISA-SAQSQSP------------------------------SSRPDNTGEIVVVKQ
RSKAFASIFSSSRDQQTTSV-ASPS-VPVPPP-----SSSTIGSP-LFWIGVGV----GL
SALFSLVTSNLK------KYAMQTAMKTMMNQMNTQ-----------------NSQFNNP
GFP----SG--SPFPFPFPPQ---------TSP---------------------ASSPF-
------QSQSQSSGATVDVT------------------------ATKV-----DTP----
-----------------------P-------STKPKPT---PAKDIEVDKPSVVLEASK-
-------EK-KEEKNY------------AFEDISPE--ETTKES----------------
---PFSNYA----EVSETSS-----------------PK-----------ETRLF-----
EDV-----LQNGAGPAN----GATA---SEVFQSL-----GGGKGGAGLSVEALEKMMED
PTVQKM---------------------VYPYLPEEMRNPETFKWMLKN-PQYRQQLQDML
NNM-SGS-GEWDK-RMTDTLKNFDLNSPEVKQQF------NQIGLTPEEVIS---KI---
--MENPDVAMAFQNPRVQAALME--------------CSENPMNIMKYQNDKE-VMDVFN
K--------------------------------------------ISQLFPGMT---G--
------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
MEN---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------TLVSCSA------SS
PKLLI---------GCNFTSS----L-------------KNPTGF-SRRTPNIVLR----
-CSKISA-SAQSQSP------------------------------SSRPENTGEIVVVKQ
RSKAFASIFSSSRDQQTTSV-ASPS-VPVPPP-----SSSTIGSP-LFWIGVGV----GL
SALFSYVTSNLK------KYAMQTAMKTMMNQMNTQ-----------------NSQFNNS
GFP----SG--SPFPFPFPPQ---------TSP---------------------ASSPF-
------QSQSQSSGATVDVT------------------------ATKV-----ETP----
-----------------------P-------STKPKPT---PAKDIEVDKPSVVLEASK-
-------EK-KEEKNY------------AFEDISPE--ETTKES----------------
---PFSNYA----EVSETNS-----------------PK-----------ETRLF-----
EDV-----LQNGAGPAN----GATA---SEVFQSL-----GGGKGGPGLSVEALEKMMED
PTVQKM---------------------VYPYLPEEMRNPETFKWMLKN-PQYRQQLQDML
NNM-SGS-GEWDK-RMTDTLKNFDLNSPEVKQQF------NQIGLTPEEVIS---KI---
--MENPDVAMAFQNPRVQAALME--------------CSENPMNIMKYQNDKE-VMDVFN
K--------------------------------------------ISQLFPGMT---G--
------------------
>Thellungiella_halophila_gnl|BL_ORD_ID|25183 _Thhalv10013528m|PACid:20204858
MEN---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------TLVSCSA------SS
PKLLI---------GCNFTSS----L-------------KNPVGF-SRRTPKVVFR----
-CSKISA-SAKSQSH------------------------------SSRPENAGEIVVVKH
RSRDFASIFSSNRDQQTTSV-AYPN-AAVPPP-----SSSTIGSP-LFWIGVGV----GL
SALFSWVTSSLK------KYAMQTAMKTMMNQMNTQ-----------------NSQFNNP
GFP----AGSASPFPFPFPPQ---------TSP---------------------TSSPF-
------QSQSQSSGATVDVT------------------------ATKV-----DTP----
-----------------------P-------SAKPQPT---PAKKTEVDKPSVVLEENK-
-------AK-KEEKNY------------AFEDVSPE--ETTKES----------------
---PFSNYA----EVSETSA-----------------PK-----------EARLF-----
EDV-----MQNGAAPAN----GATA---SEVFQSL-----GAGKGGPGLSVEALEKMMED
PTVQKM---------------------VYPHLPEEMRNPETFKWMLKN-PHYRQQLQDML
NNM-SGS-GEWDK-RMMDTLKNFDLNSPEVKQQF------DQIGLTPEEVIS---KI---
--MENPDVAMAFQNPRVQAALME--------------CSENPMNIMKYQNDKE-VMDVFN
K--------------------------------------------ISQLFPGMT---G--
------------------
>Capsella_rubella_gnl|BL_ORD_ID|22852 _v10000974m|PACid:20908651
MEN---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------TLVSCSA------SS
PKLLI---------GCNFTSS----L-------------KTPVGL-SRRTPKIVFR----
-CSKISA-SAQSHSQ----------------------------PPSSLPEN--EAVVVRH
RSKAFASIFSSSREKQTTSV-APPS-VPVPPP-----SSSTIGSP-LFWIGVGV----GL
SALFSL------------KYAMQTAMKTMMNQMNTQ-----------------NSQFNNP
GFP----SG--SPFPFPFPPQ---------PSP---------------------ASSPF-
------QSQSPSSGATVDVM------------------------ASKV-----DTP----
-----------------------P-------STKPQPK---PAKDIEVDKPSVVLEENK-
-------VK-KEENNY------------AFEDVSPE--ETTKES----------------
---PFSNYA----EVSESSA-----------------PK-----------ETRLF-----
EDV-----LQNGAGPAN----GATA---SEVFQSL-----GGGKGGPGLSVEALEKMMED
PTVQKM---------------------VYPYLPEEMRNPETFKWMLKN-PQYRQQLQDML
NNM-SGS-GEWDK-RMTDTLKNFDLNSPEVKQQF------NQIGLTPEEVIS---KI---
--MENPDVAMAFQNPRVQAALME--------------CSENPMNIMKYQNDKE-VMDVFN
K--------------------------------------------ISQLFPGMT---G--
------------------
>Brassica_rapa_gnl|BL_ORD_ID|10046 _008608|PACid:22693556
MEN---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------TLVSCSASS----SS
PKLLI---------GCNFTSS----L-------------KPPVGF-SRRSPKILLR----
-RSKISASSAQSHSP---------------------------------SDSTGEIVVVKH
KTKAFASIFSSRSDKQTASV-ASPS-VAVPPP----SSSSTIGSP-LFWIGVGV----GL
SALFSWVTSNAK------KYAMQTAMKTMMNQMNTQ-----------------NSQFNNP
GFPTGAGAGSGSPFPFPFPPQ---------TSP---------------------TSSPF-
------QSQSQSSGATVDVT------------------------ATKV-----DRP----
-----------------------P-------VSKPQTTPTPPTKNIEVDKPSVVLEENK-
-------AK-KEEKNY------------AFEDVSPE--ETTKES----------------
---PFSNYA----EVSEASA-----------------PK-----------ETRLF-----
DDV-----LQNGAAPAN----GATA---SEVFQSL-----GAGKGGAGLSVEALEKMMED
PTVQKM---------------------VYPHLPEEMRNPETFKWMLKN-PQYRQQLQDML
NNM-SGS-GEWDK-RMTETLKNFDLNSPEVKQQF------DQIGLTPEEVIS---KI---
--MENPDVAMAFQNPRVQAALME--------------CSENPMNIMKYQNDKE-VMDVFN
K--------------------------------------------ISQLFPGMT---G--
------------------
>Citrus_clementina_gnl|BL_ORD_ID|35771 _0.9_010946m|PACid:19286967
MEN---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NMALVSS--------TS
PKLVL---------NY--TNF----KHPTRGITGPRRSSSLALPF-KLS-----------
-TSRISA-SVRAGPY----------------------------------------QNGQV
GAGGFASLTSS-SGQQTSSVGVNPN-LPMPPP------SSNVGSP-LFWVGVGV----GL
SALFSFVASRLK------QYAMQQALKGMMNQMNTQ-----------------NKPFGNA
AFP----QG--SPFPFPNPPA---------SGP----------------------TTPY-
------PAASQPR-FTMDIP------------------------ATKV-----EAA----
-----------------------S-------ATD-------------VEGKKEVKGETE-
-------VK-EEPKKY------------AFVDVSPE--ETLQKS----------------
---PFDNFE----DVKETSS-----------------SK-----------DAQPP-----
KD------SQNGAAFNY----NAGS---PLGGQS-------AKKEGRFLTVDTLEKLMED
PQVQKM---------------------VYPSLPEEMRNPASFKLMLQN-PEYRKQLQEML
DGM-CES-GEFDG-RVLDSLKNFDLNSAEVKQQF------EQIGLTPEEVIT---KM---
--MANPEIALGFQSPRVQAAIME--------------CSQNPMNIIKYQNDKE-VMSVIT
K--------------------------------------------IAELFPGVT---GTS
------------------
>Citrus_sinensis_gnl|BL_ORD_ID|22996 _1.1g014282m|PACid:18115198
MEN---------------------------------------------------------
-----------------------------------------L------------------
-------------------------------------------NMALVSS--------TS
PKLVL---------NY--TNF----KHPTRGITGPRRSSSLALPF-KLS-----------
-TSRISA-SVRAGPH----------------------------------------QNGQV
GAGGFASLTSS-GGQQTSSVGVNPN-LPMPPP------SSNVGSP-LFWVGVGV----GL
SALFSFVASRLK------QYAMQQALKGMMNQMNTQ-----------------NKPFGNA
AFP----QG--SPFPFPNPPA---------SGP----------------------TTPY-
------PAASQPR-FTMDIP------------------------ATKV-----EAA----
-----------------------T-------ATD-------------VEGKKEVKGETE-
-------VK-EEPKKY------------AFVDVSPE--ETLQKS----------------
---SFDNFE----DVKETSS-----------------SK-----------DAQPP-----
KD------SQNGAAFNY----NAGS---PFGGQS-------AKKEGRFLTVDTLEKLMED
PQVQKM---------------------VYPSLPEEMRNPASFKLMLQN-PEYRKQLQEML
DGM-CES-GEFDG-RVLDSLKNFDLNSAEVKQQF------EQIGLTPEEVIT---KM---
--MANPEIALGFQSPRVQAAIME--------------CSQNPMNIIKYQNDKE-VMSVIT
K--------------------------------------------IAELFPGVT---GTS
------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|23259 _5g10800.1|PACid:21826029
MES---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------ILASSCS------AY
PRLPP---------------------LPA-ARR-----PSQPLP--ATSLSAGAGRRGAR
-RPRLVV----SAAA-----------------------------------RGSRNVLDGL
NTTAFASISSS-TSSENTSTGTGTL-PPMPPP------SSYIGSP-VFWIGIGI----AL
SAAFSMVSSMVK------KYAMEQAFKSMMTQTPPN------------------------
TFG----TN--SPFPFSMPPQ---------AGS------------TAPSS--YPYSGPR-
------KNTSPNG-TTVDVS------------------------ATDV-----AAT----
-----------------------E-------TSE-------------------VADVIE-
-------TS-KPSKKF------------AFVDVSPQ--ELQQKE----------------
---LQSSLE----TVDVKGA-----------------ST-----------ESEVK-----
EDAEQNV-PTNGAAFKP----TEDS---STGPTE-------SSKSGPMLSIDTIEKMMED
PAVQKM---------------------VYPYLPEEMRNPDSFKWMLQN-PMYRQQLEDML
NNM-GASPDQWDN-RMVDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KI---
--MANPEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQNDKE-VMDVFM
K--------------------------------------------ISQIFPQIN---G--
------------------
>Oryza_sativa_gnl|BL_ORD_ID|12651 _LOC_Os04g35900.1|PACid:21895123
MES---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------VLASSCS------AS
PRLPP---------------------LSA-ARRRR--PSSQTLP----ATAAASGRRGAG
-RSKLVVVAAAAAAA-----------------------------------RGSGNGFEGL
KTNGFASMSSS-TNSENMSTGTGSL-PPMPPP------SSYIGSP-VFWIGVGV----AL
SAAFSMVSSMVK------KYAMQQAFKSMMTQAPPN------------------------
TFG----SN--SPFPFAMPPQ---------AAP------------AAPSS--YPYSQPR-
------KDTSPQS-ATVDVS------------------------ATKV-----EAT----
-----------------------G-------TLE-------------------EADVAE-
----------QPKKKF------------AFVDVSPE--ELQQKE----------------
---LQSSLE----TVDVKSE-----------------SK-----------QSETM-----
EDTEQKA-PTNGTAFKM----NEGS---ASGTTE-------SSNSGPMLSVDTIEKMMED
PAVQKM---------------------VYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDML
NNM-GGSPDQWDN-RMLDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KI---
--MANPEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQNDKE-VMDVFM
K--------------------------------------------ISQIFPQIN---G--
------------------
>Panucum_virgatum_gnl|BL_ORD_ID|12878 _Pavirv00024278m|PACid:23768727
MES---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------VLASSCS------AS
PRLPV---------------------LSASAARLRGLPGAAPLP---ASSAAGAARSGAR
-RPRLLVAVAAAAAP-----------------------------------RGSRNVFEGL
RAKGFASVSSS-TGNENVSTGTGTL-PPMPPP------SSYFGSP-VFWIGVGV----AL
SVAFTTVSSMVK------RYAMQQAFKSMMTQSPSN------------------------
SFG----SN--SPFPFAMPPQ---------AAP------------TAPSS--YPYSQPK-
------RDTSPQV-ATVDVL------------------------ATEV-----EAS----
-----------------------G-------TPK-------------------EADVAE-
-------TP-KPSKKF------------AFVDVSPE--ELQQKN----------------
---LQSSLE----TVDVKRD-----------------ST-----------DSESK-----
EDTEQKV-PTNGAVFKP----NEDA---ARGPTE-------SSNSGPMLSVETIEKMMED
PAVQKM---------------------VYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDML
NNMGGSSPDQWDN-RMLDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KI---
--MANPEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQNDKE-VMDVFM
K--------------------------------------------ISQIFPQIN---G--
------------------
>Setaria_italica_gnl|BL_ORD_ID|21201 _Si010149m|PACid:19694675
MES---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------VLASSCS------AS
PRLPV---------------------LSA-AARFRGLPGAAPPT---AASTGGAARGGAR
-RPRLLV---AAAAP-----------------------------------RGSRNAFEGL
RAKGFASVSSS-TSNENTSTGTGTL-PPMPPP------SSYIGSP-VFWIGVGV----AL
SVAFTTVSSMVK------KYAMQQAFKSMMSQSPSN------------------------
SFG----SN--SPFPFAMPPQ---------AAP------------TAPSSYPYPYSVPK-
------KDTYPQA-ATVDVS------------------------ATEV-----EAA----
-----------------------G-------TSK-------------------EADVAE-
-------TP-KPSKKF------------AFVDVSPE--ELQQKN----------------
---LQSSLE----TVDVKSD-----------------ST-----------DSESK-----
EDTEREV-PTNGEAFKP----NEGA---ARGPTE-------SSNSGPMLSVETIEKMMED
PAVQKM---------------------VYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDML
NNM-GSSPDQWDN-RMVDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KI---
--MANPEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQNDKE-VMDVFM
K--------------------------------------------ISQIFPQIN---G--
------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|19148 _Sb06g017360.1|PACid:1972504
MES---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------VLASSCS------AS
PRLPL---------------------ISS-AARFRRLPGSVPPPTVAAASTGGAARKGPR
-RPRLFV--VAAAAP-----------------------------------RGSGNVFEGL
RAKGFASVSSS-TGNENMSTGTGTL-PPVPPP------SSYFGSP-VFWIGVGV----AL
SVAFTTVSSMVK------RYAMEQAFKSMMTQAPPN------------------------
SFG----SN--SPFPFGMPPQ---------ASP------------TAPSS--FPYLEPK-
------KDTSPQV-STVDVS------------------------ATEV-----EAA----
-----------------------G-------TSK-------------------EVDVTE-
-------TP-EPSKKF------------AFVDVSPE--ELQQKN----------------
---LQSSLE----TVDVKHD-----------------ST-----------DSESK-----
EDIEEKVLPTNGATFKP----NEDA---ARGPTE-------PSNSGPMLSVETIEKMMED
PTVQKM---------------------VYPYLPEEMRNPDSFKWMLQN-PMYRQQLQDML
NNM-GASPDQWDN-RMVDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KI---
--MANPDVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQNDKE-VMDVFM
K--------------------------------------------ISQIFPQIN---G--
------------------
>Zea_mays_gnl|BL_ORD_ID|52243 _GRMZM2G353213_T02|PACid:20872059
MES---------------------------------------------------------
-----------------------------------------L------------------
---------------------------------------------ILASSCS------AS
PRLPL---------------------LSS-AARFRGLPVSVPPP--SSASISGAARKGPM
-RPRLFV--AAAAAP-----------------------------------RGSGNVFEGL
RAKGFASMSSS-TGNENMSTGTGTL-PPMPPT------SSYIGSP-VFWIGVGV----AL
SVAFTTVSSMLK------RYAMQQAFKSMMTQSAPN------------------------
SFG----SN--SPFPFSMPPQ---------ASP------------TAPST--YPYLEPK-
------KDTSPHV-STVDVS------------------------ANEV-----EAT----
-----------------------G-------TSK-------------------EVDVTE-
-------TP-KPSKKF------------AFVDVSPE--ELQQKN----------------
---LQSSPE----TVDVKHDSTYSESKEDTEEQVPTIST-----------NTESK-----
EDTEEKV-PTNGASFKL----NEGA---AHGPTE-------SNNSASMLSVETIEKMMED
PAVQKM---------------------VYPYLPEEMRNPNSFKWMLQN-PMYRQQLQDML
NNM-GATPDQWDN-RMLDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KI---
--MANPDVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQNDKE-VMDVFM
K--------------------------------------------ISQIFPQIN---G--
------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|13162 _Pp1s159_2V6.1|PACid:18049697
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AMESRLLQAG-DVSS
PRGCFIVSSARDGAGHRQGQH----GFRVSAQRFMRGVQVRQGGNVCGRLEKKVSK----
-SKSVVV-AARKSTQ----------------------------------EQRETVVSKDD
SNEYIESSAEA-QGSG----------------------YSYIGSP-LLWIGVGV----GL
SALFSFGANAVK------RYAMQQMLKSMTGSAGGPGASPFGSPGANPFGAPGGNPFAGM
PMPP---PG--AGFPFPMPPT---------AAS--------------------PSPSPV-
-------SAAAAA-PPVDVS------------------------PTNV-----TSS----
-----------------------Q-------PSV-------------------VSETPK-
-------TS-TDAKKT------------AFTDVNAN--EILERE----------------
---QQAAAA----RFSDQAP-----------------SA-----------SEPTRPYFAD
PEL-----VDSKSGSNS----GAGAGPSSNDPWNS-----AGKGKQTVFTVDQLEKMMED
PTVQKM---------------------VYPYLPEEMRNPTTFKWMMQN-PQYRQQLQDML
NSM-GGD-GAWDN-RMSDMLNNFDLNSTEVKQQF------EQIGLTPEEVVA---KI---
--MANPEVAVAFQNPKVQAAIMD--------------CSTNPLNITKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGMN---GSP
F-----------------
>Physcomitrella_patens_gnl|BL_ORD_ID|11546 _Pp1s110_13V6.1|PACid:18048081
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AMESRVFHAGSSVAS
SRACFVVSSARAGSGHRQGQQ----GFQVAAQRFMRGAKLRDVGIECGRCGKKGSR----
-SEGIVA-AARKSTP----------------------------------EQEEYVVTKND
SNEYIESIAES-QGSG----------------------SSYIGSP-LLWIGVGV----GL
SALFSFGANSVK------RYAMQQMLKSMSGGAGGPGAS--------PFGAPGGNPFAGM
PMPP---PG--AGFPFPMPPT---------GS----------------------VSSPV-
-------SAAAAA-APVDVS------------------------P-NV-----TSS----
-----------------------Q-------PSV-------------------VSETPK-
-------SS-TEPKIA------------AFTDVNAT--EILERE----------------
---QQAAAAAAASRFSDQSP-----------------SA-----------QEPTRPFFAD
SEV-----VDSKGGSYS----GAGAGP-SNDPWDS-----AGKAKQTVFSVEQLEKMMED
PTVQKM---------------------VYPYLPEEMRNPTTFKWMMQN-PQYRQQLQDML
NSM-GGD-GAWDN-RMSDMLKNFDLNSTEVKQQF------EQIGLTPEEVVA---KI---
--MANPEVAVAFQNPKVQAAIMD--------------CSTNPLNITKYQNDKE-VMDVFN
K--------------------------------------------ISELFPGMA---GSP
F-----------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|19216 _437721|PACid:15420494
MAM---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------AHSLGFGALALHWRDGAPGAG
TSSSVRFYGSRRAPQ-------------------------------------RLVLSPLS
NRERLSVRCQSRSPAQDQAAGSAELQTVSVPPT----QPAYIGSP-LLWVGVGV----GL
SVLFSWAANYVK------KQAMQQALKSMMS--GPG-----------------QNQFGNM
PIP---------PFPFPVPPQ---------PQQ------------QPMPTFQPPVSSPQ-
--------ATQPQ---ASAS------------------------ATAVVEST-EAA----
-----------------------S-------YSE-------------------TQTPTP-
-------V--SENNKP------------AFTDVNVE--AEVSTV----------------
---KINA------EATEVKE-----------------NA-----------NDVFF---KD
AEV-----RDSGTGFTWN---TDGA---ASTSSS-------DGKANSFFSVENLEKMLED
PTVQQM---------------------VYPYLPQEMRNPSTFKWMMQN-PQFRTQLQEML
NNM-TED-GAWKNGQMGDVLKNFNPNNQELKQQF------EQIGLSPEEVMA---KM---
--VANPEIAMAFQNPKIQAALID--------------CSQNPTNITKYQNDKE-VMDVFN
K--------------------------------------------IAELFP-IK---GF-
------------------
>Cucumis_sativus_gnl|BL_ORD_ID|15634 _173410.1|PACid:16966613
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-MLLIFIPSLFDSSL-------------------------------------FSSLTWKP
VAERFATVSSSTTSNDSSSVGV-PS-VSIPPP------SSYVGSP-LFWVGVGV----GL
SALFTW------------KYAMQQAFKTMMSQMNSQ-----------------NSPMSNP
TLS----SG--SPFPTPPTFA---------TGT---------------------TISPS-
--------VSEPA-VSIDVT------------------------ATKV-----EEE----
-----------------------P-------VTN-------------------VKSRTE-
--------N-MEAKKF------------AFVDVSPE--ETDQKS----------------
---PFKE------DATDADV-----------------SK-----------SAQPT-----
EEL-----PQNGAASKQ----AYNG---SDGSQF-------SRKPGSVLSVEAVEKMMED
PTVQKM---------------------IYX------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|15848 _12.g508000.t1.1|PACid:19874172
MLC---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SRTTAPRGFGKAALALP---SR
ASIKCRAVQGSDQQQ-----------VVSAPVEAVAAPVPVPVAGAPLPQETTATYPMPP
PAPYYPGMPADAAARQQYYMAAPAAAYYPPPPAPYKEEPASTGAPWWIWLGAGV----IL
GQVLAKVQEYMKNPKTPQQIMMEMAMKQMSGAMGSP-----------------PGGAGMP
PFGG---PG--SPFGGAAPGANPFAGAAPGANP---------------------FANFA-
------AAAAAGP-STVDTT------------------------ASPA-----FAG----
-----------------------A-------SSS-------------------GASSSE-
----------RKGEKF------------A-SRLNSEGREPRKPEPAPAAAAAGAAAAASS
ATKPLDVVEPVVKEPSSSGS-----------------SSGASSSG-----RSSFF-----
ADV-----DAEASSRAG----GTSS---SSGSG--------AAPQDTGVMTDMMESMLRN
PEMQKM---------------------LYPYLPEPMRNPQSIEWMLSN-PEVKKQMEQMF
ASQ-----NVMSP-QMMDMMKGMDFNQDKVNKQF------AELGLKPEDVIS---KV---
--MANPDLAAGFSNPKVQAAIMD--------------ISQNPMNIVKYQTDPE-IMKVLE
K--------------------------------------------VTEIFQPQM---GGQ
K-----------------
>Volvox_carteri_gnl|BL_ORD_ID|13829 _Vocar20000831m|PACid:23137724
MLR---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------TRIAIPRGIGRVRPLAPRPVAN
LRVRCQATTGGDQQP-----------SVAPAVEVTAPPVVAPVAPIP---ETTATYVMPP
NPMYYQGMP---APRQDYYMAAPPAAYYPPPPAPYKEEPASSGAPWWIWLGLGV----IL
GQVLAKVQEYMKNPKTPQQIMMEMAMKQMSGAMGS------------------TTGAGMP
PFGG---AA--SPFGGPAGGA---------ANP---------------------FANFA-
------AAASAAPAATVDTT------------------------ASAV-----QAG----
-----------------------AFTPSPPSSSS-------------------STNGEV-
----------RKGEKF------------A-SRLSSEGREPRKVE-------------LPQ
ASKPLDVVEPVVKEPSTSSS-----------------SSTNSSSAGASKPRSSFF-----
ADV-----DMDATV-------TSTS---ASSSA--------AADGNSAVMSEMMESMLRN
PEMQKM---------------------LYPYLPEPMRNPQSIEWMLSN-PEVKKQMEQMF
AQQ-----NVMSP-QMMDMMKNMDFNQEKVNRQF------AELGLKPEDVIS---KV---
--MSNPELAAGFSNPKVQAAIID--------------ISSNPMNIVKYQTDPE-IMKVLE
K--------------------------------------------VTEIFQPQM----NQ
K-----------------
>Cyanophora_paradoxa_gnl|BL_ORD_ID|24807 _ConsensusfromContig41017-maker-ConsensusfromContig41017-snap-gene-0.0-mRNA-1:cds:9353/591-643:1:-
MAG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------RFFAGIGN----IL
G-----------------------------------------------------------
-----------KPFPFSLPP----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------GVKMEDVAKMQMEI---
--MKDPKLVEMMRNPKFVGAMQN--------------MMKDPSKAMEYLRDPE-VLAVVQ
R--------------------------------------------FEQTFKNLKPPGAPQ
P-----------------
>Cyanophora_paradoxa_gnl|BL_ORD_ID|15239 _ConsensusfromContig9128-snap_masked-ConsensusfromContig9128-abinit-gene-0.1-mRNA-1:cds:2242/836-1056:0:+
MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------FVG-GV----TP
AQLCSRSSGFLSSAEKATRIASAGHMRKARGAKFSV------------------------
-----------SAVTINPAPS---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------KAEEKRGRVLQSFFNKSELYLIRSPTAKKVLDAL----------------
------------------------------------------------------------
----------------------------AKVGERPRNDHIAFRSFGYGLGITALEELFLE
AGFKRM---------------------EQLYFPDKHLR-----------AHPSPQLS---
-----------------------DDAAPEQERVFISELIIDELSAKAQGIIK--------
----------------------------------------------RYLDEADPAARKFG
I--------------------------------------------LSSLMEER-------
------------------
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|529 _gnl|CMER|CME023C fusion protein of phosphoribosylaminoimidazole carboxylase and phosphoribosylaminoimidazole-succinocarboxamide synthase, chloroplast or mitochondrial precursor
MFG---------------------------------------------------------
------------------------------------------------------------
---------------------------------------------FVTSTSSPLGLRFSS
FHSNTITCFHHVSSGKNQFGG----TCRTANGAPARLGSRRLAPPRVLRTLNCSTM----
------------------------------------------------------------
------DLTAPVTSSGNNSIGDHSAQGRLTPLVPILMGSKADKKH-CDQIAAACHRFGLA
TEMHVLSAHKVPTRLLEVVGRLEADPRPKVYISVAG---------------------RSN
ALSGLLDGSVASPVIACPPPSDAFGGADIFSSL----------------RMPGGIAPVVS
LDPGNAALTAAKI-LGIHDPLVRDRVRAFQKANRDRLYVDDAEVATSAYLADIQAA----
-----------------------------------------------------ARENNVL
VSTDGVLSALVQQHAGTWRKKQGKVRDQFYSDAAKHMILVTTDR--------QSAFDRVL
AAVPFKGAVLNLVSAWWFRR-----------------TEHIVPNHLIAVPHPNVT-----
----------------------------IAKRCDPFPIEFVVRGYATGSTSTSLWKNYER
GVREY----------------------CGIKLPDNLHKNQKL-WMNLVTPTTKEDIGDAL
ISRQEIIDRGLMSAVDFDACAAYALRLFEYGQQVASEHGLILVDTKYEFGRDADGQICLI
DEIHTPDSSRYWLATSYEERIAS---------------GKEPENI-----DKE-ILRLWY
RDHCDPYKDEKLPEAPLELVTELSRRYIQLYEMITWDKFDLRLSTPSELQQALGPWFSGQ
GAKANFTMSSP-------
