>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
------------------YDDIPEARR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------QAVPKTASSPSRGNPA-----------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------LWIGSGIGLLVIAVGAAFAV
GL-------------FKPEPSQSKVETS----PTASTPPT----------GGTEAP----
-----NTPDTTLGHFSYKVAPENELQAITADNRIRLRSS------AARAYKQMSAAAAAD
GIKLQALSGFRTVEDQDYLFFRVKEERAQGAQQRAKVSAPPGRSEHHTGYAMDIGDATQP
NTHVNVTFEETRAFEWLQKNAPRYSFELSFPKGNSQGVSYEPWHWRYVGDKDSLETFYNA
RNLK--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------S
>gnl|BL_ORD_ID|3701 @Anabaena_sp_PCC_7120@ all3702 similar to D,D-carboxypeptidase
MNK---------------------------------------------------------
------AGFSGEPRDPFDELSD--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------DIPVAL
RDTPGITPK--QRLQRLIFVTGGVGAFVILAIVSGFVFFITTPKK-TTESQPSPAIADAT
PMPTASNPAD----LQAILGHLAYPEAPESELVPISRDGRIRMRRNAAQRFQEMAQAART
AGVILM---PISGFRSVKEQE-QLFFAIGAQRNQTPAQRA--ALSAPPGHSEHHTGYAVD
IGDGAAPTTNLQAIFENTRAFKW-LEANAARFGF------------EMSFPMDNSQGVSY
EPWHWRFVGDRDSLETFYKARNLKPVKTPQ------------------------------
--------------
>gnl|BL_ORD_ID|4180 @Anabaena_variabilis_ATCC_29413@ gi|75909785|ref|YP_324081.1| unnamed protein product [Anabaena variabilis ATCC 29413]
MNKAGFSGEPHDPFDELSDDIPVALRDTPGITPK--QRLQRLIFVMGAVGAFVILAIVSG
FVFF------------------------------ITTPRKTTESQPSPAIAD--ATPIPT
ASNPADLQAVLGHLAYPEA----------P-------ESELVPISRDGRIRMRRTAAQRF
QEMAQAA---RSAGVILLPISGFRSVKEQEQLF--------------FAIGAQRNQ-TPA
QRAALSAPPGHSEHHTGYAVDIGDGAAPTTNLQAIFENTRAFKW----LEANAARFGF--
-------EMSFPKDNSQ-------------------------------------------
---------------------------GVSYEPW---HWRFVGDRNSLETFYKARNLKPV
-------------------------------KTPQ
>gnl|BL_ORD_ID|3369 @Arthrospira_platensis_NIES_39@ 650386693 NIES39_J01590 putative carboxypeptidase [Arthrospira platensis NIES-39]
MY-------------------------------------K-----------NLDNVPPMT
S-EDIPEAIRD-TPKSD-NSNLGKSKR-------------SPKFWQW-------------
------LALAI-AAFGVAIA-LNYQ--------------FGIFVVDRTSIN-LSASETTD
AMQPPPTTNPLPTPSVIPNQVSQL-------PVNLLG------HLPYE------------
-----------------EAPESEL------------------------------------
-------KNITADGVIRLRRAAAYAF--------------LEMTDAARRSGI--------
--ILVPI-----------------------------------------------------
--SGFRGLEDQEFLFFDIKAQRGQVP---------------SQRAQVSAPPGYSEHHTGY
AIDVA-----------------DANFPDTDLRETFDQTPAFK-----WLLDNAAFYSFEL
SFPKDNPLGVSYE-----------------------------------------------
P-----------------------------------------------------------
-------WHWRYV----------------GDRHSLETFYKARSIDVAS------------
------------------------------------------------------------
-----PSDLVNGDN----------------------------------------------
------------------------------------------------------------
--------------------------------------
>gnl|BL_ORD_ID|2341 @Arthrospira_platensis_Paraca@ 646130070 AplaP_010100011966 peptidase M15B and M15C DD-carboxypeptidase VanY/endolysin [Arthrospira platensis Paraca]
M-----------------------------------------------------------
--------TS--EDIPEAIRD-TP----KSDNSNLGKS----------------------
---KRSPKFWQW-------------------LALAIAAFG--VAIALNYQFGIFVVDRTS
INLSASETT---DAMQPPPTTNPLPTPSVIPNQVSQLPVNLLGHLPYEEAPESE------
-------LKNITADG---------------------------------------------
------------------------------------------------------------
VIRLRRAAAYAFLEMTDAARRSGIILVPI-------------------------------
------------------------------------------------------------
----SGFRGLED-----------------------------------------QEFLFFD
----IKAQRGQVPS-------QRAQVSAPPGYS----EHHTGYAIDVA------------
----------------------------DANFP--------------------------D
TDLRETFDQ---------------------------------------------------
------------------------------------------------------------
--------------------------------------------------TPAF------
------------------------------------------------------------
--------------------------------K-----WLLDNAAFYS------------
----FELSFPKDN--PLGVSYEPWHWRYVGDRHSLET---------FYKARSIDVASPSD
LVNGDN
>gnl|BL_ORD_ID|2565 @Arthrospira_sp_PCC_8005@ 648387796 APCC8_010100013340 M15B family D-Ala-D-Ala carboxypeptidase VanY [Arthrospira sp. PCC 8005]
M-----------TSEDIPEAIR-------DTPNSDHSTLGKSQRSPKFWQWLA------L
GIVAFVVAL-----ALNY------------------------------------------
------------------------------------------------------QFGILV
VDRTSVNLSASETTDAMQPPPTTNPLPTPSVIPNQVSQLPVNLLGHLPYEEAPESE----
---------------------------------------------LKNITADGVIRLRRA
AAYAFLDMTDAARRSGI------------ILVPISG---------FRGLEDQEFLFFDIK
AQRGQVPSQRAQ-----------------VSAPPGYSEHHTGYAIDVGDAN---------
FPDTDLRETFDQTPAF-KWLVDNAAFYSFEL---SFPKDNPLGVSY-EPWHWRY----VG
DRHSLETFY---------------------------------------------------
------------------------------------------------------------
--------------------KARSIDVASPSDLVNGDN
>gnl|BL_ORD_ID|12254 Arabidopsis_thaliana AT1G13900.1|PACid:19650201
M---IVNFSFFLLLFVSV------------------------------------------
------------------------------------------------------------
-------------------------FVSSADSKATISIS---------------------
---------------PN---ALNR-------------SGDSVVIQWSGVDSPSDLDWLGL
YSPPESPNDHFIGYKFLNE------SSTWKDGFGSISLPL-------------TNL--RS
NYTFRIFRWSESEIDPKHKDHDQNPLPGTKHLLAESEQLTFGSGVGMPEQIHLSF-TNMV
NTMRVMF------------VAGDGEERFVRYGESKDLLGNS-------------AAARGM
------------RYEREHMCDSPANSTIGWRDPGWIFDTV------------MKNLNDGV
RYYYQVGSDSKGWSEIHSYIARDVTAEETV-------AFMFGDMGCATPYT-TFIRTQDE
SISTVKWILRDIEALGDKPAMISHIGDISYARGYSWVWDEFFAQVEPIASTVPYHVCIGN
HEYDFSTQPWKPDWAAS-------------------------------IYGNDGGGECGV
PYS-------------LKFNMPGNSSESTGMKAPPTRNLYYSYDMGTVHFVYI-STETNF
LK--GGSQYE--------FIKRDLESVDRKKTPFVVVQGHRPMYTTSN----EVRDTMIR
QKMVEHLEPLFVKNNVTLALWGHVHRYERFCPISNNTCGTQWQGNPVHLVIGMAGQDWQP
IWQP--RPNHPDLPIFPQPEQSMYRTGEFGYTRLVANKEKLTVSFVGNHDGEVHDTVEML
ASGVVISGSKESTKIPNLKTVPASATL---MGKSESNALWYAKGAGLMVVGVLLGFIIGF
FTRGKKSSSGNR------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------WIPVKN----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------EE----------T
>gnl|BL_ORD_ID|6440 Arabidopsis_thaliana AT4G15880.1|PACid:19644387
M-----------------------------------------------------------
------------------------------------------------------------
----------GAVAINRKRSDESFNFINQQSTNPLRN-S---------------------
---------------PYFQASKKR------------------------------------
------------RFSFAMSEDSGKPASSNPTISRISRYPD-------------AKAPLRR
EIHAPSRGILRY---GKAKSNDYC-EKDANFFVRKYDDA---KRSALEALRFVNKGKDFV
DLGDEV--------------------------EKEEVVSDD-------------SSVQAI
-----------------EVIDCDDDEEKKNLQPSFSSGVTDVKKGENFRVEDTSMMLDSL
SLDRDV--DNDASSLEAYRKLMQSAEKRNSKLEALGFEIVLNEKKLSLLRQ-SRPKTVEK
RVEVPRE------------------------------------PFIPLTEDEEA------
EVYRAFSGRNRRKVLATHENSNIDITGEVL------------------------------
----------------QCLTPSAWLNDEVINVYLELLK----------------ERETRE
PKKYLKCHYF--------NTFFYKKLVSDSGYNFKAVRRWTT------------------
-----------------------------------------------QRKLGYALIDCDM
IFVPIHRGVHWTLAVINNRESKLLYL----------------------------DSLNGV
DPMILNALAKYMGDEANEKSGKKIDANSWDMEFVED----LPQQKNGYDCGMFMLKYIDF
FSRGLGLCFSQE------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------HMPYFR----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LRTAKEILRLRAD
>gnl|BL_ORD_ID|30503 Arabidopsis_thaliana AT5G23210.3|PACid:19668450
MGSHSVEFSVLVLFLVSFLLGSTSA--------------------------EKLCSDNDG
DNGCFRSRVLAAQRADRVKELPGQPPVKFRQYAGYVTVNETHGRALFYWFFEATQNPSKK
PVLLWLNGGPGCSSIGFGAAEELGPFFPQNSSQPKLKLN---------------------
---------------PY---SWNK-------------AANLLFL----------------
----ESPVG--VGFSYTNT------SRDIKQLGDTVTA--------------------RD
SYNFLVNWFKRF---PQYKSHDFY-IAGESYAGHYVPQL---SELIYKENKIASK-KDFI
NLKGLM--------------------------IGNALLDDE-------------TDQKGM
-----------IEYAWDHAVISDALYEKVNKNCDFKQKLV------------TKECNDAL
DEYFDVYKILDMYSLYAPKCVPTSTNSSTS-------HSVAGNRPLPAFRSILRPRLISH
NEG----------------------------------WRRMAAGYDPCASEYT-------
EKY-----MNRKDVQEALHANVTNISYPWT------------------------------
----------------HCSDTVSFWSDAPASMLPTLRTLV---SAGLRVWVFSGDTDGRI
PV--TATRYS------------------LKKLGLKIVQDWTPWYT---------------
-----------------------------------------------KLQVN--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LVPSYK----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------L
>gnl|BL_ORD_ID|30502 Arabidopsis_thaliana AT5G23210.1|PACid:19668449
MGSHSVEFSVLVLFLVSFLLGSTSA--------------------------EKLCSDNDG
DNGCFRSRVLAAQRADRVKELPGQPPVKFRQYAGYVTVNETHGRALFYWFFEATQNPSKK
PVLLWLNGGPGCSSIGFGAAEELGPFFPQNSSQPKLKLN---------------------
---------------PY---SWNK-------------AANLLFL----------------
----ESPVG--VGFSYTNT------SRDIKQLGDTVTA--------------------RD
SYNFLVNWFKRF---PQYKSHDFY-IAGESYAGHYVPQL---SELIYKENKIASK-KDFI
NLKGLM--------------------------IGNALLDDE-------------TDQKGM
-----------IEYAWDHAVISDALYEKVNKNCDFKQKLV------------TKECNDAL
DEYFDVYKILDMYSLYAPKCVPTSTNSSTS-------HSVAGNRPLPAFRSILRPRLISH
NEG----------------------------------WRRMAAGYDPCASEYT-------
EKY-----MNRKDVQEALHANVTNISYPWT------------------------------
----------------HCSDTVSFWSDAPASMLPTLRTLV---SAGLRVWVFSGDTDGRI
PV--TATRYS------------------LKKLGLKIVQDWTPWYT---------------
-----------------------------------------------KLQVGGWTVEYDG
LMFVTVRGAGHQVPTFKPREALQLIHHFLGNK----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------KLPTFP----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------F
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
--------------------------------------YDDIPEARRQAVPKTASSPSRG
NPALWIGSGIGLLVIAVGAAFAVGLFKPE-PSQSKVETS---------------------
---------------PT-----------------------------------ASTPPTGG
TEAPNTPDTTLGHFSYKVA-----PENELQAITADNRIRL------------------RS
S-----------------------------------------AARAYKQMSAAAA-ADGI
KLQALS--------------------------GFRTVEDQDYLFFRVKEERAQGAQQRAK
VSAPPGRSEHHTGYAMD---IGDATQPNTHVNVTFEETRA--------------------
------------------------------------FEWLQKNAPRYSFEL-SFPKGNSQ
GVSYEPW-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------HWRYVGDKDS--
----LETFYN--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-ARNLK------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------S
>gnl|BL_ORD_ID|25150 Arabidopsis_thaliana AT3G12980.1|PACid:19663097
MAQGQNRTVLQSGQMHNSVVASASSVSSQPNMVNGISQDTLLLRQEMLNRTYAWLQQRQP
SKTDDASKAKLSEVAKRLESAMWRTATSKEDYLDFRSFDVRVESTLKQLLSQRRANPSSS
VSTMVQTPG---VSHGWGQSYTATPMVDTSKFNSSNNLSDATTETGRLLPTNRMYRGTIN
NGRQELSAVGQMIPTPGFDNSANADVYQSHRNEEYSGDGGKLLATGSDFGNPSQLQKQR-
----PTGSNDLMGYNLDHQLGGGFRSNIHQNTSGMTSIPLNAGVGMSGNNVHLANVP-RS
SEGVLSSTHFSTFSQPSQQPVEQL-QVSHVNRYSMSNSGTFVSGNLYGVQTSSGSIETAV
DMNSMSLNSMRRVDTSFGSQSGLQNNPLLKPHLRHQFENGNFQSSSNSKENLAQVSHRPL
ERQFNQQAHYGQYHQQELLMNNDA-----YRQSQPASNLV------------SQVKNEPR
VEYYNEAFQMQAINKVEPSKPQNQYKQNTVKDEYVGAQSAPVSSSQLKMSP-SFPPQTHQ
TQQVSQW--KDSSSLSAGVQPVSGLGQ----------WHSSSQNLTPISKNSN-------
EEREHFGVRFHKQHEGTNNSSSVRESTNCLTVAPSGTLDVPHLPVGINVLSKQLNGDCGL
SYKNQRRWLLFLLHVRKCNAAEDNCESKYCFTAKTLLKHINCCKAPACAYQYCHQTRQ--
----LIHHYKHCGDEACPVCVFVKNFKEKQKEKFTFLQRAEPSSASLNHGPKESFESMRT
SSERDSEAPFVVDDLQPSPKRQKVEKPSQFAYPDTQGNPATISAGVSQAHFSMGLQEKDR
LPSDVCKPVRSNVPMNADSSDSS--------RRLVPVSRELEKPVCKDTHMGRHGVKSAL
DGESLRLSKQEKPKRMNEISAPKEENAEQSLGVVSASNCGKSKIKGVSLIELFTPEQVEE
HIRGLRQWVGQSKTKAEKNKAMGLSMSENSCQLCAVERLAFEPTPIYCTPCGARVKRNAM
HYTVVAGESRHYVCIPCYNEARANTVSVDGTPVPKSRFEKKKNDEEVEESWVQCDKCQAW
QHQICALFNGRRNHGQAEYTCPNCYIQEVEQGERKPVSQNVILGAKSLPASTLSNHLEQR
LFKKLKQERQERARLQGKSYEEVPGADSLVIRVVASVDKILEVKPRFLDIFREDNYSSEF
PYKSKAILLFQKIEGVEVCLFGMYVQEFGTDSASPNQRRVYLSYLDSVKYFRPDVRTVSG
EALRTFVYHEILIGYLDYCKKRGFSSCYIWACPPLKGEDYILYCHPEIQKTPKTDKLREW
YLAMLKKASKEKVVVECTNFYDHFFVQSGECRAKVTAARLPYFDGDYWPGAAEDLIDQMS
QEEDGKKSNRKLMPKKVISKRALKAVGQLDLSVNASKDLLLMHKLGEIILPMKEDFIMVH
LQHCCKHCCTLMVSGNRWVCNQCKNFQICDKCHEVEENRVEKEKHPVNQKEKHVLYPVAI
DNIPTEIKDNDDILESEFFDTRQAFLSLCQGNHYQYDTLRRAKHSSMMILYHLHNPTVPA
FAMACAICQQELETAQGWRCEVCPDYDVCNACYSKGINHPHSIISRPSATDSVVQNTQTN
QIQNAQLREVLLHVMTCCTAQCQYPRCRVIKGLIRHGLVCKTRGCIACKKMWSLFRLHSR
NCRDPQCKVPKCRELRAHFSRKQQQADSRRRAAVMEMVRQRAADTTASTPE
>gnl|BL_ORD_ID|2376 @Gloeobacter_violaceus_PCC_7421@ 637459774 glr2377 similar to D,D-carboxypeptidase [Gloeobacter violaceus PCC 7421]
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------TDFDDIPVIQRAAATAPIPV---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------PTTK
RPLPKPPVLAAVAGMV--------------------------------------------
---------------------------VAVGLGLFLLLPKPGEESPK-------------
---AAQASA-----------------------------------PASGAKSASAPAGTLL
GHYRYKEAFRG------------------------DLVQIDFWRDT-DRPILLHKGAVES
YRQLVQAARAEGVILVTLSGFRSERYQQEVYAR-QLGKAGTTSTATLINAPPGYSEHHTG
YAIDFG--DGTVPGANL-------------------------------------------
-RPRFEQ----------------------------------------------------T
VAFRWL----------------------------------------------TANARKFG
FEMSFPKDNPQRV----------------------------SYEPWHW-RYVGDKRSIET
FYLGKG--R---------------------------------------------------
------------------------------------------------------------
---
>gnl|BL_ORD_ID|1 @Leptolyngbya_valderiana_BDU_20041@ Leptolyngbya_valderiana_BDU_20041 641057540 LVAL_00026 pseudouridine synthase Rsu [Leptolyngbya valderiana BDU 20041]
A------QHRLLDPKFGKS-----RAYWV---------------------------QVE-
---------------------------RVPDEASLQ--RLRDGVTIRQYRTRPARVRRLA
IAPDLPPRHPPIRFRKNVPTCWLEMSLTEGRNRQVRRMTAAVGHPTLRLVRVAVENLTLD
ALQPGQWRDLTLAEVSQ------LQKRC-----------GLSAVASRS-------GDRNR
ARY--------N
>gnl|BL_ORD_ID|4564 @Microcoleus_chthonoplastes_PCC_7420@ 647568950 MC7420_3835 D-alanyl-D-alanine carboxypeptidase family [Microcoleus chthonoplastes PCC 7420]
MKTPD-----------------------------------------------FPGEPV--
------------------------------------------------------------
-------------------------------------------------------NLSES
TEEDIPVAVRD-TPDTRRR-SR----LQPFLI------------ILAVLGGGAIVLGLIL
SSSTSQ------------------------------------------------------
------------------------------SPQTITASPQPTTTDT--------------
-----------STS---TTPEESESESENDVDNLLGHL--PYEEAPLSELEPITSDG---
-RIQLREAAAK------------KFKAMRAAAQA------------DGIV----------
--------------------------LVAISGYRTQQQQQHLFFDIKAQRGQVATQRAEV
SA------------------------------------------------------PPGY
SE---HHTGYAVD------------------IGDGRTPATNLNT-NFENTAAF-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
KWLEENAAYYSFELSFPKGNPQGVSYEPWHWR-----------------FVGDPDSLETF
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------YKAQNLDRPDLEPSPSSSEPEDESSTREQG--------
------------------------------------------------------------
--------------------------------------------------------TGNR
E
>gnl|BL_ORD_ID|786 @Microcystis_aeruginosa_NIES_843@ 641534767 MAE_07870 putative carboxypeptidase [Microcystis aeruginosa NIES-843]
MKP---------------------------------------------------------
------------------------------------------------------------
----------------IDDIPE--------------------------------------
------------------------------------ALRDSQYRKTTNP-----------
--------------------NGLIAIASGLLAL-VGTGIIALAV-LNRPPATVKKPVIN-
-PSPLIKAT-----PSPIENILGHLPYEEAPETEL-------------------------
---------------APITGDGAMRLRKPAAKAFIQM---QSDARRSGVILMP-ISAFRS
-----KATQDKLFFEVKEQRNQETR-------KRAEVSAPPG--YSEHHTGYAIDIGDGR
APATNLSSSF-----------ANTAAFRWLQNNAAQYSF-------------ELSFPENN
LQGINY------EPW---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------HWRFVGDSHSLETFYKAQQLGKQK
>gnl|BL_ORD_ID|4008 @Nostoc_sp_PCC_7120@ 637234094 all3702 hypothetical protein [Nostoc sp. PCC 7120]
MNK---------------------------------------------------------
------AGFSGEPRDPFDELSD--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------DIPVAL
RDTPGITPK--QRLQRLIFVTGGVGAFVILAIVSGFVFFITTPKK-TTESQPSPAIADAT
PMPTASNPAD----LQAILGHLAYPEAPESELVPISRDGRIRMRRNAAQRFQEMAQAART
AGVILM---PISGFRSVKEQE-QLFFAIGAQRNQTPAQRA--ALSAPPGHSEHHTGYAVD
IGDGAAPTTNLQAIFENTRAFKW-LEANAARFGF------------EMSFPMDNSQGVSY
EPWHWRFVGDRDSLETFYKARNLKPVKTPQ------------------------------
--------------
>gnl|BL_ORD_ID|2419 @Synechococcus_elongatus_PCC_6301@ 637618109 syc2418_c putative carboxypeptidase [Synechococcus elongatus PCC 6301]
MG----------------------------------------------------------
----------FQYDDDV-----------PVAIRSEVPTAKARTNRLLP--WVVGG-AVAA
IAI-----GAWAIVQRSSPTPEGVETPAE--------------------STAA-------
----TPNSLLGHRP------YADAAPES--------------------------------
-----LTPLASNAAIRL-----------RSPAAKAF--------DELQAAAAREGVRLVP
LSGFRSKKDQ-----EALFFDVKAERNQSVTERASVSA----------------------
------------------------------------------------------------
------------------------------------------------------------
------PPGYSEHHTGYAIDIGAADQPA--------------------------------
---------------THLETTFEQTAAFRWLQANAKRFSFELSFPRNNLQQVSYEPWHWR
FVGDLESLRLFYGDRSGTPAQ---------------------------------------
------------------------------------------------------------
--------------------------------------
>gnl|BL_ORD_ID|931 @Thermosynechococcus_elongatus_BP_1@ 637313549 tll0932 putative carboxypeptidase [Thermosynechococcus elongatus BP-1]
MD----------------------------------------------------------
-----------------------------QDIPVAERLQPIPQGKEKPR-----------
-----------QGGWAI--ASAIVLVGFMGVG----------------------------
----------AAW----FLSRPA------------------------------TSPTATG
RASTVTPTE---------------NLLGHLPYEEAPLSELEPVSADGQIKLRRAAAERFR
AMVAAAQQEGVVLIPLSG-----------------------------------FRSTQDQ
D------------YLFFEVKEHRAQRASERALVSA-------------------------
------------------------------------------------------------
-------------------PPGYSEHHTGYAVDIGDGAQPQTHLKETFEDTPAFRWLAKN
AARFSFELSFPRNN------PQG---VSYEPWH--------------------WRFVGD-
------------------------------------------------------------
--------------------------------------RHSLQTFYRARQLRLRNAP---
------------------------------------------------------------
---
>gnl|BL_ORD_ID|3901 @Trichodesmium_erythraeum_IMS101@ gi|113477844|ref|YP_723905.1| unnamed protein product [Trichodesmium erythraeum IMS101]
MKILNKLGLLKKTPDEAKLPVDDIPEAVRDE-EESAKHQSFKPQKIWQIWQLLAMGAIAL
IISISWHFQFNKTLNTSPVVQMKQKISTKAVETSPTQLETPSPSPSFNSSIKQRENILGH
LPYKEASWQELTPVFGNQ--------------NIRLRSIAAEKFDLMADVAWSANIELVP
LSGFR---TVGDQQYLFFEVKAERGQETSKRAE---------------------------
--VSAPPGYSEHHTGYAIDIGDARMPETHLEVSFENTKAFQWLQENAENYGFE-------
--LSFPKDNPQ-------GISYEPWHWRFVGDSHSLK-----------------------
---------------------------------------------TFEE---ARSLK---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------E
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-------------------YDDIPEARRQAVPKTASSPSRGNPALW-----IGSGIGLL
VIAVGAAF---------AVGLFKPEPSQSKVETSPT---ASTPPTGGTEAPNTPDTTLGH
FSYKVAPENELQAITADN--------------RIRLRSSAARAYKQMSAAAAADGIKLQA
LSGFR---TVEDQDYLFFRVKEERAQGAQQRAK---------------------------
--VSAPPGRSEHHTGYAMDIGDATQPNTHVNVTFEETRAFEWLQKNAPRYSFE-------
--LSFPKGNSQ-------GVSYEPWHWRYVGDKDSLE-----------------------
---------------------------------------------TFYN---ARNLK---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------S
