>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-------------------YDDIPEARRQA--VPKT------ASSPSRGNPALWIGSGI
GLLV--IAVGAAFAV----------------GLFKPEPSQSKVETSPT-ASTPPTGGTEA
PNTPDTTLGHFSYKVAPENELQAI----TADNRIRLRSSAARAYKQMSAAAAADGIKLQA
LSGFRTVEDQDYLFFRVKEERAQGAQQRAKVSAPPGRSEHHTGYAMDIGDATQPNTHVNV
TFEETRAFEWLQKNAPRYSFELSFPKGNSQGVSYEPWHWRYVGDKDSLETFYNARNL---
KS------------------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|3701 all3702 similar to D,D-carboxypeptidase
MNK---AGFSGEPRDPFDELSDDIPVALRDT---PGI------TPK-QRLQRLIFVTGGV
GAFV-ILAIVSGFVFFITTPK----------KTTESQP--SPAIADA--TPMPTA---SN
PADLQAILGHLAYPEAPESELVPI----SRDGRIRMRRNAAQRFQEMAQAARTAGVILMP
ISGFRSVKEQEQLFFAIGAQRNQTPAQRAALSAPPGHSEHHTGYAVDIGDGAAPTTNLQA
IFENTRAFKWLEANAARFGFEMSFPMDNSQGVSYEPWHWRFVGDRDSLETFYKARNL---
KPVKTPQ-------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|4564 647568950 MC7420_3835 D-alanyl-D-alanine carboxypeptidase family [Microcoleus chthonoplastes PCC 7420]
MKT---PDFPGEPVNLSESTEEDIPVAVRDT---PDT-------RRRSRLQPFLIILAVL
GG----GAIVLGLIL--------SSSTSQSPQTITASP--QPTTTDTSTSTTPEESESES
ENDVDNLLGHLPYEEAPLSELEPI----TSDGRIQLREAAAKKFKAMRAAAQADGIVLVA
ISGYRTQQQQQHLFFDIKAQRGQVATQRAEVSAPPGYSEHHTGYAVDIGDGRTPATNLNT
NFENTAAFKWLEENAAYYSFELSFPKGNPQGVSYEPWHWRFVGDPDSLETFYKAQNLDRP
DLEPSPSSSEPEDESSTREQGTGNRE
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|931 637313549 tll0932 putative carboxypeptidase [Thermosynechococcus elongatus BP-1]
M-------------------DQDIPVAERLQ---PIP------QGK-EKPRQGGWAIASA
IVLV--GFMGVGAAW------------------FLSRPATSPTATGRA----------ST
VTPTENLLGHLPYEEAPLSELEPV----SADGQIKLRRAAAERFRAMVAAAQQEGVVLIP
LSGFRSTQDQDYLFFEVKEHRAQRASERALVSAPPGYSEHHTGYAVDIGDGAQPQTHLKE
TFEDTPAFRWLAKNAARFSFELSFPRNNPQGVSYEPWHWRFVGDRHSLQTFYRARQL---
RLRNAP--------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|786 641534767 MAE_07870 putative carboxypeptidase [Microcystis aeruginosa NIES-843]
MKP-----------------IDDIPEALRDS-----------QYRKTTNPNGLIAIASGL
LALVGTGIIALAVL-------------------NRPPATVKKPVIN------PSPLIKAT
PSPIENILGHLPYEEAPETELAPI----TGDGAMRLRKPAAKAFIQMQSDARRSGVILMP
ISAFRSKATQDKLFFEVKEQRNQETRKRAEVSAPPGYSEHHTGYAIDIGDGRAPATNLSS
SFANTAAFRWLQNNAAQYSFELSFPENNLQGINYEPWHWRFVGDSHSLETFYKAQQL---
GKQK----------------------
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|3369 650386693 NIES39_J01590 putative carboxypeptidase [Arthrospira platensis NIES-39]
MYK--------NLDNVPPMTSEDIPEAIRDT---PKSDNSNLGKSK-RSPKFWQWLALAI
AAFG--VAIALNYQFGIFVVDRTSINLSASETTDAMQP--PPTTNP---LPTPSVIPNQV
SQLPVNLLGHLPYEEAPESELKNI----TADGVIRLRRAAAYAFLEMTDAARRSGIILVP
ISGFRGLEDQEFLFFDIKAQRGQVPSQRAQVSAPPGYSEHHTGYAIDVADANFPDTDLRE
TFDQTPAFKWLLDNAAFYSFELSFPKDNPLGVSYEPWHWRYVGDRHSLETFYKARSI---
DVASPSDLVNGDN-------------
>Arthrospira_sp_PCC_8005_gnl|BL_ORD_ID|2565 648387796 APCC8_010100013340 M15B family D-Ala-D-Ala carboxypeptidase VanY [Arthrospira sp. PCC 8005]
M------------------TSEDIPEAIRDT---PNSDHSTLGKSQ-RSPKFWQWLALGI
VAFV--VALALNYQFGILVVDRTSVNLSASETTDAMQP--PPTTNP---LPTPSVIPNQV
SQLPVNLLGHLPYEEAPESELKNI----TADGVIRLRRAAAYAFLDMTDAARRSGIILVP
ISGFRGLEDQEFLFFDIKAQRGQVPSQRAQVSAPPGYSEHHTGYAIDVGDANFPDTDLRE
TFDQTPAFKWLVDNAAFYSFELSFPKDNPLGVSYEPWHWRYVGDRHSLETFYKARSI---
DVASPSDLVNGDN-------------
>Trichodesmium_erythraeum_IMS101_gnl|BL_ORD_ID|3901 gi|113477844|ref|YP_723905.1| unnamed protein product [Trichodesmium erythraeum IMS101]
MKILNKLGLLKKTPDEAKLPVDDIPEAVRDE---EESAKHQSFKPQ-KIWQIWQLLAMGA
IALI--ISISWHFQFNKTLNTSPVVQMKQKISTKAVET--SPTQLE---TPSPSPSFNSS
IKQRENILGHLPYKEASWQELTPV----FGNQNIRLRSIAAEKFDLMADVAWSANIELVP
LSGFRTVGDQQYLFFEVKAERGQETSKRAEVSAPPGYSEHHTGYAIDIGDARMPETHLEV
SFENTKAFQWLQENAENYGFELSFPKDNPQGISYEPWHWRFVGDSHSLKTFEEARSL---
KE------------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|2419 637618109 syc2418_c putative carboxypeptidase [Synechococcus elongatus PCC 6301]
MGF---------------QYDDDVPVAIRSE--VPTA------KARTNRLLP--WVVGGA
VAAI---AIGAWAIV------------------QRSSP--TPEG-----VETPAE---ST
AATPNSLLGHRPYADAAPESLTPL----ASNAAIRLRSPAAKAFDELQAAAAREGVRLVP
LSGFRSKKDQEALFFDVKAERNQSVTERASVSAPPGYSEHHTGYAIDIGAADQPATHLET
TFEQTAAFRWLQANAKRFSFELSFPRNNLQQVSYEPWHWRFVGDLESLRLFYGDRSG---
TPAQ----------------------
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|2376 637459774 glr2377 similar to D,D-carboxypeptidase [Gloeobacter violaceus PCC 7421]
MTD-----------------FDDIPVIQRAAATAPIP------VPTTKRPLPKPPVLAAV
AGMV--VAVGLGLFL----------------LLPKPGEE-SPKAAQ---ASAPASGAKSA
SAPAGTLLGHYRYKEAFRGDLVQIDFWRDTDRPILLHKGAVESYRQLVQAARAEGVILVT
LSGFRSERYQQEVYAR-QLGKAGTTSTATLINAPPGYSEHHTGYAIDFGDGTVPGANLRP
RFEQTVAFRWLTANARKFGFEMSFPKDNPQRVSYEPWHWRYVGDKRSIETFYLGKGR---
--------------------------
