>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|145 641249277 AM1_0151 D-alanyl-D-alanine carboxypeptidase, putative [Acaryochloris marina MBIC11017]
M-------------------YDDIPEARRQA--VPKT------ASSPSRGNPALWIGSGI
GLLV--IAVGAAFAV----------------GLFKPEPSQSKVETSPT-ASTPPTGGTEA
PNTPDTTLGHFSYKVAPENELQAI----TADNRIRLRSSAARAYKQMSAAAAADGIKLQA
LSGFRTVEDQDYLFFRVKEERAQGAQQRAKVSAPPGRSEHHTGYAMDIGDATQPNTHVNV
TFEETRAFEWLQKNAPRYSFELSFPKGNSQGVSYEPWHWRYVGDKDSLETFYNARNL---
KS------------------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|3701 all3702 similar to D,D-carboxypeptidase
MNK---AGFSGEPRDPFDELSDDIPVALRDT---PGI------TPK-QRLQRLIFVTGGV
GAFV-ILAIVSGFVFFITTPK----------KTTESQP--SPAIADA--TPMPTA---SN
PADLQAILGHLAYPEAPESELVPI----SRDGRIRMRRNAAQRFQEMAQAARTAGVILMP
ISGFRSVKEQEQLFFAIGAQRNQTPAQRAALSAPPGHSEHHTGYAVDIGDGAAPTTNLQA
IFENTRAFKWLEANAARFGFEMSFPMDNSQGVSYEPWHWRFVGDRDSLETFYKARNL---
KPVKTPQ-------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|4564 647568950 MC7420_3835 D-alanyl-D-alanine carboxypeptidase family [Microcoleus chthonoplastes PCC 7420]
MKT---PDFPGEPVNLSESTEEDIPVAVRDT---PDT-------RRRSRLQPFLIILAVL
GG----GAIVLGLIL--------SSSTSQSPQTITASP--QPTTTDTSTSTTPEESESES
ENDVDNLLGHLPYEEAPLSELEPI----TSDGRIQLREAAAKKFKAMRAAAQADGIVLVA
ISGYRTQQQQQHLFFDIKAQRGQVATQRAEVSAPPGYSEHHTGYAVDIGDGRTPATNLNT
NFENTAAFKWLEENAAYYSFELSFPKGNPQGVSYEPWHWRFVGDPDSLETFYKAQNLDRP
DLEPSPSSSEPEDESSTREQGTGNRE
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|931 637313549 tll0932 putative carboxypeptidase [Thermosynechococcus elongatus BP-1]
M-------------------DQDIPVAERLQ---PIP------QGK-EKPRQGGWAIASA
IVLV--GFMGVGAAW------------------FLSRPATSPTATGRA----------ST
VTPTENLLGHLPYEEAPLSELEPV----SADGQIKLRRAAAERFRAMVAAAQQEGVVLIP
LSGFRSTQDQDYLFFEVKEHRAQRASERALVSAPPGYSEHHTGYAVDIGDGAQPQTHLKE
TFEDTPAFRWLAKNAARFSFELSFPRNNPQGVSYEPWHWRFVGDRHSLQTFYRARQL---
RLRNAP--------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|786 641534767 MAE_07870 putative carboxypeptidase [Microcystis aeruginosa NIES-843]
MKP-----------------IDDIPEALRDS-----------QYRKTTNPNGLIAIASGL
LALVGTGIIALAVL-------------------NRPPATVKKPVIN------PSPLIKAT
PSPIENILGHLPYEEAPETELAPI----TGDGAMRLRKPAAKAFIQMQSDARRSGVILMP
ISAFRSKATQDKLFFEVKEQRNQETRKRAEVSAPPGYSEHHTGYAIDIGDGRAPATNLSS
SFANTAAFRWLQNNAAQYSFELSFPENNLQGINYEPWHWRFVGDSHSLETFYKAQQL---
GKQK----------------------
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|3369 650386693 NIES39_J01590 putative carboxypeptidase [Arthrospira platensis NIES-39]
MYK--------NLDNVPPMTSEDIPEAIRDT---PKSDNSNLGKSK-RSPKFWQWLALAI
AAFG--VAIALNYQFGIFVVDRTSINLSASETTDAMQP--PPTTNP---LPTPSVIPNQV
SQLPVNLLGHLPYEEAPESELKNI----TADGVIRLRRAAAYAFLEMTDAARRSGIILVP
ISGFRGLEDQEFLFFDIKAQRGQVPSQRAQVSAPPGYSEHHTGYAIDVADANFPDTDLRE
TFDQTPAFKWLLDNAAFYSFELSFPKDNPLGVSYEPWHWRYVGDRHSLETFYKARSI---
DVASPSDLVNGDN-------------
>Arthrospira_sp_PCC_8005_gnl|BL_ORD_ID|2565 648387796 APCC8_010100013340 M15B family D-Ala-D-Ala carboxypeptidase VanY [Arthrospira sp. PCC 8005]
M------------------TSEDIPEAIRDT---PNSDHSTLGKSQ-RSPKFWQWLALGI
VAFV--VALALNYQFGILVVDRTSVNLSASETTDAMQP--PPTTNP---LPTPSVIPNQV
SQLPVNLLGHLPYEEAPESELKNI----TADGVIRLRRAAAYAFLDMTDAARRSGIILVP
ISGFRGLEDQEFLFFDIKAQRGQVPSQRAQVSAPPGYSEHHTGYAIDVGDANFPDTDLRE
TFDQTPAFKWLVDNAAFYSFELSFPKDNPLGVSYEPWHWRYVGDRHSLETFYKARSI---
DVASPSDLVNGDN-------------
>Trichodesmium_erythraeum_IMS101_gnl|BL_ORD_ID|3901 gi|113477844|ref|YP_723905.1| unnamed protein product [Trichodesmium erythraeum IMS101]
MKILNKLGLLKKTPDEAKLPVDDIPEAVRDE---EESAKHQSFKPQ-KIWQIWQLLAMGA
IALI--ISISWHFQFNKTLNTSPVVQMKQKISTKAVET--SPTQLE---TPSPSPSFNSS
IKQRENILGHLPYKEASWQELTPV----FGNQNIRLRSIAAEKFDLMADVAWSANIELVP
LSGFRTVGDQQYLFFEVKAERGQETSKRAEVSAPPGYSEHHTGYAIDIGDARMPETHLEV
SFENTKAFQWLQENAENYGFELSFPKDNPQGISYEPWHWRFVGDSHSLKTFEEARSL---
KE------------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|2419 637618109 syc2418_c putative carboxypeptidase [Synechococcus elongatus PCC 6301]
MGF---------------QYDDDVPVAIRSE--VPTA------KARTNRLLP--WVVGGA
VAAI---AIGAWAIV------------------QRSSP--TPEG-----VETPAE---ST
AATPNSLLGHRPYADAAPESLTPL----ASNAAIRLRSPAAKAFDELQAAAAREGVRLVP
LSGFRSKKDQEALFFDVKAERNQSVTERASVSAPPGYSEHHTGYAIDIGAADQPATHLET
TFEQTAAFRWLQANAKRFSFELSFPRNNLQQVSYEPWHWRFVGDLESLRLFYGDRSG---
TPAQ----------------------
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|2376 637459774 glr2377 similar to D,D-carboxypeptidase [Gloeobacter violaceus PCC 7421]
MTD-----------------FDDIPVIQRAAATAPIP------VPTTKRPLPKPPVLAAV
AGMV--VAVGLGLFL----------------LLPKPGEE-SPKAAQ---ASAPASGAKSA
SAPAGTLLGHYRYKEAFRGDLVQIDFWRDTDRPILLHKGAVESYRQLVQAARAEGVILVT
LSGFRSERYQQEVYAR-QLGKAGTTSTATLINAPPGYSEHHTGYAIDFGDGTVPGANLRP
RFEQTVAFRWLTANARKFGFEMSFPKDNPQRVSYEPWHWRYVGDKRSIETFYLGKGR---
--------------------------
>Aquilegia_coerulea_gnl|BL_ORD_ID|26324 _003_00099.1|PACid:22049415
--ME--------------------------------------------------------
------------------------------------------------------------
----------------------------NYALVCS----------------PNLTLFNVS
GSST---TTTMKGPI----------------------------------SIRTPLFANHI
LFRKSFNTTKSRFLV-KAT--AALP---------------------------KPTLHIID
SSTSTTLRTNGHEAFARISSS-SGTETSSVGVRPE-ISMPPP------SSTVGSP-LFWI
GVGVGLSALFSW--------VATNLK------KYAMQQAFKTMMGSMSSEKSPFSNP---
------AFNNPA---FS------PG--SPFPFPAP--PT---------STT---------
------------STSPS------------PVASKPA-VTVDVPATKV----EAT------
---------------------Q-------ATE-------------------VNSKTEIK-
EEPKRY------------AFVDVSPE--EIVEKD-------------------PFKSSK-
---ELKETKA-----------------TT-----------NAQNT-----EEV-------
--------------SRNGAATKG----DAGAY--SEQSNS--T--RRAGSVLSVEALEKM
MEDPTVQNM---------------------VFPY--------------------------
-------------------------LPEEMRDPTTFKWMLQNPQYRQQLEDMLNNM-GGS
-SEW-DNKMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PEVAMAFQNPRVQAAIMD--------------CSQNPLSIAKYQND
KEVMDVFNK-ISELFPGVT---G-------------------------------------
----------------SP-
>Prunus_persica_gnl|BL_ORD_ID|11413 _ppa013039m|PACid:17651878
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------M
LEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPSTFKWMLQNPQYRQQLEDMLNNM-GGS
-NEW-DNRMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PEVAMAFQNPRVQAAIMD--------------CSQNPLSIAKYQND
KEVMDVFNK-ISELFPGVS---G-------------------------------------
----------------SP-
>Vitis_vinifera_gnl|BL_ORD_ID|17248 _GSVIVT01025999001|PACid:17833873
--MD--------------------------------------------------------
------------------------------------------------------------
----------------------------SLTLVSS----------------PKLVL----
GHSP-------SNPRHI--------------------------------SCAHSSFSLPL
LFRK-----PRKFIAASQS--GASP----------------------------------R
TPRHVVETKLGTECFASISSS--SQGTSSVGVNPQ-FSPPPP------SSNIGSP-LFWI
GVGVGLSALFSW--------VASNLK------KYAMQQAFKTLMGQMDSQ-----NN---
------QFNTTT---FS------PG--SPFPFPMP--PP---------SGP-------ST
SHSGPTTSPSGPTTSPS------------TVAAQSM-VTVDVPATKV----ETP------
---------------------P-------ATD-------------------VKDDIEKK-
NEQNKY------------AFVDVSPE--ETLQES-------------------PFENFE-
---ESTETSS-----------------SK-----------DAQFS-----AGV-------
--------------SQNGTPPRP----GMGV---SEDSQS--T--RNANPFLSVDALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLQDMLNNM-GGG
-AEW-DNRMMDNLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PDVALAFQNPRIQAAIMD--------------CSQNPLSIAKYQND
KEVMDVFNK-ISELFPGVS---G-------------------------------------
----------------PP-
>Cucumis_sativus_gnl|BL_ORD_ID|15635 _173420.1|PACid:16966614
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MRNPETFKWMMQNPLYRQQLEEMLNNM-SGS
-PQW-DGRLMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PEIAMAFQNPRVQAAIMD--------------CSQNPLSITKYQND
KEVMDVFNK-ISELFPGVS---G-------------------------------------
----------------AP-
>Eucalyptus_grandis_gnl|BL_ORD_ID|2229 _A02100.1|PACid:23563950
--MP--------------------------------------------------------
---------------------------------------------------------HHF
RSADQRRREEKAKASTRFGSKNHVTNHKTSALGSPDGSISSSSSARRQLPDRDMSPFAAM
AANLQVSPHLYALPSSSHSSRAGSGGGGGRGSVP---------------PPRNK-----Q
LLSRTLLCQRRPDEA-ARL-----------------------------------------
RRYRTAPQAAESECFASISSSRSSKETTSVGVPPQ-PPVPPP------PSSFGSP-LFWI
GVGVGVSALFSW--------VANYLK------KYAMQQAFKAMMGQMNSQ-----NN---
------QFAGSP---FS------SA--SPSPFPMG--SA---------PRP---------
------------TPSP-------------MATSQPS--TVDISATKV----EAV------
----------------KAETAP-------VAD-------------------VKDEIKKE-
EELKRY------------AFVDISPE--ETKEKS-------------------PFESFK-
---DVTETTS-----------------SE-----------ATQFV-----GNA-------
--------------PQNGSASKS----VDSS---SEASES--T--GKGNPVLSVDALEKM
MEDPTVQKM---------------------VFPH--------------------------
-------------------------LPEEMRNPETFKWMLQNPQYRQQLEEMLNNM-GGS
-SEW-DGRMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PEVAMAFQNPRVQQAIMD--------------CSQNPLSIAKYQND
KEVMDVFNK-ISELFPGVT---G-------------------------------------
-----------------P-
>Glycine_max_gnl|BL_ORD_ID|31596 _11g31810.1|PACid:16285086
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------KL-------NLALVSSP---------------KPLML----
GHVP----------------------------------ARDVFRRKHF-SFGRV-----L
IAPH-----RCRFRV-SAL--SSSH---------------------------HNP-----
---KSVQEKLIVKHFASISSS-NTQETTSIGVKPQ-LS-PSP------SSTIGSP-LFWI
GVGVGLSALFSV--------VASRLK------KYAMQQAFKTMMGQMNSQ-----NN---
------QFGNAA---FS------PG--SPFPFPMP--TA---------AGP-------TA
PASSATTQSRAPSASS---------------ASQST-ITVDLPAAKV----EAA------
---------------------P-------TTN-------------------VKDEVELK-
NEPKKI------------AFVDVSPE--ETVRES-------------------PFESFK-
---D-DESSS-----------------VK-----------EAWVP-----DEV-------
--------------SQNGAPSNL----GFGD---FPGSQS--T--KKS--ALSVDALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLEEMLNNM-GGS
-TEW-DNRMMDTLKNFDLNSPEVKQQF------DQIGLSPEEVIS---KIMAN-------
--------------PEVAMAFQNPRVQAAIMD--------------CSQNPMNITKYQND
KEVMDVFNK-ISELFPGV----G-------------------------------------
----------------SP-
>Phaseolus_vulgaris_gnl|BL_ORD_ID|25224 _091029773m|PACid:23556101
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL-------NLALVSS---------------SKPLML----
GHVPARDAT-----------------------------DRDVLRRKPF-SLGRV-----L
IAPH-----RFRYRV-SAL--SSSH---------------------------HSP-----
---KSVQDKLIVKHFASISSS-NTQETTSIGVNPQ-LS-PPP------SSTIGSP-LFWI
GVGVGLSALFSM--------VASRLK------KYAMQQAFKTMMGQMNSP-----NN---
------DFGNAA---FS------PG--SPFPFSMP--SA---------AGP---------
---TATAQYGAPSTSS---------------GSQST-VTVDIPATKV----EAT------
---------------------R-------TTD-------------------IKDEVEVQ-
NKPKKI------------AFVDVSPE--ETVQKS-------------------PFESVK-
---DNESSSV-----------------KE-----------EARVP-----DEV-------
--------------SQNGAPFNQ----GFGG---FPGSQS--T--KKS--ALSVDALEKM
MEDPTVQKM---------------------VYPH--------------------------
-------------------------LPEEMRNPDTFKWMLQNPQYRQQLEAMLSNM-GGS
-TEW-DNRMMDTLKNFDLNSPEVKQQF------DQIGLSPEEVIS---KIMAN-------
--------------PEVAMAFQNPRVQAAIMD--------------CSQNPMNITKYQND
KEVMNVFNK-ISELFPGM----G-------------------------------------
----------------SP-
>Glycine_max_gnl|BL_ORD_ID|48697 _18g05480.1|PACid:16308005
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------KL-------NLALVSSP---------------KPLML----
GHGL-NCSSSLQIPCFCTLF---------------------------------------L
PSHEYPMLTFLRISV-SMV-----------------------------------------
KHFFLKKEKLIVKHFASISSS-NTQEATSTGVNPQ----LSP------SSTIGSP-LFWI
GVGVGLSALFSV--------------------KYAMQQAFKTMMGQMNSQ-----NN---
------QFGNAA---FS------PG--SPFPFPMP--TA---------AGP-------TA
PASSATTQSRAPSASS---------------ASQST-ITVDIPAAKV----EVA------
---------------------P-------TTN-------------------VKDEVELKM
ENIQGI------------IFINVSPE--ETVQES-------------------PFESFK-
---D-DESSS-----------------VK-----------EARVP-----DEV-------
--------------SQNGAPSNQ----GFGD---FPGSQS--T--KKS--VLSVDALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLEEMLNNM-GGS
-TEW-DSRMMDTLKNFDLNSPEVKQQF------DQIGLSPEEVIS---KIMAN-------
--------------PEVAMAFQNPRVQAAIMD--------------CSQNPMNITKYQND
KEVMDVFNK-ISELFPGV----G-------------------------------------
----------------SP-
>Manihot_esculenta_gnl|BL_ORD_ID|27495 _4.1_006941m|PACid:17987472
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL-------NMALLSSP------SSSSSSYSSPKLVL----
GY-----STYLKNPTATRQF--------------------SRTRALPF-TLRNY-----R
TVPH-----SSRISI-SAI--AHSR---------------------------SST----G
PRRVSHDRRLGADYLLSISSS-AGQQTSSVGVNPQPLPSPSP------SSQFGSP-LFWI
GVGVGLSALFSW--------VATNLK------KYAMQQALKTMMNQMTTQ-----NN---
------QFTNPA---VS------PG--SPFPFPIP--PA---------SGPASSPAYQTP
STSGAAISPSSPTSSGSFDSNSS-----PRVTSQSA-ITVDVPATKV----EAT------
---------------------P-------VSD-------------------AKDESEIK-
KEPKKY------------AFVDVSPE--ETFTKS-------------------PFKGDE-
---DI---SG-----------------AG-----------SSQFA-----KEV-------
--------------SQNGAASNQ----GSTT---STASDG--S--KSTRPRLSVEALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPSTFKWMLQNPQYRQQLEDMLNNM-SGS
-GEW-DNRMMESLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PDVALAFQNPRVQQAIMD--------------CSQNPLSISKYQND
KEVMDVFNK-ISELFPGVS---G-------------------------------------
----------------S--
>Ricinus_communis_gnl|BL_ORD_ID|3984 _29005.m000255|PACid:16802149
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL-------NMGLLSS------------FYASPKLVM----
GCCY---PNSLKNPTVTTNKQ--------------FSRTSTSTRALPF-SLRNY-----K
IVTR-----SSRFSI-SAL--AHSH---------------------------SSP-----
--RISGSSRLGAEHFASISSR---QQTSSVGVNPQ--PLPPP----SSSSQFGSP-LFWI
GVGVGLSAIFSL--------VATRVK------NYAMQQAFKSMMNQMNTQ-----ND---
------QFNNPA---FS------PG--SAFPFPTP--PA---------SVPASSPPFPTS
STSRPATSPSYPTSSAS----TS-----PSVASQPA-VTVDVSATKV----EAA------
---------------------S-------VTD-------------------AKDEAEIT-
KEPKKY------------AFVDVSPE--ETFPKS-------------------PFKSNE-
---DILETST-----------------SK-----------DTQFN-----PEV-------
--------------LQNGAASNQ----GAAD---FTGSQS--T--RKAGSGLSVEALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPSTFKWMLQNPQYRQQLEEMLNNM-SGT
-GEW-DNRMMDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PEIAMAFQNPRVQQAIMD--------------CSQNPLSIAKYQND
KEVMDVFNK-ISELFPGVR---P-------------------------------------
-------------------
>Carica_papaya_gnl|BL_ORD_ID|2452 _evm.model.supercontig_116.57|PACid:16406315
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL-------NGVLVSS---------------SPKLLL----
GY-----GCNHKIPKTLNYS----------------------PLRLPF-ALRSS-----R
VCRR-----NSTISV-SAL--SHSR--------------------------------YSR
PAVTSHTGKSGGDRFGSISSS-TDQQTSSVGVNPN-LTVPPP------ASSVGSP-LFWI
GVGVGLSAVFSW--------AASSLK------KYAMQQAMKTMMSQMNTQ-----NN---
------QFSNVP---FP------PG--SPFPYPKP--PT---------TGP---------
------------TTSP---------------ASQPT-VTVDVAATKV----EAA------
---------------------P-------TTD-------------------AKEESETE-
TKQKKY------------AFVDVSPE--ETTQKS-------------------PFASFE-
---DVPEISS-----------------SK-----------NSQFP-----KEV-------
--------------SQNGAASKQ----AVDS---SEGSQS-------FRPGLTVDALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLQDMLNNM-SGS
-GEW-NNNMMETLKGFDLNSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PEVAMAFQNPKIQAAIMD--------------CSQNPLSIAKYQND
KEVMDVFNK-ISELFPGVT---G-------------------------------------
----------------YP-
>Mimulus_guttatus_gnl|BL_ORD_ID|5714 _mgv1a006810m|PACid:17675109
--ME--------------------------------------------------------
------------------------------------------------------------
----------------------------NLGLVSS----------------PKIVL----
GV-----SPNPRNSVISSKP----------------------LVGLPN-LLKKTGNYGRH
TTIH-----TSSLQV-LSL--FRSP----------------------------------K
PTKTIVSEKAAKDRFATISSS--GQETSSVGVNPQ-LSV-PP------SSQVGSP-LFWI
GVGVGLSALFSF--------VAGRLK------KYAMEQAFKTFTQQMNTQ-----NS---
------PFGNAA---FS------PG--SPFPFP----PA---------TSP---------
------------ALDPFRTST--------PLASQP--ITVDVPASKV----EDP------
---------------------P-------SIS-------------------VKDEVEQE-
TGPKKY------------AFVDVSPE--ETLQKN-------------------AFENYK-
---ESIQTDS-----------------PK-----------DPQSS-----QSV-------
--------------SQNGTAWNQ----GAGG---SEGPTT-----SKTAPLMSVEALEKM
MEDPTVQQM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLQDMLNNM-GGT
-PEW-DNRMMDSLKNFDISSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PDVAMAFQNPRVQAAIMD--------------CSQNPMSIAKYQND
KEVMDVFNK-ISELFPGVA---G-------------------------------------
----------------S--
>Populus_trichocarpa_gnl|BL_ORD_ID|20359 _POPTR_0004s08560.1|PACid:18226590
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NP-------RLALLSS--------------SSPKLVM----
GY-----PTSLKNPTTPKFS------------------ISTTRPSLPF-SLRIS-----K
TAPH-----ASIFSI-SAL--ANSH-----------------------------------
-------GKLGSEYFASISSS-SGKQTASVGVNPQ--PVSPP------PSQIGSP-LFWV
GVGVGLSAIFSW--------VATRVK------NYAMQQAFKSLTEQMNTQ-----NN---
------QF-NPA---FS------AR--PPFPFSPP--PA---------SHP---------
------------STSPS------------PAASQPA-ITVDIPATKV----EAA------
---------------------P-------TTD-----------VGKEKETDFLEERKIK-
EETKKY------------AFVDISPE--ETSLNT-------------------PFSSVE-
---DDNETSS-----------------SK-----------DVEFA-----KKV-------
--------------FQNGAAFKQ----GPGA---AEGSQS-------TRPFLSVEALEKM
MEDPTMQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLEDMLNNM-GGS
-GKW-DSQMMDSLKDFDLNSAEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PDVAMAFQNPRVQQAIME--------------CSQNPINITKYQND
KEVMDVFNK-ISELFPGMT---G-------------------------------------
-------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|4786 _POPTR_0017s02900.1|PACid:18210818
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NP-------RLSLLSC--------------SSLKLVS----
GY-----PTSLKNPTTPKFS------------------ISTTRPSLPF-PHRTS-----K
TVTH-----TSRISI-SAL--SQSH-----------------------------------
--GPRRTSKNGSEYFASISSL-SGQQTASVGVNPQ--SVSPP------PSQIGSP-LFWV
GVGVALSAIFSW--------VATRLK------NYAMQQAFKSLTEQMNAQ-----NN---
------QF-NPA---FS------AR--SPFPFSPP--PA---------SQP---------
------------ATSPF------------QTASQPA-VTVDIPATKV----EAA------
---------------------P-------ETD-----------ARKEKETDTLEEREIK-
EEPRKF------------AFVDVSPE--ETSLNT-------------------PFSSVE-
---DVIDTSS-----------------SK-----------DVQFA-----KEA-------
--------------SQNGATFKQ----GPSASEPSEGSQS-----SQKAGSLSVEALEKM
MDDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLEEMLNNM-SGS
-SEW-DSRMVDSLKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PDVALAFQNPRVQQAIME--------------CSQNPLSIAKYQND
KEVMDVFNK-ISEIL-------G-------------------------------------
-------------------
>Malus_domestica_gnl|BL_ORD_ID|28768 _0000173318|PACid:22648745
--MEIEMEGVLENEIKRKGGRDAGLKEGDGREGKSGRGKRKPKSGIFVHVFREFDSKFQT
EFGKLKSEFREGGEEKEKLVFKRYFTKFRWPLRVSGSDGPSVWLRLHVQRGRVGWGLGRL
LRALFLDFLVANHDVTISSSL-------ASSLAAAPLFKPTKNXRSLIQSIPSLSM----
---L---RQSQKLQKSPEFQSQXSRWSLHCHSPPSLNELGSEKSSKPC-XEAXR-----K
TVAS-----TEISTC-SGL--EXADELCCTQTHAYGEXXLVDFICVLKVVIIGLQLQELS
TFGDKDWAKLEVXRFASISSS-STQETSSVGVNPQ-ISVPPP------PTN---------
--------------------VATRLK------NYAMQQAFKTLMGQMNPQ-----DS---
------QFNNAG---FS------PG--SPFPFPPA--SG---------SGP---------
------------FGSPF------------PPTSQHS--TVDVSATRV----DAAPSAPAA
PASSATEATPTTPITSTAPSTP-------TTD-------------------VKSDSELN-
KKSNRFVXFIDCCKNMSEAFVDVTPE--ETEQKS-------------------PFES---
---------S-----------------FK-----------DV--------SEV-------
--------------SQNGAAFKQ----GADS---FTSSQS--T--GKAKPAMSVEALEKM
LEDPTVQKMESHLSVKNLTFIGRWSSFXXDLTFY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPQYRQQLEDMLNNM-GGS
-SEW-DNRMMDSLKNFDLSSPEVKQQF------DQIGLSPEEVIS---KIMAN-------
--------------PEVAMAFQNPRVQAAIMDRWKTGWVGSWEWWECSQNPLSIAKYQND
KEVMDVFNK-ISELFPGVS---G-------------------------------------
----------------SP-
>Linum_usitatissimum_gnl|BL_ORD_ID|32755 _10002287|PACid:23171935
--MA--------------------------------------------------------
------------------------------------------------------------
-------------------------------LISTP-----------SSCSPKLVI----
GYP----PTSLLNPTTP-------------------------RRTLPYLHLRSC-----R
ILPP-----RSRFSA-SAS--YQGD-------------------------AAPPQAQPAA
RSATSRRGKSGAGNFASIFSS-KGQNTSSVGVTPQ-PVATPP------PSQVASY-----
--------LKVS--------VLDIHG------KYAMQQAMKTMMSQMNTQ-----NS---
------QFGGNT-----------PI--SPFQFPMPSVPE---------TSP---------
--SRPTSSPSWPASAPSYSKSAATEAATSPAPSQSR-ITVDVSAT------EEA------
---------------------S-------STN-------------------VNNEVDSK-
EDKKKY------------AFVDVSPEDKETLVGT-------------------PFGSAD-
---DGNETSS-----------------IK-----------DAPFE-----VEA-------
--------------SQNGAAFKQDTSAGAAA---AEGSQS-----TGSGPALSVEALEKM
MEDPTVQQM---------------------VFPY--------------------------
-------------------------LPEEMRNPTTFKWMLQNPEYRQQLQDMLNNM-GGS
-NGW-DPSMLDSMKNFDLSSPEVKQQF------DQIGLTPEEVIS---KIMAN-------
--------------PDVAMAFQNPRVQQAIME--------------CSQNPMSITKYQND
KEVMDVFNK-ISELFPGVS---G-------------------------------------
----------------SPY
>Arabidopsis_lyrata_gnl|BL_ORD_ID|5848 _488521|PACid:16039595
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL---------TLVSC------------SASSPKLLI----
GCNF---TSSLKNPTGF--------------------------------SRRTP-----R
IVLR-----CSKISA-SAQ--SQSP------------------------------SSRPD
NTGEIVVVKQRSKAFASIFSSSRDQQTTSV-ASPS-VPVPPP-----SSSTIGSP-LFWI
GVGVGLSALFSL--------VTSNLK------KYAMQTAMKTMMNQMNTQ-----NS---
------QFNNPG---FP------SG--SPFPFPFP--PQ---------TSP---------
------------ASSPF------------QSQSQSSGATVDVTATKV----DTP------
---------------------P-------STKPKPT---PAKDIEVDKPSVVLEASKEK-
KEEKNY------------AFEDISPE--ETTKES-------------------PFSNYA-
---EVSETSS-----------------PK-----------ETRLF-----EDV-------
--------------LQNGAGPAN----GATA---SEVFQSLGG--GKGGAGLSVEALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPETFKWMLKNPQYRQQLQDMLNNM-SGS
-GEW-DKRMTDTLKNFDLNSPEVKQQF------NQIGLTPEEVIS---KIMEN-------
--------------PDVAMAFQNPRVQAALME--------------CSENPMNIMKYQND
KEVMDVFNK-ISQLFPGMT---G-------------------------------------
-------------------
>Tic40_gi|30387547|gb|AAP31939.1| At5g16620 [Arabidopsis thaliana]
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL---------TLVSC------------SASSPKLLI----
GCNF---TSSLKNPTGF--------------------------------SRRTP-----N
IVLR-----CSKISA-SAQ--SQSP------------------------------SSRPE
NTGEIVVVKQRSKAFASIFSSSRDQQTTSV-ASPS-VPVPPP-----SSSTIGSP-LFWI
GVGVGLSALFSY--------VTSNLK------KYAMQTAMKTMMNQMNTQ-----NS---
------QFNNSG---FP------SG--SPFPFPFP--PQ---------TSP---------
------------ASSPF------------QSQSQSSGATVDVTATKV----ETP------
---------------------P-------STKPKPT---PAKDIEVDKPSVVLEASKEK-
KEEKNY------------AFEDISPE--ETTKES-------------------PFSNYA-
---EVSETNS-----------------PK-----------ETRLF-----EDV-------
--------------LQNGAGPAN----GATA---SEVFQSLGG--GKGGPGLSVEALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPETFKWMLKNPQYRQQLQDMLNNM-SGS
-GEW-DKRMTDTLKNFDLNSPEVKQQF------NQIGLTPEEVIS---KIMEN-------
--------------PDVAMAFQNPRVQAALME--------------CSENPMNIMKYQND
KEVMDVFNK-ISQLFPGMT---G-------------------------------------
-------------------
>Thellungiella_halophila_gnl|BL_ORD_ID|25183 _Thhalv10013528m|PACid:20204858
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL---------TLVSC------------SASSPKLLI----
GCNF---TSSLKNPVGF--------------------------------SRRTP-----K
VVFR-----CSKISA-SAK--SQSH------------------------------SSRPE
NAGEIVVVKHRSRDFASIFSSNRDQQTTSV-AYPN-AAVPPP-----SSSTIGSP-LFWI
GVGVGLSALFSW--------VTSSLK------KYAMQTAMKTMMNQMNTQ-----NS---
------QFNNPG---FP------AGSASPFPFPFP--PQ---------TSP---------
------------TSSPF------------QSQSQSSGATVDVTATKV----DTP------
---------------------P-------SAKPQPT---PAKKTEVDKPSVVLEENKAK-
KEEKNY------------AFEDVSPE--ETTKES-------------------PFSNYA-
---EVSETSA-----------------PK-----------EARLF-----EDV-------
--------------MQNGAAPAN----GATA---SEVFQSLGA--GKGGPGLSVEALEKM
MEDPTVQKM---------------------VYPH--------------------------
-------------------------LPEEMRNPETFKWMLKNPHYRQQLQDMLNNM-SGS
-GEW-DKRMMDTLKNFDLNSPEVKQQF------DQIGLTPEEVIS---KIMEN-------
--------------PDVAMAFQNPRVQAALME--------------CSENPMNIMKYQND
KEVMDVFNK-ISQLFPGMT---G-------------------------------------
-------------------
>Capsella_rubella_gnl|BL_ORD_ID|22852 _v10000974m|PACid:20908651
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL---------TLVSC------------SASSPKLLI----
GCNF---TSSLKTPVGL--------------------------------SRRTP-----K
IVFR-----CSKISA-SAQ--SHSQ----------------------------PPSSLPE
N--EAVVVRHRSKAFASIFSSSREKQTTSV-APPS-VPVPPP-----SSSTIGSP-LFWI
GVGVGLSALFSL--------------------KYAMQTAMKTMMNQMNTQ-----NS---
------QFNNPG---FP------SG--SPFPFPFP--PQ---------PSP---------
------------ASSPF------------QSQSPSSGATVDVMASKV----DTP------
---------------------P-------STKPQPK---PAKDIEVDKPSVVLEENKVK-
KEENNY------------AFEDVSPE--ETTKES-------------------PFSNYA-
---EVSESSA-----------------PK-----------ETRLF-----EDV-------
--------------LQNGAGPAN----GATA---SEVFQSLGG--GKGGPGLSVEALEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPETFKWMLKNPQYRQQLQDMLNNM-SGS
-GEW-DKRMTDTLKNFDLNSPEVKQQF------NQIGLTPEEVIS---KIMEN-------
--------------PDVAMAFQNPRVQAALME--------------CSENPMNIMKYQND
KEVMDVFNK-ISQLFPGMT---G-------------------------------------
-------------------
>Brassica_rapa_gnl|BL_ORD_ID|10046 _008608|PACid:22693556
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL---------TLVSC----------SASSSSPKLLI----
GCNF---TSSLKPPVGF--------------------------------SRRSP-----K
ILLR-----RSKISASSAQ--SHSP---------------------------------SD
STGEIVVVKHKTKAFASIFSSRSDKQTASV-ASPS-VAVPPP----SSSSTIGSP-LFWI
GVGVGLSALFSW--------VTSNAK------KYAMQTAMKTMMNQMNTQ-----NS---
------QFNNPG---FPTGAGAGSG--SPFPFPFP--PQ---------TSP---------
------------TSSPF------------QSQSQSSGATVDVTATKV----DRP------
---------------------P-------VSKPQTTPTPPTKNIEVDKPSVVLEENKAK-
KEEKNY------------AFEDVSPE--ETTKES-------------------PFSNYA-
---EVSEASA-----------------PK-----------ETRLF-----DDV-------
--------------LQNGAAPAN----GATA---SEVFQSLGA--GKGGAGLSVEALEKM
MEDPTVQKM---------------------VYPH--------------------------
-------------------------LPEEMRNPETFKWMLKNPQYRQQLQDMLNNM-SGS
-GEW-DKRMTETLKNFDLNSPEVKQQF------DQIGLTPEEVIS---KIMEN-------
--------------PDVAMAFQNPRVQAALME--------------CSENPMNIMKYQND
KEVMDVFNK-ISQLFPGMT---G-------------------------------------
-------------------
>Citrus_clementina_gnl|BL_ORD_ID|35771 _0.9_010946m|PACid:19286967
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL-------NMALVSS--------------TSPKLVL----
------NYTNFKHPTRGITG-----------------------------PRRSS-----S
LALPFKLS-TSRISA-SVR-----------------------------------------
-AGPYQNGQVGAGGFASLTSS-SGQQTSSVGVNPN-LPMPPP------SSNVGSP-LFWV
GVGVGLSALFSF--------VASRLK------QYAMQQALKGMMNQMNTQ-----NK---
------PFGNAA---FP------QG--SPFPFPNP--PA---------SGP---------
-------------TTPY------------PAASQPR-FTMDIPATKV----EAA------
---------------------S-------ATD-------------VEGKKEVKGETEVK-
EEPKKY------------AFVDVSPE--ETLQKS-------------------PFDNFE-
---DVKETSS-----------------SK-----------DAQPP-----KD--------
--------------SQNGAAFNY----NAGS---PLGGQS--A--KKEGRFLTVDTLEKL
MEDPQVQKM---------------------VYPS--------------------------
-------------------------LPEEMRNPASFKLMLQNPEYRKQLQEMLDGM-CES
-GEF-DGRVLDSLKNFDLNSAEVKQQF------EQIGLTPEEVIT---KMMAN-------
--------------PEIALGFQSPRVQAAIME--------------CSQNPMNIIKYQND
KEVMSVITK-IAELFPGVT---G-------------------------------------
----------------TS-
>Citrus_sinensis_gnl|BL_ORD_ID|22996 _1.1g014282m|PACid:18115198
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------NL-------NMALVSS--------------TSPKLVL----
------NYTNFKHPTRGITG-----------------------------PRRSS-----S
LALPFKLS-TSRISA-SVR-----------------------------------------
-AGPHQNGQVGAGGFASLTSS-GGQQTSSVGVNPN-LPMPPP------SSNVGSP-LFWV
GVGVGLSALFSF--------VASRLK------QYAMQQALKGMMNQMNTQ-----NK---
------PFGNAA---FP------QG--SPFPFPNP--PA---------SGP---------
-------------TTPY------------PAASQPR-FTMDIPATKV----EAA------
---------------------T-------ATD-------------VEGKKEVKGETEVK-
EEPKKY------------AFVDVSPE--ETLQKS-------------------SFDNFE-
---DVKETSS-----------------SK-----------DAQPP-----KD--------
--------------SQNGAAFNY----NAGS---PFGGQS--A--KKEGRFLTVDTLEKL
MEDPQVQKM---------------------VYPS--------------------------
-------------------------LPEEMRNPASFKLMLQNPEYRKQLQEMLDGM-CES
-GEF-DGRVLDSLKNFDLNSAEVKQQF------EQIGLTPEEVIT---KMMAN-------
--------------PEIALGFQSPRVQAAIME--------------CSQNPMNIIKYQND
KEVMSVITK-IAELFPGVT---G-------------------------------------
----------------TS-
>Brachypodium_distachyon_gnl|BL_ORD_ID|23259 _5g10800.1|PACid:21826029
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------SL---------ILASS------------CSAYPRLPPLPA-
ARR-----PSQPLP--ATSL-----------------------------SAGAG-----R
RGAR-----RPRLVV------SAAA-----------------------------------
RGSRNVLDGLNTTAFASISSS-TSSENTSTGTGTL-PPMPPP------SSYIGSP-VFWI
GIGIALSAAFSM--------VSSMVK------KYAMEQAFKSMMTQTPPN----------
-----------T---FG------TN--SPFPFSMP--PQ---------AGS---------
---TAPSS--YPYSGPR------------KNTSPNG-TTVDVSATDV----AAT------
---------------------E-------TSE-------------------VADVIETS-
KPSKKF------------AFVDVSPQ--ELQQKE-------------------LQSSLE-
---TVDVKGA-----------------ST-----------ESEVK-----EDAEQNV---
--------------PTNGAAFKP----TEDS---STGPTE--S--SKSGPMLSIDTIEKM
MEDPAVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPDSFKWMLQNPMYRQQLEDMLNNM-GAS
PDQW-DNRMVDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KIMAN-------
--------------PEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQND
KEVMDVFMK-ISQIFPQIN---G-------------------------------------
-------------------
>Oryza_sativa_gnl|BL_ORD_ID|12651 _LOC_Os04g35900.1|PACid:21895123
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------SL---------VLASS------------CSASPRLPPLSA-
ARRRR--PSSQTLPAT---------------------------------AAASG-----R
RGAG-----RSKLVVVAAA--AAAA-----------------------------------
RGSGNGFEGLKTNGFASMSSS-TNSENMSTGTGSL-PPMPPP------SSYIGSP-VFWI
GVGVALSAAFSM--------VSSMVK------KYAMQQAFKSMMTQAPPN----------
-----------T---FG------SN--SPFPFAMP--PQ---------AAP---------
---AAPSS--YPYSQPR------------KDTSPQS-ATVDVSATKV----EAT------
---------------------G-------TLE-------------------EADVAE---
QPKKKF------------AFVDVSPE--ELQQKE-------------------LQSSLE-
---TVDVKSE-----------------SK-----------QSETM-----EDTEQKA---
--------------PTNGTAFKM----NEGS---ASGTTE--S--SNSGPMLSVDTIEKM
MEDPAVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPDSFKWMLQNPMYRQQLQDMLNNM-GGS
PDQW-DNRMLDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KIMAN-------
--------------PEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQND
KEVMDVFMK-ISQIFPQIN---G-------------------------------------
-------------------
>Panucum_virgatum_gnl|BL_ORD_ID|12878 _Pavirv00024278m|PACid:23768727
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------SL---------VLASS------------CSASPRLPVLSAS
AARLRGLPGAAPLP---ASS-----------------------------AAGAA-----R
SGAR-----RPRLLVAVAA--AAAP-----------------------------------
RGSRNVFEGLRAKGFASVSSS-TGNENVSTGTGTL-PPMPPP------SSYFGSP-VFWI
GVGVALSVAFTT--------VSSMVK------RYAMQQAFKSMMTQSPSN----------
-----------S---FG------SN--SPFPFAMP--PQ---------AAP---------
---TAPSS--YPYSQPK------------RDTSPQV-ATVDVLATEV----EAS------
---------------------G-------TPK-------------------EADVAETP-
KPSKKF------------AFVDVSPE--ELQQKN-------------------LQSSLE-
---TVDVKRD-----------------ST-----------DSESK-----EDTEQKV---
--------------PTNGAVFKP----NEDA---ARGPTE--S--SNSGPMLSVETIEKM
MEDPAVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPDSFKWMLQNPMYRQQLQDMLNNMGGSS
PDQW-DNRMLDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KIMAN-------
--------------PEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQND
KEVMDVFMK-ISQIFPQIN---G-------------------------------------
-------------------
>Setaria_italica_gnl|BL_ORD_ID|21201 _Si010149m|PACid:19694675
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------SL---------VLASS------------CSASPRLPVLSA-
AARFRGLPGAAPPT---AAS-----------------------------TGGAA-----R
GGAR-----RPRLLV---A--AAAP-----------------------------------
RGSRNAFEGLRAKGFASVSSS-TSNENTSTGTGTL-PPMPPP------SSYIGSP-VFWI
GVGVALSVAFTT--------VSSMVK------KYAMQQAFKSMMSQSPSN----------
-----------S---FG------SN--SPFPFAMP--PQ---------AAP---------
---TAPSSYPYPYSVPK------------KDTYPQA-ATVDVSATEV----EAA------
---------------------G-------TSK-------------------EADVAETP-
KPSKKF------------AFVDVSPE--ELQQKN-------------------LQSSLE-
---TVDVKSD-----------------ST-----------DSESK-----EDTEREV---
--------------PTNGEAFKP----NEGA---ARGPTE--S--SNSGPMLSVETIEKM
MEDPAVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPDSFKWMLQNPMYRQQLQDMLNNM-GSS
PDQW-DNRMVDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KIMAN-------
--------------PEVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQND
KEVMDVFMK-ISQIFPQIN---G-------------------------------------
-------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|19148 _Sb06g017360.1|PACid:1972504
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------SL---------VLASS------------CSASPRLPLISS-
AARFRRLPGSVPPPTVAAAS-----------------------------TGGAA-----R
KGPR-----RPRLFV--VA--AAAP-----------------------------------
RGSGNVFEGLRAKGFASVSSS-TGNENMSTGTGTL-PPVPPP------SSYFGSP-VFWI
GVGVALSVAFTT--------VSSMVK------RYAMEQAFKSMMTQAPPN----------
-----------S---FG------SN--SPFPFGMP--PQ---------ASP---------
---TAPSS--FPYLEPK------------KDTSPQV-STVDVSATEV----EAA------
---------------------G-------TSK-------------------EVDVTETP-
EPSKKF------------AFVDVSPE--ELQQKN-------------------LQSSLE-
---TVDVKHD-----------------ST-----------DSESK-----EDIEEKV---
-------------LPTNGATFKP----NEDA---ARGPTE--P--SNSGPMLSVETIEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPDSFKWMLQNPMYRQQLQDMLNNM-GAS
PDQW-DNRMVDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KIMAN-------
--------------PDVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQND
KEVMDVFMK-ISQIFPQIN---G-------------------------------------
-------------------
>Zea_mays_gnl|BL_ORD_ID|52243 _GRMZM2G353213_T02|PACid:20872059
--ME--------------------------------------------------------
------------------------------------------------------------
-------------------SL---------ILASS------------CSASPRLPLLSS-
AARFRGLPVSVPPP--SSAS-----------------------------ISGAA-----R
KGPM-----RPRLFV--AA--AAAP-----------------------------------
RGSGNVFEGLRAKGFASMSSS-TGNENMSTGTGTL-PPMPPT------SSYIGSP-VFWI
GVGVALSVAFTT--------VSSMLK------RYAMQQAFKSMMTQSAPN----------
-----------S---FG------SN--SPFPFSMP--PQ---------ASP---------
---TAPST--YPYLEPK------------KDTSPHV-STVDVSANEV----EAT------
---------------------G-------TSK-------------------EVDVTETP-
KPSKKF------------AFVDVSPE--ELQQKN-------------------LQSSPE-
---TVDVKHDSTYSESKEDTEEQVPTIST-----------NTESK-----EDTEEKV---
--------------PTNGASFKL----NEGA---AHGPTE--S--NNSASMLSVETIEKM
MEDPAVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPNSFKWMLQNPMYRQQLQDMLNNM-GAT
PDQW-DNRMLDHLKNFDLSSPEVRQQF------AQVGMTPEEVVS---KIMAN-------
--------------PDVAVAFQNPKIQTAIMD--------------CSQNPLNIVKYQND
KEVMDVFMK-ISQIFPQIN---G-------------------------------------
-------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|13162 _Pp1s159_2V6.1|PACid:18049697
MAME--------------------------------------------------------
------------------------------------------------------------
-------------------SR---------LLQAG------------DVSSPRGCFIVSS
ARDGAGHRQGQHGFRVSAQRFMRGVQVRQGGNV----------------CGRLE-----K
KVSK-----SKSVVV-AAR--KSTQ----------------------------------E
QRETVVSKDDSNEYIESSAEA-QGSG----------------------YSYIGSP-LLWI
GVGVGLSALFSF--------GANAVK------RYAMQQMLKSMTGSAGGP-----GASPF
GSPGANPFGAPGGNPFAGMPMPPPG--AGFPFPMP--PT---------AAS---------
-----------PSPSPV-------------SAAAAA-PPVDVSPTNV----TSS------
---------------------Q-------PSV-------------------VSETPKTS-
TDAKKT------------AFTDVNAN--EILERE-------------------QQAAAA-
---RFSDQAP-----------------SA-----------SEPTRPYFADPEL-------
--------------VDSKSGSNS----GAGAGPSSNDPWNSAG--KGKQTVFTVDQLEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMMQNPQYRQQLQDMLNSM-GGD
-GAW-DNRMSDMLNNFDLNSTEVKQQF------EQIGLTPEEVVA---KIMAN-------
--------------PEVAVAFQNPKVQAAIMD--------------CSTNPLNITKYQND
KEVMDVFNK-ISELFPGMN---G-------------------------------------
----------------SPF
>Physcomitrella_patens_gnl|BL_ORD_ID|11546 _Pp1s110_13V6.1|PACid:18048081
MAME--------------------------------------------------------
------------------------------------------------------------
-------------------SR---------VFHAGS-----------SVASSRACFVVSS
ARAGSGHRQGQQGFQVAAQRFMRGAKLRDVGIE----------------CGRCG-----K
KGSR-----SEGIVA-AAR--KSTP----------------------------------E
QEEYVVTKNDSNEYIESIAES-QGSG----------------------SSYIGSP-LLWI
GVGVGLSALFSF--------GANSVK------RYAMQQMLKSMSGGAGGP-----GAS--
------PFGAPGGNPFAGMPMPPPG--AGFPFPMP--PT---------GS----------
------------VSSPV-------------SAAAAA-APVDVSP-NV----TSS------
---------------------Q-------PSV-------------------VSETPKSS-
TEPKIA------------AFTDVNAT--EILERE-------------------QQAAAAA
AASRFSDQSP-----------------SA-----------QEPTRPFFADSEV-------
--------------VDSKGGSYS----GAGAGP-SNDPWDSAG--KAKQTVFSVEQLEKM
MEDPTVQKM---------------------VYPY--------------------------
-------------------------LPEEMRNPTTFKWMMQNPQYRQQLQDMLNSM-GGD
-GAW-DNRMSDMLKNFDLNSTEVKQQF------EQIGLTPEEVVA---KIMAN-------
--------------PEVAVAFQNPKVQAAIMD--------------CSTNPLNITKYQND
KEVMDVFNK-ISELFPGMA---G-------------------------------------
----------------SPF
>Selaginella_moellendorffii_gnl|BL_ORD_ID|19216 _437721|PACid:15420494
MAMA--------------------------------------------------------
------------------------------------------------------------
------------------HSL---------GFGALALHWRDGAPGAGTSSSVRFYG----
-------------------------------------------------SRRAP-----Q
RLVLSPLSNRERLSV---------------------------------------------
----------------RCQSRSPAQDQAAGSAELQTVSVPPT-----QPAYIGSP-LLWV
GVGVGLSVLFSW--------AANYVK------KQAMQQALKSMMS--GPG-----QN---
------QFGNM------------PI--PPFPFPVP--PQ---------PQQ---------
---QPMPTFQPPVSSPQ--------------ATQPQ---ASASATAVVESTEAA------
---------------------S-------YSE-------------------TQTPTPV--
SENNKP------------AFTDVNVE--AEVSTV-------------------KINA---
---EATEVKE-----------------NA-----------NDVFF---KDAEV-------
--------------RDSGTGFTWN---TDGA---ASTSSS--D--GKANSFFSVENLEKM
LEDPTVQQM---------------------VYPY--------------------------
-------------------------LPQEMRNPSTFKWMMQNPQFRTQLQEMLNNM-TED
-GAWKNGQMGDVLKNFNPNNQELKQQF------EQIGLSPEEVMA---KMVAN-------
--------------PEIAMAFQNPKIQAALID--------------CSQNPTNITKYQND
KEVMDVFNK-IAELFP-IK---G-------------------------------------
----------------F--
>Cucumis_sativus_gnl|BL_ORD_ID|15634 _173410.1|PACid:16966613
--MM--------------------------------------------------------
------------------------------------------------------------
-------------------LL---------------------------------------
------------------------------------------------------------
------------IFIPSLF--DSSL-----------------------------------
--FSSLTWKPVAERFATVSSSTTSNDSSSVGV-PS-VSIPPP------SSYVGSP-LFWV
GVGVGLSALFTW--------------------KYAMQQAFKTMMSQMNSQ-----NS---
------PMSNPT---LS------SG--SPFPTPPT--FA---------TGT---------
------------TISPS--------------VSEPA-VSIDVTATKV----EEE------
---------------------P-------VTN-------------------VKSRTE-N-
MEAKKF------------AFVDVSPE--ETDQKS-------------------PFKE---
---DATDADV-----------------SK-----------SAQPT-----EEL-------
--------------PQNGAASKQ----AYNG---SDGSQF--S--RKPGSVLSVEAVEKM
MEDPTVQKM---------------------IYX---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|15848 _12.g508000.t1.1|PACid:19874172
--ML--------------------------------------------------------
------------------------------------------------------------
---------------------------------------------CSRTTAPRGFGKAAL
ALP------------------------------------------------SRA-----S
IKCRAVQGSDQQQVVSAPVEAVAAP-----------------------VPVPVAGAPLPQ
ETTATYPMPPPAPYYPGMPADAAARQQYYMAAPAAAYYPPPPAPYKEEPASTGAPWWIWL
GAGVILGQVLAK--------VQEYMKNPKTPQQIMMEMAMKQMSGAMGSPPGGAGMP---
------PFGGPG---------------SPFGGAAP--GANPFAGAAPGANP---------
------------FANFA------------AAAAAGP-STVDTTASPA----FAG------
---------------------A-------SSS-------------------GASSSE---
RKGEKF------------A-SRLNSEGREPRKPEPAPAAAAAGAAAAASSATKPLDVVEP
VVKEPSSSGS-----------------SSGASSSG-----RSSFF-----ADV-------
--------------DAEASSRAG----GTSS---SSGSG---A--APQDTGVMTDMMESM
LRNPEMQKM---------------------LYPY--------------------------
-------------------------LPEPMRNPQSIEWMLSNPEVKKQMEQMFASQ----
-NVM-SPQMMDMMKGMDFNQDKVNKQF------AELGLKPEDVIS---KVMAN-------
--------------PDLAAGFSNPKVQAAIMD--------------ISQNPMNIVKYQTD
PEIMKVLEK-VTEIFQPQM---G-------------------------------------
----------------GQK
>Volvox_carteri_gnl|BL_ORD_ID|13829 _Vocar20000831m|PACid:23137724
--ML--------------------------------------------------------
------------------------------------------------------------
---------------------------------------------RTRIAIPRGIGRVRP
LAPR---------------------------------------------PVANL-----R
VRCQATTGGDQQPSVAPAVEVTAPP-----------------------VVAPVAPIP---
ETTATYVMPPNPMYYQGMP---APRQDYYMAAPPAAYYPPPPAPYKEEPASSGAPWWIWL
GLGVILGQVLAK--------VQEYMKNPKTPQQIMMEMAMKQMSGAMGS-TTGAGMP---
------PFGGAA---------------SPFGGPAG--GA---------ANP---------
------------FANFA------------AAASAAPAATVDTTASAV----QAG------
---------------------AFTPSPPSSSS-------------------STNGEV---
RKGEKF------------A-SRLSSEGREPRKVE-------------LPQASKPLDVVEP
VVKEPSTSSS-----------------SSTNSSSAGASKPRSSFF-----ADV-------
--------------DMDATV-------TSTS---ASSSA---A--ADGNSAVMSEMMESM
LRNPEMQKM---------------------LYPY--------------------------
-------------------------LPEPMRNPQSIEWMLSNPEVKKQMEQMFAQQ----
-NVM-SPQMMDMMKNMDFNQEKVNRQF------AELGLKPEDVIS---KVMSN-------
--------------PELAAGFSNPKVQAAIID--------------ISSNPMNIVKYQTD
PEIMKVLEK-VTEIFQPQM-----------------------------------------
----------------NQK
>Cyanophora_paradoxa_gnl|BL_ORD_ID|24807 _ConsensusfromContig41017-maker-ConsensusfromContig41017-snap-gene-0.0-mRNA-1:cds:9353/591-643:1:-
--MA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
G-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------RFFA
GIGNILG-----------------------------------------------------
---------------------------KPFPFSLP--P----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GVKMEDVAKMQMEIMKD-------
--------------PKLVEMMRNPKFVGAMQN--------------MMKDPSKAMEYLRD
PEVLAVVQR-FEQTFKNLKPPGA-------------------------------------
----------------PQP
>Cyanophora_paradoxa_gnl|BL_ORD_ID|15239 _ConsensusfromContig9128-snap_masked-ConsensusfromContig9128-abinit-gene-0.1-mRNA-1:cds:2242/836-1056:0:+
--MA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------FV
G-GVTPAQLCSR--------SSGFLSSAEKATRIASAGHMRKARGA--------------
------KFSVSA------------------------------------------------
-------------------------------------VTINPAPSKA----EEK------
--------------------------------------------RGRVLQSFFNKSE---
------------------LYLIRSPTAKKVLDAL--------------------------
--------------------------------------------------AKV-------
----------------------------------GERPRNDHIAFRSFGYGLGITALEEL
FLEAGFKRM---------------------EQLY--------------------------
-------------------------FPDKHLR------AHPSPQL---------------
---------------SDDAAPEQERVFISELIIDELSAKAQGIIK---RYLDE-------
--------------ADPAA--RKFGILSSLME----------------------------
-------ER---------------------------------------------------
-------------------
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|529 _gnl|CMER|CME023C fusion protein of phosphoribosylaminoimidazole carboxylase and phosphoribosylaminoimidazole-succinocarboxamide synthase, chloroplast or mitochondrial precursor
--MF--------------------------------------------------------
------------------------------------------------------------
------------------------------GFVTSTSSPLGLRFSSFHSNTITCFHHVSS
GKNQFGGTCRTA-------------------------------------NGAPA-----R
LGSRRLAPPRVLRTLNCSTMDLTAP-----------------------------------
--------------VTSSGNNSIGDHSAQGRLTPLVPILMGSKADKKHCDQIAAA-CHRF
GLATEMHVLSAHKVPTRLLEVVGRLE------ADPRPKVYISVAGRSNALSGLLDGSVA-
---------------------------SPVIACPP--PSDAFGGADIFSSL---------
----------------------------RMPGGIAPVVSLDPGNAAL----TAA------
------------------------------------------KILGIHDPLVRDRVRAFQ
KANRDR------------LYVD--------------------------------------
----------------------------------------DAEVATSAYLADIQAAAREN
NVLVSTDGVLSALVQQHAGTWRK-----------KQGKVRDQFYSDAAKHMILVTTDRQS
AFDRVLAAVPFKGAVLNLVSAWWFRRTEHIVPNHLIAVPHPNVTIAKRCDPFPIEFVVRG
YATGSTSTSLWKNYERGVREYCGIKLPDNLHKNQKLWMNLVTPTTKEDIGDALISR----
-QEIIDRGLMSAVD-FDACAAYALRLF-------EYG---QQVASEHGLILVDTKYEFGR
DADGQICLIDEIHTPDSSRYWLATSYEERIAS---------------GKEPENI-----D
KEILRLWYRDHCDPYKDEKLPEAPLELVTELSRRYIQLYEMITWDKFDLRLSTPSELQQA
LGPWFSGQGAKANFTMSSP
